" Name:         Forest Night
" Description:  🌲 Comfortable & Pleasant VIM Color Scheme
" Author:       Sainnhepark <sainnhe@gmail.com>
" Maintainer:   Sainnhepark <sainnhe@gmail.com>
" Website:      https://github.com/sainnhe/vim-color-forest-night/
" License:      MIT && Anti-996
" Last Updated: Sun 09 Jun 2019 07:03:32 PM CST

" Generated by Colortemplate v2.0.0b3

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'forest-night'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS'))

hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Debug Special
hi! link Include PreProc
hi! link Macro PreProc
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link Structure Type
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#132132', '#ff6a6f', '#a9dd9d', '#f0eaaa',
        \ '#7098e6', '#605779', '#7098e6', '#fffeeb', '#8d9eb2', '#fd8489',
        \ '#c9fd88', '#f0eaaa', '#98b8e6', '#e7d5ff', '#a8d2eb', '#ffffff']
  if get(g:, 'dark_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#ffebc3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#ffebc3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#ffebc3 guibg=#3c4c55 guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#ffebc3 guibg=#3c4c55 guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=fg guibg=#536273 guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=#788898 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=#3c4c55 guibg=#ffebc3 guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#4c5866 guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#4c5866 guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#788898 guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=NONE guibg=#5f8770 guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#5f87af guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=NONE guibg=#70495d guisp=NONE gui=NONE cterm=NONE
  hi DiffText guifg=NONE guibg=#536273 guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#536273 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#fd8489 guibg=#3c4c55 guisp=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#ffebc3 guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#ffebc3 guibg=#616c72 guisp=NONE gui=italic cterm=italic
  hi IncSearch guifg=NONE guibg=#70495d guisp=NONE gui=underline cterm=underline
  hi LineNr guifg=#3c4c55 guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#f0c38a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#7fc1ca guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NonText guifg=#646f7c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#ffebc3 guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#ffebc3 guibg=#616c72 guisp=NONE gui=reverse cterm=reverse
  hi PmenuThumb guifg=NONE guibg=#ffebc3 guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#a8d2eb guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=NONE guibg=#70495d guisp=NONE gui=underline cterm=underline
  hi SignColumn guifg=NONE guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#536273 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#fd8489 guibg=NONE guisp=#fd8489 gui=NONE cterm=NONE
  hi SpellCap guifg=#f0aa8a guibg=NONE guisp=#f0aa8a gui=NONE cterm=NONE
  hi SpellLocal guifg=#a8d2eb guibg=NONE guisp=#7fc1ca gui=NONE cterm=NONE
  hi SpellRare guifg=#e7d5ff guibg=NONE guisp=#605779 gui=NONE cterm=NONE
  hi StatusLine guifg=#4c5866 guibg=#a9dd9d guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#ffebc3 guibg=#4c5866 guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#ffebc3 guibg=#536273 guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#ffebc3 guibg=#4c5866 guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#4c5866 guibg=#a9dd9d guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#f0aa8a guibg=NONE guisp=NONE gui=bold cterm=bold
  hi VertSplit guifg=#616c72 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#70495d guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=#70495d guisp=NONE gui=italic cterm=italic
  hi WarningMsg guifg=#f0aa8a guibg=#3c4c55 guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#4c5866 guibg=#ffebc3 guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#a8d2eb guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi Conditional guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Define guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Number guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Float guifg=#87af87 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Character guifg=#87af87 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Boolean guifg=#c5d4dd guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Function guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Label guifg=#a8d2eb guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Tag guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#788898 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Constant guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#646f7c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreCondit guifg=#fd8489 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Special guifg=#87af87 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialComment guifg=#5f8770 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#f0c38a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#a8d2eb guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Exception guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#e7d5ff guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Type guifg=#f0c38a guibg=NONE guisp=NONE gui=bold cterm=bold
  hi StorageClass guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE cterm=NONE
  hi ToolbarLine guifg=#616c72 guibg=#536273 guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#f0c38a guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Noise guifg=#f0eaaa guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi helpExample guifg=#a8d2eb guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi helpCommand guifg=#e7d5ff guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi makeCommands guifg=#f0eaaa guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownCode guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownUrl guifg=#fd8489 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi markdownCodeDelimiter guifg=#a9dd9d guibg=NONE guisp=NONE gui=bold cterm=bold
  hi! link mkdCode markdownCode
  hi! link mkdUrl markdownUrl
  hi! link mkdCodeDelimiter markdownCodeDelimiter
  hi rstEmphasis guifg=NONE guibg=NONE guisp=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi rstStrongEmphasis guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi cmakeArguments guifg=#f0eaaa guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi htmlBold guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlLink guifg=#f0aa8a guibg=NONE guisp=NONE gui=bold cterm=bold
  hi htmlTagName guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi htmlEndTag guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi htmlSpecialTagName guifg=#f0c38a guibg=NONE guisp=NONE gui=bold cterm=bold
  hi htmlTag guifg=#f0eaaa guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link xmlTag htmlTag
  hi! link xmlTagName htmlTagName
  hi! link xmlEndTag htmlEndTag
  hi! link jsFunction Function
  hi! link jsExceptions Exception
  hi pythonDottedName guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pythonClassVar guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ocamlConstructor guifg=#f0c38a guibg=NONE guisp=NONE gui=bold cterm=bold
  hi ocamlKeyChar guifg=#a8d2eb guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ocamlKeyword guifg=#f0c38a guibg=NONE guisp=NONE gui=bold cterm=bold
  hi ocamlFunDef guifg=#a8d2eb guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi goBuiltins guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link goDeclaration Function
  hi rubyControl guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyCapitalizedMethod guifg=#f0aa8a guibg=NONE guisp=NONE gui=bold cterm=bold
  hi rubyDocumentation guifg=#788898 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyStringEscape guifg=#918175 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustEnumVariant guifg=#f0eaaa guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustFuncCall guifg=#a8d2eb guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustCommentLineDoc guifg=#918175 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustEscape guifg=#918175 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustEscapeUnicode guifg=#918175 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi rustEscapeError guifg=#918175 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi tomlTable guifg=#a8d2eb guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi tomlTableArray guifg=#a8d2eb guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi tomlKey guifg=#f0c38a guibg=NONE guisp=NONE gui=bold cterm=bold
  hi typescriptBraces guifg=#c5d4dd guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link typescriptEndColons typescriptBraces
  hi! link typescriptExceptions Exception
  hi! link typescriptFloat Float
  hi! link typescriptMessage String
  hi vimfilerColumn__SizeLine guifg=#616c72 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimfilerClosedFile guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi wastInstGeneral guifg=#f0eaaa guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi wastInstWithType guifg=#f0eaaa guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi zshDelimiter guifg=#a8d2eb guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi zshPrecommand guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEWarningSign guifg=#f0aa8a guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi ALEErrorSign guifg=#fd8489 guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi ALEInfoSign guifg=#a8d2eb guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi ALEError guifg=NONE guibg=#70495d guisp=NONE gui=NONE cterm=NONE
  hi ALEWarning guifg=NONE guibg=#b36200 guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextError guifg=#788898 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextWarning guifg=#788898 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextInfo guifg=#788898 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link ALEVirtualTextStyleError ALEVirtualTextError
  hi! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
  hi CocHighlightText guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocCodeLens guifg=#788898 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link CocErrorSign ALEErrorSign
  hi! link CocWarningSign ALEWarningSign
  hi! link CocInfoSign ALEInfoSign
  hi! link CocHintSign Label
  hi! link CocErrorHighlight ALEError
  hi! link CocWarningHighlight ALEWarning
  hi! link CocInfoHighlight ALEInfo
  hi! link CocWarningVirtualText ALEVirtualTextWarning
  hi! link CocErrorVirtualText ALEVirtualTextError
  hi! link CocInfoVirtualText ALEVirtualTextInfo
  hi! link CocHintVirtualText ALEVirtualTextInfo
  hi! link CocCodeLens ALEVirtualTextInfo
  hi NERDTreeFlags guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NERDTreeDirSlash guifg=#5f8770 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NERDTreeCWD guifg=#5f8770 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NERDTreeLinkFile guifg=#5f8770 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NERDTreeLinkTarget guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi EasyMotionTarget guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi EasyMotionShade guifg=NONE guibg=#4c5866 guisp=NONE gui=bold cterm=bold
  hi MatchParenCur guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi StartifyBracket guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifyHeader guifg=#f0aa8a guibg=NONE guisp=NONE gui=bold cterm=bold
  hi StartifyNumber guifg=#f0aa8a guibg=NONE guisp=NONE gui=bold cterm=bold
  hi StartifyPath guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifySlash guifg=#5f8770 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link StartifySpecial Comment
  hi! link StartifyFile Normal
  hi diffAdded guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi diffFile guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi diffIndexLine guifg=#f0c38a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi diffNewFile guifg=#a8d2eb guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi diffRemoved guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi gitCommitOverflow guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi gitCommitSummary guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi gitCommitSelectedFile guifg=#a8d2eb guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi gitconfigSection guifg=NONE guibg=#70495d guisp=NONE gui=NONE cterm=NONE
  if !s:italics
    hi Folded gui=NONE cterm=NONE
    hi VisualNOS gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
    hi rstEmphasis gui=NONE cterm=NONE
    hi rustEscapeUnicode gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=223 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=223 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=223 ctermbg=239 cterm=NONE
    if !has('patch-8.0.0616') " Fix for Vim bug
      set background=dark
    endif
    hi Terminal ctermfg=223 ctermbg=239 cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=238 cterm=NONE
  hi Conceal ctermfg=245 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=239 ctermbg=223 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=235 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=235 cterm=NONE
  hi CursorLineNr ctermfg=245 ctermbg=244 cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=65 cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=67 cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=95 cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=238 cterm=NONE
  hi Directory ctermfg=150 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=238 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=210 ctermbg=239 cterm=NONE
  hi FoldColumn ctermfg=223 ctermbg=244 cterm=NONE
  hi Folded ctermfg=223 ctermbg=244 cterm=italic
  hi IncSearch ctermfg=NONE ctermbg=95 cterm=underline
  hi LineNr ctermfg=239 ctermbg=244 cterm=NONE
  hi ModeMsg ctermfg=222 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=110 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=244 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=223 ctermbg=244 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=244 cterm=NONE
  hi PmenuSel ctermfg=223 ctermbg=244 cterm=reverse
  hi PmenuThumb ctermfg=NONE ctermbg=223 cterm=NONE
  hi Question ctermfg=153 ctermbg=NONE cterm=NONE
  hi Search ctermfg=NONE ctermbg=95 cterm=underline
  hi SignColumn ctermfg=NONE ctermbg=244 cterm=NONE
  hi SpecialKey ctermfg=238 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=210 ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=216 ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=153 ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=189 ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=235 ctermbg=150 cterm=NONE
  hi StatusLineNC ctermfg=223 ctermbg=235 cterm=NONE
  hi TabLine ctermfg=223 ctermbg=238 cterm=NONE
  hi TabLineFill ctermfg=223 ctermbg=235 cterm=NONE
  hi TabLineSel ctermfg=235 ctermbg=150 cterm=NONE
  hi Title ctermfg=216 ctermbg=NONE cterm=bold
  hi VertSplit ctermfg=244 ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=95 cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=95 cterm=italic
  hi WarningMsg ctermfg=216 ctermbg=239 cterm=NONE
  hi WildMenu ctermfg=235 ctermbg=223 cterm=NONE
  hi Underlined ctermfg=153 ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi Conditional ctermfg=210 ctermbg=NONE cterm=NONE
  hi Define ctermfg=216 ctermbg=NONE cterm=NONE
  hi Number ctermfg=150 ctermbg=NONE cterm=NONE
  hi Float ctermfg=108 ctermbg=NONE cterm=NONE
  hi Character ctermfg=108 ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=230 ctermbg=NONE cterm=NONE
  hi Function ctermfg=216 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=216 ctermbg=NONE cterm=NONE
  hi Label ctermfg=153 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=216 ctermbg=NONE cterm=NONE
  hi String ctermfg=150 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=216 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=245 ctermbg=NONE cterm=italic
  hi Constant ctermfg=210 ctermbg=NONE cterm=NONE
  hi Error ctermfg=210 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=210 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=244 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=216 ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=210 ctermbg=NONE cterm=bold
  hi Special ctermfg=108 ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=65 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=222 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=153 ctermbg=NONE cterm=NONE
  hi Exception ctermfg=210 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=189 ctermbg=NONE cterm=bold
  hi Type ctermfg=222 ctermbg=NONE cterm=bold
  hi StorageClass ctermfg=216 ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=244 ctermbg=238 cterm=NONE
  hi ToolbarButton ctermfg=222 ctermbg=NONE cterm=bold
  hi Noise ctermfg=229 ctermbg=NONE cterm=NONE
  hi helpExample ctermfg=153 ctermbg=NONE cterm=NONE
  hi helpCommand ctermfg=189 ctermbg=NONE cterm=NONE
  hi makeCommands ctermfg=229 ctermbg=NONE cterm=NONE
  hi markdownCode ctermfg=150 ctermbg=NONE cterm=NONE
  hi markdownUrl ctermfg=210 ctermbg=NONE cterm=underline
  hi markdownCodeDelimiter ctermfg=150 ctermbg=NONE cterm=bold
  hi! link mkdCode markdownCode
  hi! link mkdUrl markdownUrl
  hi! link mkdCodeDelimiter markdownCodeDelimiter
  hi rstEmphasis ctermfg=NONE ctermbg=NONE cterm=italic
  hi rstStrongEmphasis ctermfg=NONE ctermbg=NONE cterm=bold
  hi cmakeArguments ctermfg=229 ctermbg=NONE cterm=NONE
  hi htmlBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlLink ctermfg=216 ctermbg=NONE cterm=bold
  hi htmlTagName ctermfg=216 ctermbg=NONE cterm=NONE
  hi htmlEndTag ctermfg=216 ctermbg=NONE cterm=NONE
  hi htmlSpecialTagName ctermfg=222 ctermbg=NONE cterm=bold
  hi htmlTag ctermfg=229 ctermbg=NONE cterm=NONE
  hi! link xmlTag htmlTag
  hi! link xmlTagName htmlTagName
  hi! link xmlEndTag htmlEndTag
  hi! link jsFunction Function
  hi! link jsExceptions Exception
  hi pythonDottedName ctermfg=210 ctermbg=NONE cterm=NONE
  hi pythonClassVar ctermfg=210 ctermbg=NONE cterm=NONE
  hi ocamlConstructor ctermfg=222 ctermbg=NONE cterm=bold
  hi ocamlKeyChar ctermfg=153 ctermbg=NONE cterm=NONE
  hi ocamlKeyword ctermfg=222 ctermbg=NONE cterm=bold
  hi ocamlFunDef ctermfg=153 ctermbg=NONE cterm=NONE
  hi goBuiltins ctermfg=210 ctermbg=NONE cterm=NONE
  hi! link goDeclaration Function
  hi rubyControl ctermfg=210 ctermbg=NONE cterm=NONE
  hi rubyCapitalizedMethod ctermfg=216 ctermbg=NONE cterm=bold
  hi rubyDocumentation ctermfg=245 ctermbg=NONE cterm=NONE
  hi rubyStringEscape ctermfg=246 ctermbg=NONE cterm=NONE
  hi rustEnumVariant ctermfg=229 ctermbg=NONE cterm=NONE
  hi rustFuncCall ctermfg=153 ctermbg=NONE cterm=NONE
  hi rustCommentLineDoc ctermfg=246 ctermbg=NONE cterm=NONE
  hi rustEscape ctermfg=246 ctermbg=NONE cterm=NONE
  hi rustEscapeUnicode ctermfg=246 ctermbg=NONE cterm=italic
  hi rustEscapeError ctermfg=246 ctermbg=NONE cterm=bold
  hi tomlTable ctermfg=153 ctermbg=NONE cterm=NONE
  hi tomlTableArray ctermfg=153 ctermbg=NONE cterm=NONE
  hi tomlKey ctermfg=222 ctermbg=NONE cterm=bold
  hi typescriptBraces ctermfg=230 ctermbg=NONE cterm=NONE
  hi! link typescriptEndColons typescriptBraces
  hi! link typescriptExceptions Exception
  hi! link typescriptFloat Float
  hi! link typescriptMessage String
  hi vimfilerColumn__SizeLine ctermfg=244 ctermbg=NONE cterm=NONE
  hi vimfilerClosedFile ctermfg=150 ctermbg=NONE cterm=NONE
  hi wastInstGeneral ctermfg=229 ctermbg=NONE cterm=NONE
  hi wastInstWithType ctermfg=229 ctermbg=NONE cterm=NONE
  hi zshDelimiter ctermfg=153 ctermbg=NONE cterm=NONE
  hi zshPrecommand ctermfg=210 ctermbg=NONE cterm=NONE
  hi ALEWarningSign ctermfg=216 ctermbg=244 cterm=NONE
  hi ALEErrorSign ctermfg=210 ctermbg=244 cterm=NONE
  hi ALEInfoSign ctermfg=153 ctermbg=244 cterm=NONE
  hi ALEError ctermfg=NONE ctermbg=95 cterm=NONE
  hi ALEWarning ctermfg=NONE ctermbg=136 cterm=NONE
  hi ALEVirtualTextError ctermfg=245 ctermbg=NONE cterm=NONE
  hi ALEVirtualTextWarning ctermfg=245 ctermbg=NONE cterm=NONE
  hi ALEVirtualTextInfo ctermfg=245 ctermbg=NONE cterm=NONE
  hi! link ALEVirtualTextStyleError ALEVirtualTextError
  hi! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
  hi CocHighlightText ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocCodeLens ctermfg=245 ctermbg=NONE cterm=NONE
  hi! link CocErrorSign ALEErrorSign
  hi! link CocWarningSign ALEWarningSign
  hi! link CocInfoSign ALEInfoSign
  hi! link CocHintSign Label
  hi! link CocErrorHighlight ALEError
  hi! link CocWarningHighlight ALEWarning
  hi! link CocInfoHighlight ALEInfo
  hi! link CocWarningVirtualText ALEVirtualTextWarning
  hi! link CocErrorVirtualText ALEVirtualTextError
  hi! link CocInfoVirtualText ALEVirtualTextInfo
  hi! link CocHintVirtualText ALEVirtualTextInfo
  hi! link CocCodeLens ALEVirtualTextInfo
  hi NERDTreeFlags ctermfg=216 ctermbg=NONE cterm=NONE
  hi NERDTreeDirSlash ctermfg=65 ctermbg=NONE cterm=NONE
  hi NERDTreeCWD ctermfg=65 ctermbg=NONE cterm=NONE
  hi NERDTreeLinkFile ctermfg=65 ctermbg=NONE cterm=NONE
  hi NERDTreeLinkTarget ctermfg=150 ctermbg=NONE cterm=NONE
  hi EasyMotionTarget ctermfg=NONE ctermbg=NONE cterm=bold
  hi EasyMotionShade ctermfg=NONE ctermbg=235 cterm=bold
  hi MatchParenCur ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur ctermfg=NONE ctermbg=NONE cterm=underline
  hi StartifyBracket ctermfg=150 ctermbg=NONE cterm=NONE
  hi StartifyHeader ctermfg=216 ctermbg=NONE cterm=bold
  hi StartifyNumber ctermfg=216 ctermbg=NONE cterm=bold
  hi StartifyPath ctermfg=150 ctermbg=NONE cterm=NONE
  hi StartifySlash ctermfg=65 ctermbg=NONE cterm=NONE
  hi! link StartifySpecial Comment
  hi! link StartifyFile Normal
  hi diffAdded ctermfg=150 ctermbg=NONE cterm=NONE
  hi diffFile ctermfg=150 ctermbg=NONE cterm=NONE
  hi diffIndexLine ctermfg=222 ctermbg=NONE cterm=NONE
  hi diffNewFile ctermfg=153 ctermbg=NONE cterm=NONE
  hi diffRemoved ctermfg=210 ctermbg=NONE cterm=NONE
  hi gitCommitOverflow ctermfg=210 ctermbg=NONE cterm=NONE
  hi gitCommitSummary ctermfg=216 ctermbg=NONE cterm=NONE
  hi gitCommitSelectedFile ctermfg=153 ctermbg=NONE cterm=NONE
  hi gitconfigSection ctermfg=NONE ctermbg=95 cterm=NONE
  if !s:italics
    hi Folded cterm=NONE
    hi VisualNOS cterm=NONE
    hi Comment cterm=NONE
    hi rstEmphasis cterm=NONE
    hi rustEscapeUnicode cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=LightYellow ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=LightYellow ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=LightYellow ctermbg=Black cterm=NONE
    hi Terminal ctermfg=LightYellow ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=DarkGrey cterm=NONE
  hi Conceal ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=Black ctermbg=LightYellow cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=Black cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi CursorLineNr ctermfg=Grey ctermbg=Grey cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=DarkGreen cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=DarkBlue cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=DarkRed cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi Directory ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=Red ctermbg=Black cterm=NONE
  hi FoldColumn ctermfg=LightYellow ctermbg=Grey cterm=NONE
  hi Folded ctermfg=LightYellow ctermbg=Grey cterm=italic
  hi IncSearch ctermfg=NONE ctermbg=DarkRed cterm=underline
  hi LineNr ctermfg=Black ctermbg=Grey cterm=NONE
  hi ModeMsg ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=Blue ctermbg=NONE cterm=NONE
  hi NonText ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=LightYellow ctermbg=Grey cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=Grey cterm=NONE
  hi PmenuSel ctermfg=LightYellow ctermbg=Grey cterm=reverse
  hi PmenuThumb ctermfg=NONE ctermbg=LightYellow cterm=NONE
  hi Question ctermfg=LightCyan ctermbg=NONE cterm=NONE
  hi Search ctermfg=NONE ctermbg=DarkRed cterm=underline
  hi SignColumn ctermfg=NONE ctermbg=Grey cterm=NONE
  hi SpecialKey ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=Red ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=LightCyan ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=LightMagenta ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=Black ctermbg=LightGreen cterm=NONE
  hi StatusLineNC ctermfg=LightYellow ctermbg=Black cterm=NONE
  hi TabLine ctermfg=LightYellow ctermbg=DarkGrey cterm=NONE
  hi TabLineFill ctermfg=LightYellow ctermbg=Black cterm=NONE
  hi TabLineSel ctermfg=Black ctermbg=LightGreen cterm=NONE
  hi Title ctermfg=Yellow ctermbg=NONE cterm=bold
  hi VertSplit ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=DarkRed cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=DarkRed cterm=italic
  hi WarningMsg ctermfg=Yellow ctermbg=Black cterm=NONE
  hi WildMenu ctermfg=Black ctermbg=LightYellow cterm=NONE
  hi Underlined ctermfg=LightCyan ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi Conditional ctermfg=Red ctermbg=NONE cterm=NONE
  hi Define ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Number ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Float ctermfg=Green ctermbg=NONE cterm=NONE
  hi Character ctermfg=Green ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=White ctermbg=NONE cterm=NONE
  hi Function ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Label ctermfg=LightCyan ctermbg=NONE cterm=NONE
  hi Operator ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi String ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Tag ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Comment ctermfg=Grey ctermbg=NONE cterm=italic
  hi Constant ctermfg=Red ctermbg=NONE cterm=NONE
  hi Error ctermfg=Red ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=Red ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=Grey ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=Red ctermbg=NONE cterm=bold
  hi Special ctermfg=Green ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Statement ctermfg=LightCyan ctermbg=NONE cterm=NONE
  hi Exception ctermfg=Red ctermbg=NONE cterm=NONE
  hi Todo ctermfg=LightMagenta ctermbg=NONE cterm=bold
  hi Type ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi StorageClass ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=Grey ctermbg=DarkGrey cterm=NONE
  hi ToolbarButton ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi Noise ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi helpExample ctermfg=LightCyan ctermbg=NONE cterm=NONE
  hi helpCommand ctermfg=LightMagenta ctermbg=NONE cterm=NONE
  hi makeCommands ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi markdownCode ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi markdownUrl ctermfg=Red ctermbg=NONE cterm=underline
  hi markdownCodeDelimiter ctermfg=LightGreen ctermbg=NONE cterm=bold
  hi! link mkdCode markdownCode
  hi! link mkdUrl markdownUrl
  hi! link mkdCodeDelimiter markdownCodeDelimiter
  hi rstEmphasis ctermfg=NONE ctermbg=NONE cterm=italic
  hi rstStrongEmphasis ctermfg=NONE ctermbg=NONE cterm=bold
  hi cmakeArguments ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi htmlBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlLink ctermfg=Yellow ctermbg=NONE cterm=bold
  hi htmlTagName ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi htmlEndTag ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi htmlSpecialTagName ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi htmlTag ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi! link xmlTag htmlTag
  hi! link xmlTagName htmlTagName
  hi! link xmlEndTag htmlEndTag
  hi! link jsFunction Function
  hi! link jsExceptions Exception
  hi pythonDottedName ctermfg=Red ctermbg=NONE cterm=NONE
  hi pythonClassVar ctermfg=Red ctermbg=NONE cterm=NONE
  hi ocamlConstructor ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi ocamlKeyChar ctermfg=LightCyan ctermbg=NONE cterm=NONE
  hi ocamlKeyword ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi ocamlFunDef ctermfg=LightCyan ctermbg=NONE cterm=NONE
  hi goBuiltins ctermfg=Red ctermbg=NONE cterm=NONE
  hi! link goDeclaration Function
  hi rubyControl ctermfg=Red ctermbg=NONE cterm=NONE
  hi rubyCapitalizedMethod ctermfg=Yellow ctermbg=NONE cterm=bold
  hi rubyDocumentation ctermfg=Grey ctermbg=NONE cterm=NONE
  hi rubyStringEscape ctermfg=Brown ctermbg=NONE cterm=NONE
  hi rustEnumVariant ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi rustFuncCall ctermfg=LightCyan ctermbg=NONE cterm=NONE
  hi rustCommentLineDoc ctermfg=Brown ctermbg=NONE cterm=NONE
  hi rustEscape ctermfg=Brown ctermbg=NONE cterm=NONE
  hi rustEscapeUnicode ctermfg=Brown ctermbg=NONE cterm=italic
  hi rustEscapeError ctermfg=Brown ctermbg=NONE cterm=bold
  hi tomlTable ctermfg=LightCyan ctermbg=NONE cterm=NONE
  hi tomlTableArray ctermfg=LightCyan ctermbg=NONE cterm=NONE
  hi tomlKey ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi typescriptBraces ctermfg=White ctermbg=NONE cterm=NONE
  hi! link typescriptEndColons typescriptBraces
  hi! link typescriptExceptions Exception
  hi! link typescriptFloat Float
  hi! link typescriptMessage String
  hi vimfilerColumn__SizeLine ctermfg=Grey ctermbg=NONE cterm=NONE
  hi vimfilerClosedFile ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi wastInstGeneral ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi wastInstWithType ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi zshDelimiter ctermfg=LightCyan ctermbg=NONE cterm=NONE
  hi zshPrecommand ctermfg=Red ctermbg=NONE cterm=NONE
  hi ALEWarningSign ctermfg=Yellow ctermbg=Grey cterm=NONE
  hi ALEErrorSign ctermfg=Red ctermbg=Grey cterm=NONE
  hi ALEInfoSign ctermfg=LightCyan ctermbg=Grey cterm=NONE
  hi ALEError ctermfg=NONE ctermbg=DarkRed cterm=NONE
  hi ALEWarning ctermfg=NONE ctermbg=DarkYellow cterm=NONE
  hi ALEVirtualTextError ctermfg=Grey ctermbg=NONE cterm=NONE
  hi ALEVirtualTextWarning ctermfg=Grey ctermbg=NONE cterm=NONE
  hi ALEVirtualTextInfo ctermfg=Grey ctermbg=NONE cterm=NONE
  hi! link ALEVirtualTextStyleError ALEVirtualTextError
  hi! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
  hi CocHighlightText ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocCodeLens ctermfg=Grey ctermbg=NONE cterm=NONE
  hi! link CocErrorSign ALEErrorSign
  hi! link CocWarningSign ALEWarningSign
  hi! link CocInfoSign ALEInfoSign
  hi! link CocHintSign Label
  hi! link CocErrorHighlight ALEError
  hi! link CocWarningHighlight ALEWarning
  hi! link CocInfoHighlight ALEInfo
  hi! link CocWarningVirtualText ALEVirtualTextWarning
  hi! link CocErrorVirtualText ALEVirtualTextError
  hi! link CocInfoVirtualText ALEVirtualTextInfo
  hi! link CocHintVirtualText ALEVirtualTextInfo
  hi! link CocCodeLens ALEVirtualTextInfo
  hi NERDTreeFlags ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi NERDTreeDirSlash ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi NERDTreeCWD ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi NERDTreeLinkFile ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi NERDTreeLinkTarget ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi EasyMotionTarget ctermfg=NONE ctermbg=NONE cterm=bold
  hi EasyMotionShade ctermfg=NONE ctermbg=Black cterm=bold
  hi MatchParenCur ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur ctermfg=NONE ctermbg=NONE cterm=underline
  hi StartifyBracket ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi StartifyHeader ctermfg=Yellow ctermbg=NONE cterm=bold
  hi StartifyNumber ctermfg=Yellow ctermbg=NONE cterm=bold
  hi StartifyPath ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi StartifySlash ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi! link StartifySpecial Comment
  hi! link StartifyFile Normal
  hi diffAdded ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi diffFile ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi diffIndexLine ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi diffNewFile ctermfg=LightCyan ctermbg=NONE cterm=NONE
  hi diffRemoved ctermfg=Red ctermbg=NONE cterm=NONE
  hi gitCommitOverflow ctermfg=Red ctermbg=NONE cterm=NONE
  hi gitCommitSummary ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi gitCommitSelectedFile ctermfg=LightCyan ctermbg=NONE cterm=NONE
  hi gitconfigSection ctermfg=NONE ctermbg=DarkRed cterm=NONE
  if !s:italics
    hi Folded cterm=NONE
    hi VisualNOS cterm=NONE
    hi Comment cterm=NONE
    hi rstEmphasis cterm=NONE
    hi rustEscapeUnicode cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" QuickFixLine      -> Search
" StatusLineTerm    -> StatusLine
" StatusLineTermNC  -> StatusLineNC
" Debug             -> Special
" Include           -> PreProc
" Macro             -> PreProc
" Repeat            -> Statement
" SpecialChar       -> Special
" Structure         -> Type
" Typedef           -> Type
" lCursor           -> Cursor
" Background: dark
" Color: white         #c5d4dd           230               White
" Color: lightyellow   #ffebc3           223               LightYellow
" Color: black         #3c4c55           239               Black
" Color: dark          #4c5866           235               Black
" Color: darkgrey      #536273           238               DarkGrey
" Color: grey          #616c72           244               Grey
" Color: greyalt       #646f7c           244               Grey
" Color: greyer        #788898           245               Grey
" Color: red           #fd8489           210               Red
" Color: darkred       #70495d           95                DarkRed
" Color: brightgreen   #a9dd9d           150               LightGreen
" Color: green         #87af87           108               Green
" Color: darkgreen     #5f8770           65                DarkGreen
" Color: lightblue     #a8d2eb           153               LightCyan
" Color: blue          #7fc1ca           110               Blue
" Color: darkblue      #5f87af           67                DarkBlue
" Color: lightmagenta  #e7d5ff           189               LightMagenta
" Color: orange        #f0aa8a           216               Yellow
" Color: darkorange    #b36200           136               DarkYellow
" Color: yellow        #f0eaaa           229               Yellow
" Color: darkyellow    #f0c38a           222               DarkYellow
" Color: lightbrown    #b2a488           247               Brown
" Color: brown         #918175           246               Brown
" Color: darkbrown     #2d2c29           237               DarkGrey
" Color: t_black       #132132           233               Black
" Color: t_red         #ff6a6f           203               Red
" Color: t_green       #a9dd9d           150               Green
" Color: t_yellow      #f0c38a           222               Yellow
" Color: t_blue        #7098e6           69                Blue
" Color: t_magenta     #605779           60                Magenta
" Color: t_cyan        #a8d2eb           153               Cyan
" Color: t_white       #fffeeb           231               White
" Color: t_black_b     #8d9eb2           103               DarkGrey
" Color: t_red_b       #fd8489           210               LightRed
" Color: t_green_b     #c9fd88           149               LightGreen
" Color: t_blue_b      #98b8e6           111               LightBlue
" Color: t_magenta_b   #e7d5ff           189               LightMagenta
" Color: t_white_b     #ffffff           231               White
" Term colors: t_black t_red t_green yellow t_blue t_magenta t_blue t_white
" Term colors: t_black_b t_red_b t_green_b yellow
" Term colors: t_blue_b t_magenta_b lightblue t_white_b
" Variant: gui
" if get(g:, '@optionprefix_transp_bg', 0) && !has('gui_running')
" Variant: 256 8
" if get(g:, '@optionprefix_transp_bg', 0)
" Variant: gui 256 8
"     Normal           lightyellow       none
"     Terminal         lightyellow       none
" else
"     Normal           lightyellow       black
"     Terminal         lightyellow       black
" endif
" ColorColumn          fg                darkgrey
" Conceal              greyer            none
" Cursor               black             lightyellow
" CursorColumn         none              dark
" CursorLine           none              dark
" CursorLineNr         greyer            grey
" DiffAdd              none              darkgreen
" DiffChange           none              darkblue
" DiffDelete           none              darkred
" DiffText             none              darkgrey
" Directory            brightgreen       none
" EndOfBuffer          darkgrey          none
" ErrorMsg             red               black
" FoldColumn           lightyellow       grey
" Folded               lightyellow       grey              italic
" IncSearch            none              darkred           underline
" LineNr               black             grey
" ModeMsg              darkyellow        none
" MoreMsg              blue              none
" NonText              greyalt           none
" Pmenu                lightyellow       grey
" PmenuSbar            none              grey
" PmenuSel             lightyellow       grey              reverse
" PmenuThumb           none              lightyellow
" Question             lightblue         none
" Search               none              darkred           underline
" SignColumn           none              grey
" SpecialKey           darkgrey          none
" SpellBad             red               none              s=red
" SpellCap             orange            none              s=orange
" SpellLocal           lightblue         none              s=blue
" SpellRare             lightmagenta     none              s=t_magenta
" StatusLine           dark              brightgreen
" StatusLineNC         lightyellow       dark
" TabLine              lightyellow       darkgrey
" TabLineFill          lightyellow       dark
" TabLineSel           dark              brightgreen
" Title                orange            none              bold
" VertSplit            grey              none
" Visual               none              darkred
" VisualNOS            none              darkred           italic
" WarningMsg           orange            black
" WildMenu             dark              lightyellow
" Underlined           lightblue         none
" MatchParen           none              none              bold
" Conditional          red               none
" Define               orange            none
" Number               brightgreen       none
" Float                green             none
" Character            green             none
" Boolean              white             none
" Function             orange            none
" Keyword              orange            none
" Label                lightblue         none
" Operator             orange            none
" String               brightgreen       none
" Tag                  orange            none
" Comment              greyer            none              italic
" Constant             red               none
" Error                red               none
" Identifier           red               none
" Ignore               greyalt           none
" PreProc              orange            none
" PreCondit            red               none              bold
" Special              green             none
" SpecialComment       darkgreen         none
" Delimiter            darkyellow        none
" Statement            lightblue         none
" Exception            red               none
" Todo                 lightmagenta      none              bold
" Type                 darkyellow        none              bold
" StorageClass         orange            none
" CursorIM             none              fg
" ToolbarLine          grey              darkgrey
" ToolbarButton        darkyellow        none              bold
" Noise                yellow            none
" helpExample          lightblue         none
" helpCommand          lightmagenta      none
" makeCommands         yellow            none
" markdownCode         brightgreen       none
" markdownUrl          red               none              underline
" markdownCodeDelimiter brightgreen      none              bold
" mkdCode           -> markdownCode
" mkdUrl            -> markdownUrl
" mkdCodeDelimiter  -> markdownCodeDelimiter
" rstEmphasis          none              none              italic
" rstStrongEmphasis    none              none              bold
" cmakeArguments       yellow            none
" htmlBold             none              none              bold
" htmlLink             orange            none              bold
" htmlTagName          orange            none
" htmlEndTag           orange            none
" htmlSpecialTagName   darkyellow        none              bold
" htmlTag              yellow            none
" xmlTag            -> htmlTag
" xmlTagName        -> htmlTagName
" xmlEndTag         -> htmlEndTag
" jsFunction        -> Function
" jsExceptions      -> Exception
" pythonDottedName     red               none
" pythonClassVar       red               none
" ocamlConstructor     darkyellow        none              bold
" ocamlKeyChar         lightblue         none
" ocamlKeyword         darkyellow        none              bold
" ocamlFunDef          lightblue         none
" goBuiltins           red               none
" goDeclaration     -> Function
" rubyControl          red               none
" rubyCapitalizedMethod orange           none              bold
" rubyDocumentation    greyer            none
" rubyStringEscape     brown             none
" rustEnumVariant      yellow            none
" rustFuncCall         lightblue         none
" rustCommentLineDoc   brown             none
" rustEscape           brown             none
" rustEscapeUnicode    brown             none              italic
" rustEscapeError      brown             none              bold
" tomlTable            lightblue         none
" tomlTableArray       lightblue         none
" tomlKey              darkyellow        none              bold
" typescriptBraces     white             none
" typescriptEndColons -> typescriptBraces
" typescriptExceptions -> Exception
" typescriptFloat   -> Float
" typescriptMessage -> String
" vimfilerColumn__SizeLine grey          none
" vimfilerClosedFile   brightgreen       none
" wastInstGeneral      yellow            none
" wastInstWithType     yellow            none
" zshDelimiter         lightblue         none
" zshPrecommand        red               none
" ALEWarningSign       orange            grey
" ALEErrorSign         red               grey
" ALEInfoSign          lightblue         grey
" ALEError             none              darkred
" ALEWarning           none              darkorange
" ALEVirtualTextError  greyer            none
" ALEVirtualTextWarning greyer           none
" ALEVirtualTextInfo   greyer            none
" ALEVirtualTextStyleError            -> ALEVirtualTextError
" ALEVirtualTextStyleWarning          -> ALEVirtualTextWarning
" CocHighlightText     none              none              bold
" CocCodeLens          greyer            none
" CocErrorSign      -> ALEErrorSign
" CocWarningSign    -> ALEWarningSign
" CocInfoSign       -> ALEInfoSign
" CocHintSign       -> Label
" CocErrorHighlight -> ALEError
" CocWarningHighlight -> ALEWarning
" CocInfoHighlight  -> ALEInfo
" CocWarningVirtualText -> ALEVirtualTextWarning
" CocErrorVirtualText -> ALEVirtualTextError
" CocInfoVirtualText -> ALEVirtualTextInfo
" CocHintVirtualText -> ALEVirtualTextInfo
" CocCodeLens       -> ALEVirtualTextInfo
" NERDTreeFlags        orange            none
" NERDTreeDirSlash     darkgreen         none
" NERDTreeCWD          darkgreen         none
" NERDTreeLinkFile     darkgreen         none
" NERDTreeLinkTarget   brightgreen       none
" EasyMotionTarget     none              none              bold
" EasyMotionShade      none              dark              bold
" MatchParenCur        none              none              bold
" MatchWord            none              none              underline
" MatchWordCur         none              none              underline
" StartifyBracket      brightgreen       none
" StartifyHeader       orange            none              bold
" StartifyNumber       orange            none              bold
" StartifyPath         brightgreen       none
" StartifySlash        darkgreen         none
" StartifySpecial   -> Comment
" StartifyFile      -> Normal
" diffAdded            brightgreen       none
" diffFile             brightgreen       none
" diffIndexLine        darkyellow        none
" diffNewFile          lightblue         none
" diffRemoved          red               none
" gitCommitOverflow    red               none
" gitCommitSummary     orange            none
" gitCommitSelectedFile lightblue        none
" gitconfigSection     none              darkred
" Variant: 2
" Color: unused #000000 0
" Normal               unused unused
" ColorColumn          unused unused reverse
" Conceal              unused unused
" Cursor               unused unused
" CursorColumn         unused unused reverse
" CursorLine           unused unused underline
" CursorLineNr         unused unused reverse,italic,bold,underline
" DiffAdd              unused unused reverse,underline
" DiffChange           unused unused reverse,underline
" DiffDelete           unused unused reverse,underline
" DiffText             unused unused bold,reverse,underline
" Directory            unused unused
" EndOfBuffer          unused unused
" ErrorMsg             unused unused bold,reverse,italic
" FoldColumn           unused unused reverse
" Folded               unused unused italic,reverse,underline
" IncSearch            unused unused reverse,bold,italic
" LineNr               unused unused reverse
" MatchParen           unused unused bold,underline
" ModeMsg              unused unused
" MoreMsg              unused unused
" NonText              unused unused
" Pmenu                unused unused reverse
" PmenuSbar            unused unused
" PmenuSel             unused unused
" PmenuThumb           unused unused
" Question             unused unused standout
" Search               unused unused underline,italic
" SignColumn           unused unused reverse
" SpecialKey           unused unused bold
" SpellBad             unused unused underline,italic
" SpellCap             unused unused underline,italic
" SpellLocal           unused unused underline,italic
" SpellRare            unused unused underline,italic
" StatusLine           unused unused reverse,bold
" StatusLineNC         unused unused reverse
" TabLine              unused unused reverse,underline,italic
" TabLineFill          unused unused reverse,underline
" TabLineSel           unused unused bold
" Title                unused unused bold
" VertSplit            unused unused reverse
" Visual               unused unused reverse
" VisualNOS            unused unused
" WarningMsg           unused unused standout
" WildMenu             unused unused bold
" Comment              unused unused italic
" Constant             unused unused bold,italic
" Error                unused unused reverse
" Identifier           unused unused italic
" Ignore               unused unused
" PreProc              unused unused italic
" Special              unused unused bold,italic
" Statement            unused unused bold
" Todo                 unused unused bold,underline
" Type                 unused unused bold
" Underlined           unused unused underline
" CursorIM             unused unused
" ToolbarLine          unused unused reverse
" ToolbarButton        unused unused bold,reverse
