" Name:         Forest Night
" Description:  🌲 Comfortable & Pleasant VIM Color Scheme
" Author:       Sainnhepark <sainnhe@gmail.com>
" Maintainer:   Sainnhepark <sainnhe@gmail.com>
" Website:      https://github.com/sainnhe/vim-color-forest-night/
" License:      MIT && Anti-996
" Last Updated: Mon 02 Sep 2019 06:28:57 PM CST

" Generated by Colortemplate v2.0.0

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'forest-night'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS')) || has('nvim')

let s:italics = get(g:, 'forest_night_use_italic', 1) && s:italics
hi! link plug2 Yellow
hi! link plugBracket Grey
hi! link plugDash Orange
hi! link plugName Green
hi! link plugH2 Orange
hi! link plugMessage Orange
hi! link plugError Red
hi! link plugNotLoaded Grey
hi! link plugRelDate Grey
hi! link plugStar Blue
hi! link plugUpdate Aqua
hi! link plugDeleted Grey
hi! link plugEdge Magenta
hi! link ALEVirtualTextStyleError ALEVirtualTextError
hi! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
hi! link ALEVirtualTextError Grey
hi! link ALEVirtualTextWarning Grey
hi! link ALEVirtualTextInfo Grey
hi! link CocErrorSign ALEErrorSign
hi! link CocWarningSign ALEWarningSign
hi! link CocInfoSign ALEInfoSign
hi! link CocErrorHighlight ALEError
hi! link CocWarningHighlight ALEWarning
hi! link CocInfoHighlight ALEInfo
hi! link CocCodeLens Grey
hi! link CocWarningVirtualText ALEVirtualTextWarning
hi! link CocErrorVirtualText ALEVirtualTextError
hi! link CocInfoVirtualText ALEVirtualTextInfo
hi! link CocHintVirtualText ALEVirtualTextInfo
hi! link NERDTreeFlags Orange
hi! link NERDTreeLinkTarget Green
hi! link NERDTreeDirSlash Aqua
hi! link NERDTreeCWD Aqua
hi! link NERDTreeLinkFile Grey
hi! link TagbarKind Orange
hi! link TagbarVisibilityPublic Blue
hi! link TagbarVisibilityPrivate Magenta
hi! link TagbarNestedKind Aqua
hi! link TagbarSignature Green
hi! link TagbarPseudoID Magenta
hi! link StartifyBracket Grey
hi! link StartifyHeader Orange
hi! link StartifySection Red
hi! link StartifyNumber Blue
hi! link StartifyPath Green
hi! link StartifySpecial Grey
hi! link StartifyFile Normal
hi! link StartifySlash Aqua
hi! link gvSha Green
hi! link gvAuthor Orange
hi! link EasyMotionTarget Search
hi! link EasyMotionShade Grey
let g:fzf_colors = {
      \ 'fg':      ['fg', 'Normal'],
      \ 'bg':      ['bg', 'Normal'],
      \ 'hl':      ['fg', 'Green'],
      \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
      \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
      \ 'hl+':     ['fg', 'Green'],
      \ 'info':    ['fg', 'Yellow'],
      \ 'prompt':  ['fg', 'Green'],
      \ 'pointer': ['fg', 'Blue'],
      \ 'marker':  ['fg', 'Magenta'],
      \ 'spinner': ['fg', 'Magenta'],
      \ 'header':  ['fg', 'Grey']
      \ }
hi! link markdownLinkText Yellow
hi! link markdownListMarker Blue
hi! link markdownOrderedListMarker Blue
hi! link markdownCodeDelimiter Aqua
hi! link markdownCode Green
hi! link markdownId Orange
hi! link markdownIdDeclaration Orange
hi! link markdownBoldDelimiter Grey
hi! link markdownItalicDelimiter Comment
hi! link markdownRule Magenta
hi! link markdownHeadingRule Magenta
hi! link markdownHeadingDelimiter Grey
hi! link mkdListItem Blue
hi! link mkdLink Yellow
hi! link mkdCodeDelimiter Aqua
hi! link mkdCode Green
hi! link mkdID Orange
hi! link mkdBold Grey
hi! link mkdItalic Comment
hi! link mkdRule Magenta
hi! link mkdHeading Grey
hi! link mkdDelimiter Grey
hi! link rstDirective Orange
hi! link rstExplicitMarkup Blue
hi! link rstDelimiter Orange
hi! link rstTableLines Grey
hi! link texDocType Red
hi! link texDocTypeArgs Aqua
hi! link texBeginEndName Magenta
hi! link texStatement Green
hi! link texTitle Aqua
hi! link texSection Orange
hi! link htmlStatement Orange
hi! link htmlTag Orange
hi! link htmlEndTag Yellow
hi! link htmlScriptTag Purple
hi! link htmlSpecialTagName Blue
hi! link xmlTag Orange
hi! link xmlTagName Orange
hi! link xmlEndTag Yellow
hi! link xmlEqual Blue
hi! link cssClassName Yellow
hi! link cssClassNameDot cssClassName
hi! link cssTagName Red
hi! link cssIdentifier Aqua
hi! link cssAttributeSelector Aqua
hi! link cssProp Aqua
hi! link cssAttr Orange
hi! link cssPseudoClass Blue
hi! link cssPseudoClassId Blue
hi! link cssImportant Red
hi! link cssUnitDecorators Blue
hi! link cssColor Orange
hi! link cssMediaType Blue
hi! link cssAttrComma Delimiter
hi! link cssBraces Delimiter
hi! link cssSelectorOp Delimiter
hi! link cssSelectorOp2 Delimiter
hi! link sassVariable Green
hi! link sassClassChar Yellow
hi! link sassMixing Blue
hi! link sassInclude Red
hi! link scssVariable Green
hi! link scssClassChar Yellow
hi! link lessVariable Green
hi! link lessMixinChar Grey
hi! link jsVariableDef Aqua
hi! link jsObjectProp Green
hi! link jsObjectKey Blue
hi! link jsParen Aqua
hi! link jsBracket Aqua
hi! link jsParenIfElse Aqua
hi! link jsParenRepeat Aqua
hi! link jsParenSwitch Aqua
hi! link jsGlobalObjects Yellow
hi! link jsFuncArgs Aqua
hi! link jsFunctionKey Green
hi! link jsThis Magenta
hi! link jsOperatorKeyword Red
hi! link jsClassDefinition Yellow
hi! link jsObjectKeyComputed Aqua
hi! link jsxTagName Orange
hi! link jsxComponentName Aqua
hi! link typescriptExceptions Exception
hi! link typescriptInterpolationDelimiter Blue
hi! link typescriptInterpolation Aqua
hi! link typescriptParens Delimiter
hi! link typescriptBraces Delimiter
hi! link typescriptEndColons Delimiter
hi! link typescriptGlobalObjects Aqua
hi! link typescriptOperator Red
hi! link dartCombinators Yellow
hi! link dartType Orange
hi! link dartTypedef Red
hi! link dartInterpolation Blue
hi! link dartBranch Orange
hi! link coffeeParen Delimiter
hi! link coffeeCurly Delimiter
hi! link coffeeBracket Delimiter
hi! link coffeeInterpDelim Blue
hi! link coffeeInterp Aqua
hi! link coffeeConstant Yellow
hi! link purescriptModuleName Aqua
hi! link purescriptOperatorTypeSig Magenta
hi! link javaClassDecl Red
hi! link javaAnnotation Magenta
hi! link javaTypedef Aqua
hi! link ktComplexInterpolationBrace Blue
hi! link ktComplexInterpolation Aqua
hi! link ktConstant Yellow
hi! link ktStatement Red
hi! link ktKeyword Aqua
hi! link ktArrow Magenta
hi! link pythonBuiltinType Yellow
hi! link goVar Orange
hi! link goImport Red
hi! link goPackage Red
hi! link goBuiltins Green
hi! link goPredefinedIdentifiers Yellow
hi! link rustSuper Magenta
hi! link rustEnumVariant Yellow
hi! link rustSelf Aqua
hi! link rustModPath Aqua
hi! link rustModPathSep Grey
hi! link rustAttribute Magenta
hi! link rustMacroVariable Aqua
hi! link rustMacroRepeatDelimiters Magenta
hi! link rustPubScopeCrate Magenta
hi! link rustStructure Orange

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#7f8f9f', '#ff9094', '#bcd093', '#f0b295',
        \ '#bdd0e5', '#e5c6f0', '#a2cea5', '#f2ddb5', '#7f8f9f', '#ff9094',
        \ '#bcd093', '#eccc8f', '#bdd0e5', '#e5c6f0', '#a2cea5', '#f2ddb5']
  if has('nvim')
    let g:terminal_color_0 = '#7f8f9f'
    let g:terminal_color_1 = '#ff9094'
    let g:terminal_color_2 = '#bcd093'
    let g:terminal_color_3 = '#f0b295'
    let g:terminal_color_4 = '#bdd0e5'
    let g:terminal_color_5 = '#e5c6f0'
    let g:terminal_color_6 = '#a2cea5'
    let g:terminal_color_7 = '#f2ddb5'
    let g:terminal_color_8 = '#7f8f9f'
    let g:terminal_color_9 = '#ff9094'
    let g:terminal_color_10 = '#bcd093'
    let g:terminal_color_11 = '#eccc8f'
    let g:terminal_color_12 = '#bdd0e5'
    let g:terminal_color_13 = '#e5c6f0'
    let g:terminal_color_14 = '#a2cea5'
    let g:terminal_color_15 = '#f2ddb5'
  endif
  hi White guifg=#f2ddb5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Grey guifg=#7f8f9f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Red guifg=#ff9094 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Orange guifg=#f0b295 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Yellow guifg=#eccc8f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Green guifg=#bcd093 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Aqua guifg=#a2cea5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Blue guifg=#bdd0e5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Magenta guifg=#e5c6f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  if get(g:, 'forest_night_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#f2ddb5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#f2ddb5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi DiffText guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
    hi EndOfBuffer guifg=#3c4c55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#f2ddb5 guibg=#3c4c55 guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#f2ddb5 guibg=#3c4c55 guisp=NONE gui=NONE cterm=NONE
    hi DiffText guifg=NONE guibg=#3c4c55 guisp=NONE gui=reverse cterm=reverse
    hi EndOfBuffer guifg=#3c4c55 guibg=#3c4c55 guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=NONE guibg=#45565e guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=#7f8f9f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi lCursor guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn guifg=NONE guibg=#45565e guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#45565e guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#7f8f9f guibg=#45565e guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#616c72 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=NONE guibg=#45565e guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=NONE guibg=#54695f guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#43596f guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=NONE guibg=#70495d guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#bcd093 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#ff9094 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi WarningMsg guifg=#eccc8f guibg=NONE guisp=NONE gui=bold cterm=bold
  hi ModeMsg guifg=#3c4c55 guibg=#bcd093 guisp=NONE gui=bold cterm=bold
  hi MoreMsg guifg=#eccc8f guibg=NONE guisp=NONE gui=bold cterm=bold
  hi FoldColumn guifg=#f2ddb5 guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#f2ddb5 guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=NONE guibg=#54695f guisp=NONE gui=bold cterm=bold
  hi Search guifg=NONE guibg=#70495d guisp=NONE gui=underline cterm=underline
  hi MatchParen guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText guifg=#7f8f9f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#f2ddb5 guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#3c4c55 guibg=#f2ddb5 guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=NONE guibg=#f2ddb5 guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#f0b295 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi SpellBad guifg=#ff9094 guibg=NONE guisp=#ff9094 gui=italic,undercurl cterm=italic,undercurl
  hi SpellCap guifg=#bdd0e5 guibg=NONE guisp=#bdd0e5 gui=italic,undercurl cterm=italic,undercurl
  hi SpellLocal guifg=#a2cea5 guibg=NONE guisp=#a2cea5 gui=italic,undercurl cterm=italic,undercurl
  hi SpellRare guifg=#e5c6f0 guibg=NONE guisp=#e5c6f0 gui=italic,undercurl cterm=italic,undercurl
  hi StatusLine guifg=#f2ddb5 guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#f2ddb5 guibg=#45565e guisp=NONE gui=NONE cterm=NONE
  hi StatusLineTerm guifg=#f2ddb5 guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineTermNC guifg=#f2ddb5 guibg=#45565e guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#f2ddb5 guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#f2ddb5 guibg=#45565e guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#3c4c55 guibg=#bcd093 guisp=NONE gui=bold cterm=bold
  hi VertSplit guifg=#576a72 guibg=#3c4c55 guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#70495d guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=#70495d guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#3c4c55 guibg=#f2ddb5 guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#e5c6f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CursorIM guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi ToolbarLine guifg=NONE guibg=#576a72 guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#f2ddb5 guibg=#576a72 guisp=NONE gui=bold cterm=bold
  hi QuickFixLine guifg=#eccc8f guibg=#3c4c55 guisp=NONE gui=reverse cterm=reverse
  hi Debug guifg=#f0b295 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Exception guifg=#ff9094 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#ff9094 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Conditional guifg=#ff9094 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Repeat guifg=#ff9094 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#ff9094 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Include guifg=#ff9094 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Define guifg=#ff9094 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreCondit guifg=#ff9094 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#f0b295 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Statement guifg=#f0b295 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#f0b295 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Structure guifg=#f0b295 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Tag guifg=#f0b295 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Label guifg=#f0b295 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#eccc8f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Typedef guifg=#eccc8f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Function guifg=#bcd093 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#bcd093 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Character guifg=#bcd093 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Constant guifg=#a2cea5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#a2cea5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Macro guifg=#a2cea5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#bdd0e5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#bdd0e5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialChar guifg=#bdd0e5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Boolean guifg=#e5c6f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Number guifg=#e5c6f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Float guifg=#e5c6f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#bdd0e5 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi SpecialKey guifg=#bdd0e5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#7f8f9f guibg=NONE guisp=NONE gui=italic cterm=italic
  hi SpecialComment guifg=#7f8f9f guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Delimiter guifg=#f2ddb5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#f2ddb5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=NONE guibg=#70495d guisp=NONE gui=NONE cterm=NONE
  hi plug1 guifg=#ff9094 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi plugNumber guifg=#ff9094 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi ALEWarningSign guifg=#eccc8f guibg=#45565e guisp=NONE gui=NONE cterm=NONE
  hi ALEErrorSign guifg=#ff9094 guibg=#45565e guisp=NONE gui=NONE cterm=NONE
  hi ALEInfoSign guifg=#bdd0e5 guibg=#45565e guisp=NONE gui=NONE cterm=NONE
  hi ALEError guifg=#ff9094 guibg=NONE guisp=NONE gui=bold,italic cterm=bold,italic
  hi ALEWarning guifg=#eccc8f guibg=NONE guisp=NONE gui=bold,italic cterm=bold,italic
  hi CocHighlightText guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocHintSign guifg=#e5c6f0 guibg=#45565e guisp=NONE gui=NONE cterm=NONE
  hi MatchParenCur guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi Sneak guifg=NONE guibg=#54695f guisp=NONE gui=bold cterm=bold
  hi GitGutterAdd guifg=#bcd093 guibg=#45565e guisp=NONE gui=NONE cterm=NONE
  hi GitGutterChange guifg=#bdd0e5 guibg=#45565e guisp=NONE gui=NONE cterm=NONE
  hi GitGutterDelete guifg=#ff9094 guibg=#45565e guisp=NONE gui=NONE cterm=NONE
  hi GitGutterChangeDelete guifg=#e5c6f0 guibg=#45565e guisp=NONE gui=NONE cterm=NONE
  hi SignifySignAdd guifg=#bcd093 guibg=#45565e guisp=NONE gui=NONE cterm=NONE
  hi SignifySignChange guifg=#bdd0e5 guibg=#45565e guisp=NONE gui=NONE cterm=NONE
  hi SignifySignDelete guifg=#ff9094 guibg=#45565e guisp=NONE gui=NONE cterm=NONE
  hi multiple_cursors_cursor guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi multiple_cursors_visual guifg=NONE guibg=#54695f guisp=NONE gui=NONE cterm=NONE
  hi Lf_hl_match guifg=#bcd093 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Lf_hl_match0 guifg=#bcd093 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Lf_hl_match1 guifg=#eccc8f guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Lf_hl_match2 guifg=#f0b295 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Lf_hl_match3 guifg=#bdd0e5 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Lf_hl_match4 guifg=#e5c6f0 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Lf_hl_matchRefine guifg=#ff9094 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi markdownH1 guifg=#ff9094 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi markdownH2 guifg=#f0b295 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi markdownH3 guifg=#eccc8f guibg=NONE guisp=NONE gui=bold cterm=bold
  hi markdownH4 guifg=#a2cea5 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi markdownH5 guifg=#bdd0e5 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi markdownH6 guifg=#e5c6f0 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi markdownUrl guifg=#bcd093 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi markdownBold guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalic guifg=NONE guibg=NONE guisp=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi markdownItalicDelimiter guifg=#7f8f9f guibg=NONE guisp=NONE gui=italic cterm=italic
  hi mkdInlineURL guifg=#eccc8f guibg=NONE guisp=NONE gui=underline cterm=underline
  hi mkdURL guifg=#bcd093 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi mkdItalic guifg=#7f8f9f guibg=NONE guisp=NONE gui=italic cterm=italic
  hi rstStandaloneHyperlink guifg=#bcd093 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi rstSections guifg=#ff9094 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi rstHyperlinkTarget guifg=#bcd093 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi rstSubstitutionReference guifg=#e5c6f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi htmlH1 guifg=#ff9094 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi htmlH2 guifg=#f0b295 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi htmlH3 guifg=#eccc8f guibg=NONE guisp=NONE gui=bold cterm=bold
  hi htmlH4 guifg=#a2cea5 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi htmlH5 guifg=#bdd0e5 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi htmlH6 guifg=#e5c6f0 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi htmlLink guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlBold guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlBoldUnderline guifg=NONE guibg=NONE guisp=NONE gui=bold,underline ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi htmlBoldItalic guifg=NONE guibg=NONE guisp=NONE gui=bold,italic ctermfg=NONE ctermbg=NONE cterm=bold,italic
  hi htmlBoldUnderlineItalic guifg=NONE guibg=NONE guisp=NONE gui=bold,italic,underline ctermfg=NONE ctermbg=NONE cterm=bold,italic,underline
  hi htmlUnderline guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlUnderlineItalic guifg=NONE guibg=NONE guisp=NONE gui=italic,underline ctermfg=NONE ctermbg=NONE cterm=italic,underline
  hi htmlItalic guifg=NONE guibg=NONE guisp=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  if !s:italics
    hi SpellBad gui=undercurl cterm=undercurl
    hi SpellCap gui=undercurl cterm=undercurl
    hi SpellLocal gui=undercurl cterm=undercurl
    hi SpellRare gui=undercurl cterm=undercurl
    hi Comment gui=NONE cterm=NONE
    hi SpecialComment gui=NONE cterm=NONE
    hi ALEError gui=bold cterm=bold
    hi ALEWarning gui=bold cterm=bold
    hi markdownItalic gui=NONE cterm=NONE
    hi markdownItalicDelimiter gui=NONE cterm=NONE
    hi mkdItalic gui=NONE cterm=NONE
    hi htmlBoldItalic gui=bold cterm=bold
    hi htmlBoldUnderlineItalic gui=bold,underline cterm=bold,underline
    hi htmlUnderlineItalic gui=underline cterm=underline
    hi htmlItalic gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  hi White ctermfg=223 ctermbg=NONE cterm=NONE
  hi Grey ctermfg=245 ctermbg=NONE cterm=NONE
  hi Red ctermfg=210 ctermbg=NONE cterm=NONE
  hi Orange ctermfg=216 ctermbg=NONE cterm=NONE
  hi Yellow ctermfg=222 ctermbg=NONE cterm=NONE
  hi Green ctermfg=150 ctermbg=NONE cterm=NONE
  hi Aqua ctermfg=151 ctermbg=NONE cterm=NONE
  hi Blue ctermfg=153 ctermbg=NONE cterm=NONE
  hi Magenta ctermfg=225 ctermbg=NONE cterm=NONE
  if get(g:, 'forest_night_transp_bg', 0)
    hi Normal ctermfg=223 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=223 ctermbg=NONE cterm=NONE
    hi DiffText ctermfg=NONE ctermbg=NONE cterm=reverse
    hi EndOfBuffer ctermfg=239 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=223 ctermbg=239 cterm=NONE
    if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
      set background=dark
    endif
    hi Terminal ctermfg=223 ctermbg=239 cterm=NONE
    hi DiffText ctermfg=NONE ctermbg=239 cterm=reverse
    hi EndOfBuffer ctermfg=239 ctermbg=239 cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=240 cterm=NONE
  hi Conceal ctermfg=245 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi lCursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=240 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=240 cterm=NONE
  hi CursorLineNr ctermfg=245 ctermbg=240 cterm=NONE
  hi LineNr ctermfg=242 ctermbg=NONE cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=240 cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=241 cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=24 cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=96 cterm=NONE
  hi Directory ctermfg=150 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=210 ctermbg=NONE cterm=bold
  hi WarningMsg ctermfg=222 ctermbg=NONE cterm=bold
  hi ModeMsg ctermfg=239 ctermbg=150 cterm=bold
  hi MoreMsg ctermfg=222 ctermbg=NONE cterm=bold
  hi FoldColumn ctermfg=223 ctermbg=242 cterm=NONE
  hi Folded ctermfg=223 ctermbg=242 cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=241 cterm=bold
  hi Search ctermfg=NONE ctermbg=96 cterm=underline
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText ctermfg=245 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=223 ctermbg=242 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=242 cterm=NONE
  hi PmenuSel ctermfg=239 ctermbg=223 cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=223 cterm=NONE
  hi Question ctermfg=216 ctermbg=NONE cterm=bold
  hi SpellBad ctermfg=210 ctermbg=NONE cterm=italic,underline
  hi SpellCap ctermfg=153 ctermbg=NONE cterm=italic,underline
  hi SpellLocal ctermfg=151 ctermbg=NONE cterm=italic,underline
  hi SpellRare ctermfg=225 ctermbg=NONE cterm=italic,underline
  hi StatusLine ctermfg=223 ctermbg=242 cterm=NONE
  hi StatusLineNC ctermfg=223 ctermbg=240 cterm=NONE
  hi StatusLineTerm ctermfg=223 ctermbg=242 cterm=NONE
  hi StatusLineTermNC ctermfg=223 ctermbg=240 cterm=NONE
  hi TabLine ctermfg=223 ctermbg=242 cterm=NONE
  hi TabLineFill ctermfg=223 ctermbg=240 cterm=NONE
  hi TabLineSel ctermfg=239 ctermbg=150 cterm=bold
  hi VertSplit ctermfg=241 ctermbg=239 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=96 cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=96 cterm=NONE
  hi WildMenu ctermfg=239 ctermbg=223 cterm=NONE
  hi Todo ctermfg=225 ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=NONE cterm=reverse
  hi ToolbarLine ctermfg=NONE ctermbg=241 cterm=NONE
  hi ToolbarButton ctermfg=223 ctermbg=241 cterm=bold
  hi QuickFixLine ctermfg=222 ctermbg=239 cterm=reverse
  hi Debug ctermfg=216 ctermbg=NONE cterm=NONE
  hi Exception ctermfg=210 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=210 ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=210 ctermbg=NONE cterm=NONE
  hi Repeat ctermfg=210 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=210 ctermbg=NONE cterm=NONE
  hi Include ctermfg=210 ctermbg=NONE cterm=NONE
  hi Define ctermfg=210 ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=210 ctermbg=NONE cterm=NONE
  hi Title ctermfg=216 ctermbg=NONE cterm=bold
  hi Statement ctermfg=216 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=216 ctermbg=NONE cterm=NONE
  hi Structure ctermfg=216 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=216 ctermbg=NONE cterm=NONE
  hi Label ctermfg=216 ctermbg=NONE cterm=NONE
  hi Type ctermfg=222 ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=222 ctermbg=NONE cterm=NONE
  hi Function ctermfg=150 ctermbg=NONE cterm=NONE
  hi String ctermfg=150 ctermbg=NONE cterm=NONE
  hi Character ctermfg=150 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=151 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=151 ctermbg=NONE cterm=NONE
  hi Macro ctermfg=151 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=153 ctermbg=NONE cterm=NONE
  hi Special ctermfg=153 ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=153 ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=225 ctermbg=NONE cterm=NONE
  hi Number ctermfg=225 ctermbg=NONE cterm=NONE
  hi Float ctermfg=225 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=153 ctermbg=NONE cterm=underline
  hi SpecialKey ctermfg=153 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=245 ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=245 ctermbg=NONE cterm=italic
  hi Delimiter ctermfg=223 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=223 ctermbg=NONE cterm=NONE
  hi Error ctermfg=NONE ctermbg=96 cterm=NONE
  hi plug1 ctermfg=210 ctermbg=NONE cterm=bold
  hi plugNumber ctermfg=210 ctermbg=NONE cterm=bold
  hi ALEWarningSign ctermfg=222 ctermbg=240 cterm=NONE
  hi ALEErrorSign ctermfg=210 ctermbg=240 cterm=NONE
  hi ALEInfoSign ctermfg=153 ctermbg=240 cterm=NONE
  hi ALEError ctermfg=210 ctermbg=NONE cterm=bold,italic
  hi ALEWarning ctermfg=222 ctermbg=NONE cterm=bold,italic
  hi CocHighlightText ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocHintSign ctermfg=225 ctermbg=240 cterm=NONE
  hi MatchParenCur ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur ctermfg=NONE ctermbg=NONE cterm=underline
  hi Sneak ctermfg=NONE ctermbg=241 cterm=bold
  hi GitGutterAdd ctermfg=150 ctermbg=240 cterm=NONE
  hi GitGutterChange ctermfg=153 ctermbg=240 cterm=NONE
  hi GitGutterDelete ctermfg=210 ctermbg=240 cterm=NONE
  hi GitGutterChangeDelete ctermfg=225 ctermbg=240 cterm=NONE
  hi SignifySignAdd ctermfg=150 ctermbg=240 cterm=NONE
  hi SignifySignChange ctermfg=153 ctermbg=240 cterm=NONE
  hi SignifySignDelete ctermfg=210 ctermbg=240 cterm=NONE
  hi multiple_cursors_cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi multiple_cursors_visual ctermfg=NONE ctermbg=241 cterm=NONE
  hi Lf_hl_match ctermfg=150 ctermbg=NONE cterm=bold
  hi Lf_hl_match0 ctermfg=150 ctermbg=NONE cterm=bold
  hi Lf_hl_match1 ctermfg=222 ctermbg=NONE cterm=bold
  hi Lf_hl_match2 ctermfg=216 ctermbg=NONE cterm=bold
  hi Lf_hl_match3 ctermfg=153 ctermbg=NONE cterm=bold
  hi Lf_hl_match4 ctermfg=225 ctermbg=NONE cterm=bold
  hi Lf_hl_matchRefine ctermfg=210 ctermbg=NONE cterm=bold
  hi markdownH1 ctermfg=210 ctermbg=NONE cterm=bold
  hi markdownH2 ctermfg=216 ctermbg=NONE cterm=bold
  hi markdownH3 ctermfg=222 ctermbg=NONE cterm=bold
  hi markdownH4 ctermfg=151 ctermbg=NONE cterm=bold
  hi markdownH5 ctermfg=153 ctermbg=NONE cterm=bold
  hi markdownH6 ctermfg=225 ctermbg=NONE cterm=bold
  hi markdownUrl ctermfg=150 ctermbg=NONE cterm=underline
  hi markdownBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi markdownItalicDelimiter ctermfg=245 ctermbg=NONE cterm=italic
  hi mkdInlineURL ctermfg=222 ctermbg=NONE cterm=underline
  hi mkdURL ctermfg=150 ctermbg=NONE cterm=underline
  hi mkdItalic ctermfg=245 ctermbg=NONE cterm=italic
  hi rstStandaloneHyperlink ctermfg=150 ctermbg=NONE cterm=underline
  hi rstSections ctermfg=210 ctermbg=NONE cterm=bold
  hi rstHyperlinkTarget ctermfg=150 ctermbg=NONE cterm=underline
  hi rstSubstitutionReference ctermfg=225 ctermbg=NONE cterm=NONE
  hi htmlH1 ctermfg=210 ctermbg=NONE cterm=bold
  hi htmlH2 ctermfg=216 ctermbg=NONE cterm=bold
  hi htmlH3 ctermfg=222 ctermbg=NONE cterm=bold
  hi htmlH4 ctermfg=151 ctermbg=NONE cterm=bold
  hi htmlH5 ctermfg=153 ctermbg=NONE cterm=bold
  hi htmlH6 ctermfg=225 ctermbg=NONE cterm=bold
  hi htmlLink ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlBoldUnderline ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi htmlBoldItalic ctermfg=NONE ctermbg=NONE cterm=bold,italic
  hi htmlBoldUnderlineItalic ctermfg=NONE ctermbg=NONE cterm=bold,italic,underline
  hi htmlUnderline ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlUnderlineItalic ctermfg=NONE ctermbg=NONE cterm=italic,underline
  hi htmlItalic ctermfg=NONE ctermbg=NONE cterm=italic
  if !s:italics
    hi SpellBad cterm=underline
    hi SpellCap cterm=underline
    hi SpellLocal cterm=underline
    hi SpellRare cterm=underline
    hi Comment cterm=NONE
    hi SpecialComment cterm=NONE
    hi ALEError cterm=bold
    hi ALEWarning cterm=bold
    hi markdownItalic cterm=NONE
    hi markdownItalicDelimiter cterm=NONE
    hi mkdItalic cterm=NONE
    hi htmlBoldItalic cterm=bold
    hi htmlBoldUnderlineItalic cterm=bold,underline
    hi htmlUnderlineItalic cterm=underline
    hi htmlItalic cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'forest_night_transp_bg', 0)
    hi Normal ctermfg=White ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
    hi DiffText ctermfg=NONE ctermbg=NONE cterm=reverse
    hi EndOfBuffer ctermfg=Black ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=White ctermbg=Black cterm=NONE
    hi Terminal ctermfg=White ctermbg=Black cterm=NONE
    hi DiffText ctermfg=NONE ctermbg=Black cterm=reverse
    hi EndOfBuffer ctermfg=Black ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=Black cterm=NONE
  hi Conceal ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi lCursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=Black cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi CursorLineNr ctermfg=Grey ctermbg=Black cterm=NONE
  hi LineNr ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=Black cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=DarkGreen cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=DarkBlue cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=DarkRed cterm=NONE
  hi Directory ctermfg=Green ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=Red ctermbg=NONE cterm=bold
  hi WarningMsg ctermfg=Yellow ctermbg=NONE cterm=bold
  hi ModeMsg ctermfg=Black ctermbg=Green cterm=bold
  hi MoreMsg ctermfg=Yellow ctermbg=NONE cterm=bold
  hi FoldColumn ctermfg=White ctermbg=DarkGrey cterm=NONE
  hi Folded ctermfg=White ctermbg=DarkGrey cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=DarkGreen cterm=bold
  hi Search ctermfg=NONE ctermbg=DarkRed cterm=underline
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=White ctermbg=DarkGrey cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi PmenuSel ctermfg=Black ctermbg=White cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=White cterm=NONE
  hi Question ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi SpellBad ctermfg=Red ctermbg=NONE cterm=italic,underline
  hi SpellCap ctermfg=Blue ctermbg=NONE cterm=italic,underline
  hi SpellLocal ctermfg=DarkGreen ctermbg=NONE cterm=italic,underline
  hi SpellRare ctermfg=Magenta ctermbg=NONE cterm=italic,underline
  hi StatusLine ctermfg=White ctermbg=DarkGrey cterm=NONE
  hi StatusLineNC ctermfg=White ctermbg=Black cterm=NONE
  hi StatusLineTerm ctermfg=White ctermbg=DarkGrey cterm=NONE
  hi StatusLineTermNC ctermfg=White ctermbg=Black cterm=NONE
  hi TabLine ctermfg=White ctermbg=DarkGrey cterm=NONE
  hi TabLineFill ctermfg=White ctermbg=Black cterm=NONE
  hi TabLineSel ctermfg=Black ctermbg=Green cterm=bold
  hi VertSplit ctermfg=Black ctermbg=Black cterm=NONE
  hi Visual ctermfg=NONE ctermbg=DarkRed cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=DarkRed cterm=NONE
  hi WildMenu ctermfg=Black ctermbg=White cterm=NONE
  hi Todo ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=NONE cterm=reverse
  hi ToolbarLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi ToolbarButton ctermfg=White ctermbg=Black cterm=bold
  hi QuickFixLine ctermfg=Yellow ctermbg=Black cterm=reverse
  hi Debug ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Exception ctermfg=Red ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=Red ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=Red ctermbg=NONE cterm=NONE
  hi Repeat ctermfg=Red ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=Red ctermbg=NONE cterm=NONE
  hi Include ctermfg=Red ctermbg=NONE cterm=NONE
  hi Define ctermfg=Red ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=Red ctermbg=NONE cterm=NONE
  hi Title ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi Statement ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Structure ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Tag ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Label ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Type ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Function ctermfg=Green ctermbg=NONE cterm=NONE
  hi String ctermfg=Green ctermbg=NONE cterm=NONE
  hi Character ctermfg=Green ctermbg=NONE cterm=NONE
  hi Constant ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Macro ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Operator ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Special ctermfg=Blue ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Number ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Float ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=Blue ctermbg=NONE cterm=underline
  hi SpecialKey ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Comment ctermfg=Grey ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=Grey ctermbg=NONE cterm=italic
  hi Delimiter ctermfg=White ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=White ctermbg=NONE cterm=NONE
  hi Error ctermfg=NONE ctermbg=DarkRed cterm=NONE
  hi plug1 ctermfg=Red ctermbg=NONE cterm=bold
  hi plugNumber ctermfg=Red ctermbg=NONE cterm=bold
  hi ALEWarningSign ctermfg=Yellow ctermbg=Black cterm=NONE
  hi ALEErrorSign ctermfg=Red ctermbg=Black cterm=NONE
  hi ALEInfoSign ctermfg=Blue ctermbg=Black cterm=NONE
  hi ALEError ctermfg=Red ctermbg=NONE cterm=bold,italic
  hi ALEWarning ctermfg=Yellow ctermbg=NONE cterm=bold,italic
  hi CocHighlightText ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocHintSign ctermfg=Magenta ctermbg=Black cterm=NONE
  hi MatchParenCur ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur ctermfg=NONE ctermbg=NONE cterm=underline
  hi Sneak ctermfg=NONE ctermbg=DarkGreen cterm=bold
  hi GitGutterAdd ctermfg=Green ctermbg=Black cterm=NONE
  hi GitGutterChange ctermfg=Blue ctermbg=Black cterm=NONE
  hi GitGutterDelete ctermfg=Red ctermbg=Black cterm=NONE
  hi GitGutterChangeDelete ctermfg=Magenta ctermbg=Black cterm=NONE
  hi SignifySignAdd ctermfg=Green ctermbg=Black cterm=NONE
  hi SignifySignChange ctermfg=Blue ctermbg=Black cterm=NONE
  hi SignifySignDelete ctermfg=Red ctermbg=Black cterm=NONE
  hi multiple_cursors_cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi multiple_cursors_visual ctermfg=NONE ctermbg=DarkGreen cterm=NONE
  hi Lf_hl_match ctermfg=Green ctermbg=NONE cterm=bold
  hi Lf_hl_match0 ctermfg=Green ctermbg=NONE cterm=bold
  hi Lf_hl_match1 ctermfg=Yellow ctermbg=NONE cterm=bold
  hi Lf_hl_match2 ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi Lf_hl_match3 ctermfg=Blue ctermbg=NONE cterm=bold
  hi Lf_hl_match4 ctermfg=Magenta ctermbg=NONE cterm=bold
  hi Lf_hl_matchRefine ctermfg=Red ctermbg=NONE cterm=bold
  hi markdownH1 ctermfg=Red ctermbg=NONE cterm=bold
  hi markdownH2 ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi markdownH3 ctermfg=Yellow ctermbg=NONE cterm=bold
  hi markdownH4 ctermfg=DarkGreen ctermbg=NONE cterm=bold
  hi markdownH5 ctermfg=Blue ctermbg=NONE cterm=bold
  hi markdownH6 ctermfg=Magenta ctermbg=NONE cterm=bold
  hi markdownUrl ctermfg=Green ctermbg=NONE cterm=underline
  hi markdownBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi markdownItalicDelimiter ctermfg=Grey ctermbg=NONE cterm=italic
  hi mkdInlineURL ctermfg=Yellow ctermbg=NONE cterm=underline
  hi mkdURL ctermfg=Green ctermbg=NONE cterm=underline
  hi mkdItalic ctermfg=Grey ctermbg=NONE cterm=italic
  hi rstStandaloneHyperlink ctermfg=Green ctermbg=NONE cterm=underline
  hi rstSections ctermfg=Red ctermbg=NONE cterm=bold
  hi rstHyperlinkTarget ctermfg=Green ctermbg=NONE cterm=underline
  hi rstSubstitutionReference ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi htmlH1 ctermfg=Red ctermbg=NONE cterm=bold
  hi htmlH2 ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi htmlH3 ctermfg=Yellow ctermbg=NONE cterm=bold
  hi htmlH4 ctermfg=DarkGreen ctermbg=NONE cterm=bold
  hi htmlH5 ctermfg=Blue ctermbg=NONE cterm=bold
  hi htmlH6 ctermfg=Magenta ctermbg=NONE cterm=bold
  hi htmlLink ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlBoldUnderline ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi htmlBoldItalic ctermfg=NONE ctermbg=NONE cterm=bold,italic
  hi htmlBoldUnderlineItalic ctermfg=NONE ctermbg=NONE cterm=bold,italic,underline
  hi htmlUnderline ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlUnderlineItalic ctermfg=NONE ctermbg=NONE cterm=italic,underline
  hi htmlItalic ctermfg=NONE ctermbg=NONE cterm=italic
  if !s:italics
    hi SpellBad cterm=underline
    hi SpellCap cterm=underline
    hi SpellLocal cterm=underline
    hi SpellRare cterm=underline
    hi Comment cterm=NONE
    hi SpecialComment cterm=NONE
    hi ALEError cterm=bold
    hi ALEWarning cterm=bold
    hi markdownItalic cterm=NONE
    hi markdownItalicDelimiter cterm=NONE
    hi mkdItalic cterm=NONE
    hi htmlBoldItalic cterm=bold
    hi htmlBoldUnderlineItalic cterm=bold,underline
    hi htmlUnderlineItalic cterm=underline
    hi htmlItalic cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background:  dark
" Color: white         #f2ddb5           ~                 White
" Color: dark0         #3c4c55           ~                 Black
" Color: dark1         #45565e           ~                 Black
" Color: dark2         #4f6269           ~                 Black
" Color: dark3         #576a72           ~                 Black
" Color: dark4         #60737a           ~                 Black
" Color: dark5         #677a81           ~                 Black
" Color: darkgrey      #616c72           ~                 DarkGrey
" Color: grey          #7f8f9f           ~                 Grey
" Color: red           #ff9094           ~                 Red
" Color: orange        #f0b295           ~                 DarkYellow
" Color: yellow        #eccc8f           ~                 Yellow
" Color: green         #bcd093           ~                 Green
" Color: aqua          #a2cea5           ~                 DarkGreen
" Color: blue          #bdd0e5           ~                 Blue
" Color: magenta       #e5c6f0           ~                 Magenta
" Color: darkred       #70495d           ~                 DarkRed
" Color: darkgreen     #54695f           ~                 DarkGreen
" Color: darkblue      #43596f           ~                 DarkBlue
" Term colors: grey red green orange blue magenta aqua white
" Term colors: grey red green yellow blue magenta aqua white
" vim: et ts=2 sw=2
