" Name:         Forest Night
" Description:  🌲 Comfortable & Pleasant VIM Color Scheme
" Author:       Sainnhepark <sainnhe@gmail.com>
" Maintainer:   Sainnhepark <sainnhe@gmail.com>
" Website:      https://github.com/sainnhe/vim-color-forest-night/
" License:      MIT && Anti-996
" Last Updated: Fri 05 Jul 2019 06:14:50 PM CST

" Generated by Colortemplate v2.0.0b3

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'forest-night'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS'))

hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Debug Special
hi! link Include PreProc
hi! link Macro PreProc
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link Structure Type
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#7f8f9f', '#fd8489', '#a9dd9d', '#f0aa8a',
        \ '#bdd0e5', '#daccf0', '#a9dd9d', '#ffebc3', '#7f8f9f', '#fd8489',
        \ '#a9dd9d', '#eed094', '#bdd0e5', '#daccf0', '#a9dd9d', '#ffebc3']
  if get(g:, 'dark_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#ffebc3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#ffebc3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#ffebc3 guibg=#3c4c55 guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#ffebc3 guibg=#3c4c55 guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=fg guibg=#536273 guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=#7f8f9f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=#ffebc3 guibg=#4c5866 guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#4c5866 guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#4c5866 guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#7f8f9f guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#3c4c55 guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=NONE guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=NONE guibg=#54695f guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#63431e guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=NONE guibg=#70495d guisp=NONE gui=NONE cterm=NONE
  hi DiffText guifg=NONE guibg=#43596f guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#536273 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#fd8489 guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#f0aa8a guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#3c4c55 guibg=#a9dd9d guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#ffebc3 guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#ffebc3 guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#ffebc3 guibg=#616c72 guisp=NONE gui=italic cterm=italic
  hi IncSearch guifg=NONE guibg=#70495d guisp=NONE gui=underline cterm=underline
  hi Search guifg=NONE guibg=#70495d guisp=NONE gui=underline cterm=underline
  hi NonText guifg=#7f8f9f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#ffebc3 guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#ffebc3 guibg=#616c72 guisp=NONE gui=reverse cterm=reverse
  hi PmenuThumb guifg=NONE guibg=#ffebc3 guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#bdd0e5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#536273 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#fd8489 guibg=NONE guisp=#fd8489 gui=NONE cterm=NONE
  hi SpellCap guifg=#f0aa8a guibg=NONE guisp=#f0aa8a gui=NONE cterm=NONE
  hi SpellLocal guifg=#bdd0e5 guibg=NONE guisp=#bdd0e5 gui=NONE cterm=NONE
  hi SpellRare guifg=#daccf0 guibg=NONE guisp=#daccf0 gui=NONE cterm=NONE
  hi TabLine guifg=#ffebc3 guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#ffebc3 guibg=#4c5866 guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#4c5866 guibg=#a9dd9d guisp=NONE gui=NONE cterm=NONE
  hi StatusLine guifg=#ffebc3 guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#ffebc3 guibg=#4c5866 guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#4c5866 guibg=#ffebc3 guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#616c72 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#70495d guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=#70495d guisp=NONE gui=italic cterm=italic
  hi MatchParen guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi PreProc guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Define guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Exception guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreCondit guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Function guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Label guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#eed094 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#eed094 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Constant guifg=#eed094 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Character guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Number guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Float guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Boolean guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#bdd0e5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#bdd0e5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#bdd0e5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Conditional guifg=#daccf0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Tag guifg=#daccf0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#daccf0 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Comment guifg=#7f8f9f guibg=NONE guisp=NONE gui=italic cterm=italic
  hi SpecialComment guifg=#84a78d guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Ignore guifg=#7f8f9f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE cterm=NONE
  hi ToolbarLine guifg=#ffebc3 guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#3c4c55 guibg=#ffebc3 guisp=NONE gui=bold cterm=bold
  hi Noise guifg=#ffebc3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi htmlStatement guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi htmlTag guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link xmlTag htmlTag
  hi! link xmlTagName htmlTagName
  hi! link xmlEndTag htmlEndTag
  hi cssClassName guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link cssClassNameDot cssClassName
  hi cssProp guifg=#ffebc3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link cssBraces Delimiter
  hi! link cssSelectorOp Delimiter
  hi! link cssSelectorOp2 Delimiter
  hi cssAtRule guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssTagName guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssAttrComma guifg=#ffebc3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssUnitDecorators guifg=#bdd0e5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssColor guifg=#ffebc3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssImportant guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link sassVariable Identifier
  hi sassClass guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi sassClassChar guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi sassCharset guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi sassInclude guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi scssSelectorName guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link scssSelectorChar scssSelectorName
  hi! link lessVariable Identifier
  hi lessClass guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsGlobalNodeObjects guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link jsFunction Keyword
  hi! link jsParens Delimiter
  hi! link jsBraces Delimiter
  hi! link jsBrackets Delimiter
  hi! link jsFuncBraces Delimiter
  hi! link jsFuncParens Delimiter
  hi! link jsObjectBraces Delimiter
  hi! link jsObjectParens Delimiter
  hi! link jsExceptions Exception
  hi jsObjectValue guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsObjectProp guifg=#eed094 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsBlockLabel guifg=#eed094 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsOperatorKeyword guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsGlobalObjects guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsUndefined guifg=#eed094 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsThis guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsArrowFunction guifg=#bdd0e5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi typescriptBranch guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link typescriptExceptions Exception
  hi! link typescriptParens Delimiter
  hi! link typescriptBraces Delimiter
  hi! link typescriptEndColons typescriptBraces
  hi typescriptGlobalObjects guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi typescriptLogicSymbols guifg=#daccf0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link typescriptOpSymbols Operator
  hi typescriptOperator guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi typescriptDomNodeConsts guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link dartCoreClasses Function
  hi dartTypedef guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dartOperator guifg=#bdd0e5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dartKeyword guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dartCoreClasses guifg=#eed094 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dartInterpolation guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link coffeeParen Delimiter
  hi! link coffeeCurly Delimiter
  hi! link coffeeBracket Delimiter
  hi coffeeCurlies guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi coffeeSpecialOp guifg=#daccf0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi coffeeExtendedOp guifg=#bdd0e5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi coffeeParens guifg=#ffebc3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi coffeeConstant guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi coffeeObjAssign guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi coffeeInterpDelim guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi javaScopeDecl guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi javaLabel guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi javaVarArg guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link javaParen Delimiter
  hi javaAnnotation guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pythonExClass guifg=#eed094 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pythonBoolean guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pythonOperator guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pythonClassVar guifg=#eed094 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pythonDecorator guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link pythonStatement Keyword
  hi pythonBuiltinFunc guifg=#eed094 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pythonDottedName guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi goDeclaration guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi goImport guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi goPackage guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi goStatement guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi goPredefinedIdentifiers guifg=#eed094 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link goUnsignedInts Function
  hi rustKeyword guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link rustDynKeyword Keyword
  hi! link rustExistential Keyword
  hi! link rustSuper Keyword
  hi! link rustExternCrate Keyword
  hi rustSelf guifg=#eed094 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustSigil guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustEnum guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustModPath guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link rustOperator Delimiter
  hi rustAttribute guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustDerive guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustMacroVariable guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustPubScopeCrate guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link phpParent Delimiter
  hi! link phpFunction Function
  hi phpMethod guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpInclude guifg=#f0aa8a guibg=NONE guisp=NONE gui=bold cterm=bold
  hi phpKeyword guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpClass guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpClassNamespaceSeparator guifg=#eed094 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpStaticClasses guifg=#eed094 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpIdentifier guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpIdentifierSimply guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpVarSelector guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link phpMemberSelector Delimiter
  hi! link phpOperator Delimiter
  hi! link csBraces Delimiter
  hi! link csParens Delimiter
  hi csUnspecifiedStatement guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csContextualStatement guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csNewType guifg=#eed094 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csClass guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csEndColon guifg=#ffebc3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fsharpKeyword guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fsharpModifier guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fsharpModule guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fsharpSymbol guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fsharpKeychar guifg=#bdd0e5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fsharpOperator guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyInclude guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyControl guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyCapitalizedMethod guifg=#f0aa8a guibg=NONE guisp=NONE gui=bold cterm=bold
  hi rubyDocumentation guifg=#84a78d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyPredefinedVariable guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlPackageDecl guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementPackage guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementInclude guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementStorage guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementInclude guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementFiledesc guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementScalar guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementList guifg=#eed094 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlFunction guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlMethod guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlVarSimpleMemberName guifg=#ffebc3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi haskellImportKeywords guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi haskellType guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi haskellWhere guifg=#bdd0e5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi haskellOperators guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link haskellDeclKeyword Type
  hi haskellDecl guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link luaBraces Delimiter
  hi luaFuncKeyword guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi luaFuncArgName guifg=#ffebc3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dTypedef guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dScopeDecl guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dLabel guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dOperator guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dAnnotation guifg=#eed094 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dEnum guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi scalaInstanceDeclaration guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi scalaCapitalWord guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi scalaAnnotation guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi scalaSpecial guifg=#bdd0e5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi scalaKeywordModifier guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi elixirAtom guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi elixirInclude guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi elixirAlias guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi elixirOperator guifg=#bdd0e5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link elixirDefine Type
  hi! link elixirPrivateDefine Type
  hi! link ocamlModule Type
  hi ocamlModPath guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fortranCall guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi shQuote guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi shDeref guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi shVariable guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi shOperator guifg=#bdd0e5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi zshPreProc guifg=#84a78d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi zshDeref guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fishKeyword guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fishStatement guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fishIdentifier guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsonKeyword guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsonQuote guifg=#ffebc3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsonBoolean guifg=#ffebc3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi yamlKey guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi yamlConstant guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi tomlTable guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi tomlTableArray guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi tomlKey guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEWarningSign guifg=#f0aa8a guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi ALEErrorSign guifg=#fd8489 guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi ALEInfoSign guifg=#bdd0e5 guibg=#616c72 guisp=NONE gui=NONE cterm=NONE
  hi ALEError guifg=NONE guibg=#70495d guisp=NONE gui=NONE cterm=NONE
  hi ALEWarning guifg=NONE guibg=#63431e guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextError guifg=#7f8f9f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextWarning guifg=#7f8f9f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextInfo guifg=#7f8f9f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link ALEVirtualTextStyleError ALEVirtualTextError
  hi! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
  hi CocHighlightText guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocCodeLens guifg=#7f8f9f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link CocErrorSign ALEErrorSign
  hi! link CocWarningSign ALEWarningSign
  hi! link CocInfoSign ALEInfoSign
  hi! link CocHintSign Label
  hi! link CocErrorHighlight ALEError
  hi! link CocWarningHighlight ALEWarning
  hi! link CocInfoHighlight ALEInfo
  hi! link CocWarningVirtualText ALEVirtualTextWarning
  hi! link CocErrorVirtualText ALEVirtualTextError
  hi! link CocInfoVirtualText ALEVirtualTextInfo
  hi! link CocHintVirtualText ALEVirtualTextInfo
  hi! link CocCodeLens ALEVirtualTextInfo
  hi NERDTreeFlags guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NERDTreeDirSlash guifg=#84a78d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NERDTreeCWD guifg=#84a78d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NERDTreeLinkFile guifg=#84a78d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NERDTreeLinkTarget guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MatchParenCur guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi StartifyBracket guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifyHeader guifg=#fd8489 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifyNumber guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifyPath guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifySlash guifg=#84a78d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifySection guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link StartifySpecial Comment
  hi! link StartifyFile Normal
  hi Sneak guifg=NONE guibg=#54695f guisp=NONE gui=NONE cterm=NONE
  hi gvSha guifg=#a9dd9d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi gvAuthor guifg=#f0aa8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  if !s:italics
    hi Folded gui=NONE cterm=NONE
    hi VisualNOS gui=NONE cterm=NONE
    hi Todo gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
    hi SpecialComment gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=223 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=223 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=223 ctermbg=239 cterm=NONE
    if !has('patch-8.0.0616') " Fix for Vim bug
      set background=dark
    endif
    hi Terminal ctermfg=223 ctermbg=239 cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=238 cterm=NONE
  hi Conceal ctermfg=245 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=223 ctermbg=235 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=235 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=235 cterm=NONE
  hi CursorLineNr ctermfg=245 ctermbg=244 cterm=NONE
  hi LineNr ctermfg=239 ctermbg=244 cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=244 cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=65 cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=136 cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=95 cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=67 cterm=NONE
  hi Directory ctermfg=150 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=238 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=210 ctermbg=244 cterm=NONE
  hi WarningMsg ctermfg=216 ctermbg=244 cterm=NONE
  hi ModeMsg ctermfg=239 ctermbg=150 cterm=NONE
  hi MoreMsg ctermfg=223 ctermbg=244 cterm=NONE
  hi FoldColumn ctermfg=223 ctermbg=244 cterm=NONE
  hi Folded ctermfg=223 ctermbg=244 cterm=italic
  hi IncSearch ctermfg=NONE ctermbg=95 cterm=underline
  hi Search ctermfg=NONE ctermbg=95 cterm=underline
  hi NonText ctermfg=245 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=223 ctermbg=244 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=244 cterm=NONE
  hi PmenuSel ctermfg=223 ctermbg=244 cterm=reverse
  hi PmenuThumb ctermfg=NONE ctermbg=223 cterm=NONE
  hi Question ctermfg=153 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=238 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=210 ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=216 ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=153 ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=189 ctermbg=NONE cterm=NONE
  hi TabLine ctermfg=223 ctermbg=244 cterm=NONE
  hi TabLineFill ctermfg=223 ctermbg=235 cterm=NONE
  hi TabLineSel ctermfg=235 ctermbg=150 cterm=NONE
  hi StatusLine ctermfg=223 ctermbg=244 cterm=NONE
  hi StatusLineNC ctermfg=223 ctermbg=235 cterm=NONE
  hi WildMenu ctermfg=235 ctermbg=223 cterm=NONE
  hi VertSplit ctermfg=244 ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=95 cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=95 cterm=italic
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi PreProc ctermfg=210 ctermbg=NONE cterm=NONE
  hi Define ctermfg=210 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=210 ctermbg=NONE cterm=NONE
  hi Exception ctermfg=210 ctermbg=NONE cterm=NONE
  hi Error ctermfg=210 ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=216 ctermbg=NONE cterm=NONE
  hi Title ctermfg=216 ctermbg=NONE cterm=NONE
  hi Function ctermfg=216 ctermbg=NONE cterm=NONE
  hi Label ctermfg=216 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=216 ctermbg=NONE cterm=NONE
  hi Type ctermfg=222 ctermbg=NONE cterm=NONE
  hi Special ctermfg=222 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=222 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=150 ctermbg=NONE cterm=NONE
  hi String ctermfg=150 ctermbg=NONE cterm=NONE
  hi Character ctermfg=150 ctermbg=NONE cterm=NONE
  hi Number ctermfg=150 ctermbg=NONE cterm=NONE
  hi Float ctermfg=150 ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=150 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=153 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=153 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=153 ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=189 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=189 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=189 ctermbg=NONE cterm=italic
  hi Comment ctermfg=245 ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=65 ctermbg=NONE cterm=italic
  hi Ignore ctermfg=245 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=223 ctermbg=244 cterm=NONE
  hi ToolbarButton ctermfg=239 ctermbg=223 cterm=bold
  hi Noise ctermfg=223 ctermbg=NONE cterm=NONE
  hi htmlStatement ctermfg=216 ctermbg=NONE cterm=NONE
  hi htmlTag ctermfg=150 ctermbg=NONE cterm=NONE
  hi! link xmlTag htmlTag
  hi! link xmlTagName htmlTagName
  hi! link xmlEndTag htmlEndTag
  hi cssClassName ctermfg=216 ctermbg=NONE cterm=NONE
  hi! link cssClassNameDot cssClassName
  hi cssProp ctermfg=223 ctermbg=NONE cterm=NONE
  hi! link cssBraces Delimiter
  hi! link cssSelectorOp Delimiter
  hi! link cssSelectorOp2 Delimiter
  hi cssAtRule ctermfg=210 ctermbg=NONE cterm=NONE
  hi cssTagName ctermfg=216 ctermbg=NONE cterm=NONE
  hi cssAttrComma ctermfg=223 ctermbg=NONE cterm=NONE
  hi cssUnitDecorators ctermfg=153 ctermbg=NONE cterm=NONE
  hi cssColor ctermfg=223 ctermbg=NONE cterm=NONE
  hi cssImportant ctermfg=210 ctermbg=NONE cterm=NONE
  hi! link sassVariable Identifier
  hi sassClass ctermfg=216 ctermbg=NONE cterm=NONE
  hi sassClassChar ctermfg=216 ctermbg=NONE cterm=NONE
  hi sassCharset ctermfg=150 ctermbg=NONE cterm=NONE
  hi sassInclude ctermfg=210 ctermbg=NONE cterm=NONE
  hi scssSelectorName ctermfg=216 ctermbg=NONE cterm=NONE
  hi! link scssSelectorChar scssSelectorName
  hi! link lessVariable Identifier
  hi lessClass ctermfg=216 ctermbg=NONE cterm=NONE
  hi jsGlobalNodeObjects ctermfg=210 ctermbg=NONE cterm=NONE
  hi! link jsFunction Keyword
  hi! link jsParens Delimiter
  hi! link jsBraces Delimiter
  hi! link jsBrackets Delimiter
  hi! link jsFuncBraces Delimiter
  hi! link jsFuncParens Delimiter
  hi! link jsObjectBraces Delimiter
  hi! link jsObjectParens Delimiter
  hi! link jsExceptions Exception
  hi jsObjectValue ctermfg=150 ctermbg=NONE cterm=NONE
  hi jsObjectProp ctermfg=222 ctermbg=NONE cterm=NONE
  hi jsBlockLabel ctermfg=222 ctermbg=NONE cterm=NONE
  hi jsOperatorKeyword ctermfg=216 ctermbg=NONE cterm=NONE
  hi jsGlobalObjects ctermfg=216 ctermbg=NONE cterm=NONE
  hi jsUndefined ctermfg=222 ctermbg=NONE cterm=NONE
  hi jsThis ctermfg=216 ctermbg=NONE cterm=NONE
  hi jsArrowFunction ctermfg=153 ctermbg=NONE cterm=NONE
  hi typescriptBranch ctermfg=216 ctermbg=NONE cterm=NONE
  hi! link typescriptExceptions Exception
  hi! link typescriptParens Delimiter
  hi! link typescriptBraces Delimiter
  hi! link typescriptEndColons typescriptBraces
  hi typescriptGlobalObjects ctermfg=216 ctermbg=NONE cterm=NONE
  hi typescriptLogicSymbols ctermfg=189 ctermbg=NONE cterm=NONE
  hi! link typescriptOpSymbols Operator
  hi typescriptOperator ctermfg=216 ctermbg=NONE cterm=NONE
  hi typescriptDomNodeConsts ctermfg=216 ctermbg=NONE cterm=NONE
  hi! link dartCoreClasses Function
  hi dartTypedef ctermfg=216 ctermbg=NONE cterm=NONE
  hi dartOperator ctermfg=153 ctermbg=NONE cterm=NONE
  hi dartKeyword ctermfg=210 ctermbg=NONE cterm=NONE
  hi dartCoreClasses ctermfg=222 ctermbg=NONE cterm=NONE
  hi dartInterpolation ctermfg=216 ctermbg=NONE cterm=NONE
  hi! link coffeeParen Delimiter
  hi! link coffeeCurly Delimiter
  hi! link coffeeBracket Delimiter
  hi coffeeCurlies ctermfg=150 ctermbg=NONE cterm=NONE
  hi coffeeSpecialOp ctermfg=189 ctermbg=NONE cterm=NONE
  hi coffeeExtendedOp ctermfg=153 ctermbg=NONE cterm=NONE
  hi coffeeParens ctermfg=223 ctermbg=NONE cterm=NONE
  hi coffeeConstant ctermfg=216 ctermbg=NONE cterm=NONE
  hi coffeeObjAssign ctermfg=216 ctermbg=NONE cterm=NONE
  hi coffeeInterpDelim ctermfg=150 ctermbg=NONE cterm=NONE
  hi javaScopeDecl ctermfg=210 ctermbg=NONE cterm=NONE
  hi javaLabel ctermfg=216 ctermbg=NONE cterm=NONE
  hi javaVarArg ctermfg=150 ctermbg=NONE cterm=NONE
  hi! link javaParen Delimiter
  hi javaAnnotation ctermfg=216 ctermbg=NONE cterm=NONE
  hi pythonExClass ctermfg=222 ctermbg=NONE cterm=NONE
  hi pythonBoolean ctermfg=150 ctermbg=NONE cterm=NONE
  hi pythonOperator ctermfg=150 ctermbg=NONE cterm=NONE
  hi pythonClassVar ctermfg=222 ctermbg=NONE cterm=NONE
  hi pythonDecorator ctermfg=210 ctermbg=NONE cterm=NONE
  hi! link pythonStatement Keyword
  hi pythonBuiltinFunc ctermfg=222 ctermbg=NONE cterm=NONE
  hi pythonDottedName ctermfg=216 ctermbg=NONE cterm=NONE
  hi goDeclaration ctermfg=216 ctermbg=NONE cterm=NONE
  hi goImport ctermfg=216 ctermbg=NONE cterm=NONE
  hi goPackage ctermfg=210 ctermbg=NONE cterm=NONE
  hi goStatement ctermfg=150 ctermbg=NONE cterm=NONE
  hi goPredefinedIdentifiers ctermfg=222 ctermbg=NONE cterm=NONE
  hi! link goUnsignedInts Function
  hi rustKeyword ctermfg=150 ctermbg=NONE cterm=NONE
  hi! link rustDynKeyword Keyword
  hi! link rustExistential Keyword
  hi! link rustSuper Keyword
  hi! link rustExternCrate Keyword
  hi rustSelf ctermfg=222 ctermbg=NONE cterm=NONE
  hi rustSigil ctermfg=150 ctermbg=NONE cterm=NONE
  hi rustEnum ctermfg=216 ctermbg=NONE cterm=NONE
  hi rustModPath ctermfg=216 ctermbg=NONE cterm=NONE
  hi! link rustOperator Delimiter
  hi rustAttribute ctermfg=210 ctermbg=NONE cterm=NONE
  hi rustDerive ctermfg=216 ctermbg=NONE cterm=NONE
  hi rustMacroVariable ctermfg=216 ctermbg=NONE cterm=NONE
  hi rustPubScopeCrate ctermfg=216 ctermbg=NONE cterm=NONE
  hi! link phpParent Delimiter
  hi! link phpFunction Function
  hi phpMethod ctermfg=216 ctermbg=NONE cterm=NONE
  hi phpInclude ctermfg=216 ctermbg=NONE cterm=bold
  hi phpKeyword ctermfg=210 ctermbg=NONE cterm=NONE
  hi phpClass ctermfg=216 ctermbg=NONE cterm=NONE
  hi phpClassNamespaceSeparator ctermfg=222 ctermbg=NONE cterm=NONE
  hi phpStaticClasses ctermfg=222 ctermbg=NONE cterm=NONE
  hi phpIdentifier ctermfg=216 ctermbg=NONE cterm=NONE
  hi phpIdentifierSimply ctermfg=216 ctermbg=NONE cterm=NONE
  hi phpVarSelector ctermfg=210 ctermbg=NONE cterm=NONE
  hi! link phpMemberSelector Delimiter
  hi! link phpOperator Delimiter
  hi! link csBraces Delimiter
  hi! link csParens Delimiter
  hi csUnspecifiedStatement ctermfg=210 ctermbg=NONE cterm=NONE
  hi csContextualStatement ctermfg=150 ctermbg=NONE cterm=NONE
  hi csNewType ctermfg=222 ctermbg=NONE cterm=NONE
  hi csClass ctermfg=210 ctermbg=NONE cterm=NONE
  hi csEndColon ctermfg=223 ctermbg=NONE cterm=NONE
  hi fsharpKeyword ctermfg=216 ctermbg=NONE cterm=NONE
  hi fsharpModifier ctermfg=210 ctermbg=NONE cterm=NONE
  hi fsharpModule ctermfg=216 ctermbg=NONE cterm=NONE
  hi fsharpSymbol ctermfg=150 ctermbg=NONE cterm=NONE
  hi fsharpKeychar ctermfg=153 ctermbg=NONE cterm=NONE
  hi fsharpOperator ctermfg=150 ctermbg=NONE cterm=NONE
  hi rubyInclude ctermfg=216 ctermbg=NONE cterm=NONE
  hi rubyControl ctermfg=210 ctermbg=NONE cterm=NONE
  hi rubyCapitalizedMethod ctermfg=216 ctermbg=NONE cterm=bold
  hi rubyDocumentation ctermfg=65 ctermbg=NONE cterm=NONE
  hi rubyPredefinedVariable ctermfg=150 ctermbg=NONE cterm=NONE
  hi perlPackageDecl ctermfg=216 ctermbg=NONE cterm=NONE
  hi perlStatementPackage ctermfg=210 ctermbg=NONE cterm=NONE
  hi perlStatementInclude ctermfg=216 ctermbg=NONE cterm=NONE
  hi perlStatementStorage ctermfg=210 ctermbg=NONE cterm=NONE
  hi perlStatementInclude ctermfg=210 ctermbg=NONE cterm=NONE
  hi perlStatementFiledesc ctermfg=216 ctermbg=NONE cterm=NONE
  hi perlStatementScalar ctermfg=216 ctermbg=NONE cterm=NONE
  hi perlStatementList ctermfg=222 ctermbg=NONE cterm=NONE
  hi perlFunction ctermfg=210 ctermbg=NONE cterm=NONE
  hi perlMethod ctermfg=216 ctermbg=NONE cterm=NONE
  hi perlVarSimpleMemberName ctermfg=223 ctermbg=NONE cterm=NONE
  hi haskellImportKeywords ctermfg=210 ctermbg=NONE cterm=NONE
  hi haskellType ctermfg=216 ctermbg=NONE cterm=NONE
  hi haskellWhere ctermfg=153 ctermbg=NONE cterm=NONE
  hi haskellOperators ctermfg=150 ctermbg=NONE cterm=NONE
  hi! link haskellDeclKeyword Type
  hi haskellDecl ctermfg=210 ctermbg=NONE cterm=NONE
  hi! link luaBraces Delimiter
  hi luaFuncKeyword ctermfg=210 ctermbg=NONE cterm=NONE
  hi luaFuncArgName ctermfg=223 ctermbg=NONE cterm=NONE
  hi dTypedef ctermfg=216 ctermbg=NONE cterm=NONE
  hi dScopeDecl ctermfg=210 ctermbg=NONE cterm=NONE
  hi dLabel ctermfg=150 ctermbg=NONE cterm=NONE
  hi dOperator ctermfg=150 ctermbg=NONE cterm=NONE
  hi dAnnotation ctermfg=222 ctermbg=NONE cterm=NONE
  hi dEnum ctermfg=216 ctermbg=NONE cterm=NONE
  hi scalaInstanceDeclaration ctermfg=150 ctermbg=NONE cterm=NONE
  hi scalaCapitalWord ctermfg=150 ctermbg=NONE cterm=NONE
  hi scalaAnnotation ctermfg=210 ctermbg=NONE cterm=NONE
  hi scalaSpecial ctermfg=153 ctermbg=NONE cterm=NONE
  hi scalaKeywordModifier ctermfg=216 ctermbg=NONE cterm=NONE
  hi elixirAtom ctermfg=150 ctermbg=NONE cterm=NONE
  hi elixirInclude ctermfg=210 ctermbg=NONE cterm=NONE
  hi elixirAlias ctermfg=216 ctermbg=NONE cterm=NONE
  hi elixirOperator ctermfg=153 ctermbg=NONE cterm=NONE
  hi! link elixirDefine Type
  hi! link elixirPrivateDefine Type
  hi! link ocamlModule Type
  hi ocamlModPath ctermfg=150 ctermbg=NONE cterm=NONE
  hi fortranCall ctermfg=210 ctermbg=NONE cterm=NONE
  hi shQuote ctermfg=150 ctermbg=NONE cterm=NONE
  hi shDeref ctermfg=150 ctermbg=NONE cterm=NONE
  hi shVariable ctermfg=216 ctermbg=NONE cterm=NONE
  hi shOperator ctermfg=153 ctermbg=NONE cterm=NONE
  hi zshPreProc ctermfg=65 ctermbg=NONE cterm=NONE
  hi zshDeref ctermfg=150 ctermbg=NONE cterm=NONE
  hi fishKeyword ctermfg=210 ctermbg=NONE cterm=NONE
  hi fishStatement ctermfg=216 ctermbg=NONE cterm=NONE
  hi fishIdentifier ctermfg=150 ctermbg=NONE cterm=NONE
  hi jsonKeyword ctermfg=216 ctermbg=NONE cterm=NONE
  hi jsonQuote ctermfg=223 ctermbg=NONE cterm=NONE
  hi jsonBoolean ctermfg=223 ctermbg=NONE cterm=NONE
  hi yamlKey ctermfg=216 ctermbg=NONE cterm=NONE
  hi yamlConstant ctermfg=150 ctermbg=NONE cterm=NONE
  hi tomlTable ctermfg=210 ctermbg=NONE cterm=NONE
  hi tomlTableArray ctermfg=210 ctermbg=NONE cterm=NONE
  hi tomlKey ctermfg=216 ctermbg=NONE cterm=NONE
  hi ALEWarningSign ctermfg=216 ctermbg=244 cterm=NONE
  hi ALEErrorSign ctermfg=210 ctermbg=244 cterm=NONE
  hi ALEInfoSign ctermfg=153 ctermbg=244 cterm=NONE
  hi ALEError ctermfg=NONE ctermbg=95 cterm=NONE
  hi ALEWarning ctermfg=NONE ctermbg=136 cterm=NONE
  hi ALEVirtualTextError ctermfg=245 ctermbg=NONE cterm=NONE
  hi ALEVirtualTextWarning ctermfg=245 ctermbg=NONE cterm=NONE
  hi ALEVirtualTextInfo ctermfg=245 ctermbg=NONE cterm=NONE
  hi! link ALEVirtualTextStyleError ALEVirtualTextError
  hi! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
  hi CocHighlightText ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocCodeLens ctermfg=245 ctermbg=NONE cterm=NONE
  hi! link CocErrorSign ALEErrorSign
  hi! link CocWarningSign ALEWarningSign
  hi! link CocInfoSign ALEInfoSign
  hi! link CocHintSign Label
  hi! link CocErrorHighlight ALEError
  hi! link CocWarningHighlight ALEWarning
  hi! link CocInfoHighlight ALEInfo
  hi! link CocWarningVirtualText ALEVirtualTextWarning
  hi! link CocErrorVirtualText ALEVirtualTextError
  hi! link CocInfoVirtualText ALEVirtualTextInfo
  hi! link CocHintVirtualText ALEVirtualTextInfo
  hi! link CocCodeLens ALEVirtualTextInfo
  hi NERDTreeFlags ctermfg=216 ctermbg=NONE cterm=NONE
  hi NERDTreeDirSlash ctermfg=65 ctermbg=NONE cterm=NONE
  hi NERDTreeCWD ctermfg=65 ctermbg=NONE cterm=NONE
  hi NERDTreeLinkFile ctermfg=65 ctermbg=NONE cterm=NONE
  hi NERDTreeLinkTarget ctermfg=150 ctermbg=NONE cterm=NONE
  hi MatchParenCur ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur ctermfg=NONE ctermbg=NONE cterm=underline
  hi StartifyBracket ctermfg=150 ctermbg=NONE cterm=NONE
  hi StartifyHeader ctermfg=210 ctermbg=NONE cterm=NONE
  hi StartifyNumber ctermfg=216 ctermbg=NONE cterm=NONE
  hi StartifyPath ctermfg=150 ctermbg=NONE cterm=NONE
  hi StartifySlash ctermfg=65 ctermbg=NONE cterm=NONE
  hi StartifySection ctermfg=216 ctermbg=NONE cterm=NONE
  hi! link StartifySpecial Comment
  hi! link StartifyFile Normal
  hi Sneak ctermfg=NONE ctermbg=65 cterm=NONE
  hi gvSha ctermfg=150 ctermbg=NONE cterm=NONE
  hi gvAuthor ctermfg=216 ctermbg=NONE cterm=NONE
  if !s:italics
    hi Folded cterm=NONE
    hi VisualNOS cterm=NONE
    hi Todo cterm=NONE
    hi Comment cterm=NONE
    hi SpecialComment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=White ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=White ctermbg=Black cterm=NONE
    hi Terminal ctermfg=White ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=DarkGrey cterm=NONE
  hi Conceal ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=White ctermbg=Black cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=Black cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi CursorLineNr ctermfg=Grey ctermbg=Grey cterm=NONE
  hi LineNr ctermfg=Black ctermbg=Grey cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=Grey cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=DarkGreen cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=DarkYellow cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=DarkRed cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=DarkBlue cterm=NONE
  hi Directory ctermfg=Green ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=Red ctermbg=Grey cterm=NONE
  hi WarningMsg ctermfg=DarkYellow ctermbg=Grey cterm=NONE
  hi ModeMsg ctermfg=Black ctermbg=Green cterm=NONE
  hi MoreMsg ctermfg=White ctermbg=Grey cterm=NONE
  hi FoldColumn ctermfg=White ctermbg=Grey cterm=NONE
  hi Folded ctermfg=White ctermbg=Grey cterm=italic
  hi IncSearch ctermfg=NONE ctermbg=DarkRed cterm=underline
  hi Search ctermfg=NONE ctermbg=DarkRed cterm=underline
  hi NonText ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=White ctermbg=Grey cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=Grey cterm=NONE
  hi PmenuSel ctermfg=White ctermbg=Grey cterm=reverse
  hi PmenuThumb ctermfg=NONE ctermbg=White cterm=NONE
  hi Question ctermfg=Blue ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=Red ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=Blue ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi TabLine ctermfg=White ctermbg=Grey cterm=NONE
  hi TabLineFill ctermfg=White ctermbg=Black cterm=NONE
  hi TabLineSel ctermfg=Black ctermbg=Green cterm=NONE
  hi StatusLine ctermfg=White ctermbg=Grey cterm=NONE
  hi StatusLineNC ctermfg=White ctermbg=Black cterm=NONE
  hi WildMenu ctermfg=Black ctermbg=White cterm=NONE
  hi VertSplit ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=DarkRed cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=DarkRed cterm=italic
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi PreProc ctermfg=Red ctermbg=NONE cterm=NONE
  hi Define ctermfg=Red ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=Red ctermbg=NONE cterm=NONE
  hi Exception ctermfg=Red ctermbg=NONE cterm=NONE
  hi Error ctermfg=Red ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Title ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Function ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Label ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Type ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Special ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Constant ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=Green ctermbg=NONE cterm=NONE
  hi String ctermfg=Green ctermbg=NONE cterm=NONE
  hi Character ctermfg=Green ctermbg=NONE cterm=NONE
  hi Number ctermfg=Green ctermbg=NONE cterm=NONE
  hi Float ctermfg=Green ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=Green ctermbg=NONE cterm=NONE
  hi Statement ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Operator ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Tag ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Todo ctermfg=Magenta ctermbg=NONE cterm=italic
  hi Comment ctermfg=Grey ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=DarkGreen ctermbg=NONE cterm=italic
  hi Ignore ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=White ctermbg=Grey cterm=NONE
  hi ToolbarButton ctermfg=Black ctermbg=White cterm=bold
  hi Noise ctermfg=White ctermbg=NONE cterm=NONE
  hi htmlStatement ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi htmlTag ctermfg=Green ctermbg=NONE cterm=NONE
  hi! link xmlTag htmlTag
  hi! link xmlTagName htmlTagName
  hi! link xmlEndTag htmlEndTag
  hi cssClassName ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link cssClassNameDot cssClassName
  hi cssProp ctermfg=White ctermbg=NONE cterm=NONE
  hi! link cssBraces Delimiter
  hi! link cssSelectorOp Delimiter
  hi! link cssSelectorOp2 Delimiter
  hi cssAtRule ctermfg=Red ctermbg=NONE cterm=NONE
  hi cssTagName ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi cssAttrComma ctermfg=White ctermbg=NONE cterm=NONE
  hi cssUnitDecorators ctermfg=Blue ctermbg=NONE cterm=NONE
  hi cssColor ctermfg=White ctermbg=NONE cterm=NONE
  hi cssImportant ctermfg=Red ctermbg=NONE cterm=NONE
  hi! link sassVariable Identifier
  hi sassClass ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi sassClassChar ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi sassCharset ctermfg=Green ctermbg=NONE cterm=NONE
  hi sassInclude ctermfg=Red ctermbg=NONE cterm=NONE
  hi scssSelectorName ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link scssSelectorChar scssSelectorName
  hi! link lessVariable Identifier
  hi lessClass ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi jsGlobalNodeObjects ctermfg=Red ctermbg=NONE cterm=NONE
  hi! link jsFunction Keyword
  hi! link jsParens Delimiter
  hi! link jsBraces Delimiter
  hi! link jsBrackets Delimiter
  hi! link jsFuncBraces Delimiter
  hi! link jsFuncParens Delimiter
  hi! link jsObjectBraces Delimiter
  hi! link jsObjectParens Delimiter
  hi! link jsExceptions Exception
  hi jsObjectValue ctermfg=Green ctermbg=NONE cterm=NONE
  hi jsObjectProp ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi jsBlockLabel ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi jsOperatorKeyword ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi jsGlobalObjects ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi jsUndefined ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi jsThis ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi jsArrowFunction ctermfg=Blue ctermbg=NONE cterm=NONE
  hi typescriptBranch ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link typescriptExceptions Exception
  hi! link typescriptParens Delimiter
  hi! link typescriptBraces Delimiter
  hi! link typescriptEndColons typescriptBraces
  hi typescriptGlobalObjects ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi typescriptLogicSymbols ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi! link typescriptOpSymbols Operator
  hi typescriptOperator ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi typescriptDomNodeConsts ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link dartCoreClasses Function
  hi dartTypedef ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi dartOperator ctermfg=Blue ctermbg=NONE cterm=NONE
  hi dartKeyword ctermfg=Red ctermbg=NONE cterm=NONE
  hi dartCoreClasses ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi dartInterpolation ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link coffeeParen Delimiter
  hi! link coffeeCurly Delimiter
  hi! link coffeeBracket Delimiter
  hi coffeeCurlies ctermfg=Green ctermbg=NONE cterm=NONE
  hi coffeeSpecialOp ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi coffeeExtendedOp ctermfg=Blue ctermbg=NONE cterm=NONE
  hi coffeeParens ctermfg=White ctermbg=NONE cterm=NONE
  hi coffeeConstant ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi coffeeObjAssign ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi coffeeInterpDelim ctermfg=Green ctermbg=NONE cterm=NONE
  hi javaScopeDecl ctermfg=Red ctermbg=NONE cterm=NONE
  hi javaLabel ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi javaVarArg ctermfg=Green ctermbg=NONE cterm=NONE
  hi! link javaParen Delimiter
  hi javaAnnotation ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi pythonExClass ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi pythonBoolean ctermfg=Green ctermbg=NONE cterm=NONE
  hi pythonOperator ctermfg=Green ctermbg=NONE cterm=NONE
  hi pythonClassVar ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi pythonDecorator ctermfg=Red ctermbg=NONE cterm=NONE
  hi! link pythonStatement Keyword
  hi pythonBuiltinFunc ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi pythonDottedName ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi goDeclaration ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi goImport ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi goPackage ctermfg=Red ctermbg=NONE cterm=NONE
  hi goStatement ctermfg=Green ctermbg=NONE cterm=NONE
  hi goPredefinedIdentifiers ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi! link goUnsignedInts Function
  hi rustKeyword ctermfg=Green ctermbg=NONE cterm=NONE
  hi! link rustDynKeyword Keyword
  hi! link rustExistential Keyword
  hi! link rustSuper Keyword
  hi! link rustExternCrate Keyword
  hi rustSelf ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi rustSigil ctermfg=Green ctermbg=NONE cterm=NONE
  hi rustEnum ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi rustModPath ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link rustOperator Delimiter
  hi rustAttribute ctermfg=Red ctermbg=NONE cterm=NONE
  hi rustDerive ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi rustMacroVariable ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi rustPubScopeCrate ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link phpParent Delimiter
  hi! link phpFunction Function
  hi phpMethod ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi phpInclude ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi phpKeyword ctermfg=Red ctermbg=NONE cterm=NONE
  hi phpClass ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi phpClassNamespaceSeparator ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi phpStaticClasses ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi phpIdentifier ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi phpIdentifierSimply ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi phpVarSelector ctermfg=Red ctermbg=NONE cterm=NONE
  hi! link phpMemberSelector Delimiter
  hi! link phpOperator Delimiter
  hi! link csBraces Delimiter
  hi! link csParens Delimiter
  hi csUnspecifiedStatement ctermfg=Red ctermbg=NONE cterm=NONE
  hi csContextualStatement ctermfg=Green ctermbg=NONE cterm=NONE
  hi csNewType ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi csClass ctermfg=Red ctermbg=NONE cterm=NONE
  hi csEndColon ctermfg=White ctermbg=NONE cterm=NONE
  hi fsharpKeyword ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi fsharpModifier ctermfg=Red ctermbg=NONE cterm=NONE
  hi fsharpModule ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi fsharpSymbol ctermfg=Green ctermbg=NONE cterm=NONE
  hi fsharpKeychar ctermfg=Blue ctermbg=NONE cterm=NONE
  hi fsharpOperator ctermfg=Green ctermbg=NONE cterm=NONE
  hi rubyInclude ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi rubyControl ctermfg=Red ctermbg=NONE cterm=NONE
  hi rubyCapitalizedMethod ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi rubyDocumentation ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi rubyPredefinedVariable ctermfg=Green ctermbg=NONE cterm=NONE
  hi perlPackageDecl ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi perlStatementPackage ctermfg=Red ctermbg=NONE cterm=NONE
  hi perlStatementInclude ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi perlStatementStorage ctermfg=Red ctermbg=NONE cterm=NONE
  hi perlStatementInclude ctermfg=Red ctermbg=NONE cterm=NONE
  hi perlStatementFiledesc ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi perlStatementScalar ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi perlStatementList ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi perlFunction ctermfg=Red ctermbg=NONE cterm=NONE
  hi perlMethod ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi perlVarSimpleMemberName ctermfg=White ctermbg=NONE cterm=NONE
  hi haskellImportKeywords ctermfg=Red ctermbg=NONE cterm=NONE
  hi haskellType ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi haskellWhere ctermfg=Blue ctermbg=NONE cterm=NONE
  hi haskellOperators ctermfg=Green ctermbg=NONE cterm=NONE
  hi! link haskellDeclKeyword Type
  hi haskellDecl ctermfg=Red ctermbg=NONE cterm=NONE
  hi! link luaBraces Delimiter
  hi luaFuncKeyword ctermfg=Red ctermbg=NONE cterm=NONE
  hi luaFuncArgName ctermfg=White ctermbg=NONE cterm=NONE
  hi dTypedef ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi dScopeDecl ctermfg=Red ctermbg=NONE cterm=NONE
  hi dLabel ctermfg=Green ctermbg=NONE cterm=NONE
  hi dOperator ctermfg=Green ctermbg=NONE cterm=NONE
  hi dAnnotation ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi dEnum ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi scalaInstanceDeclaration ctermfg=Green ctermbg=NONE cterm=NONE
  hi scalaCapitalWord ctermfg=Green ctermbg=NONE cterm=NONE
  hi scalaAnnotation ctermfg=Red ctermbg=NONE cterm=NONE
  hi scalaSpecial ctermfg=Blue ctermbg=NONE cterm=NONE
  hi scalaKeywordModifier ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi elixirAtom ctermfg=Green ctermbg=NONE cterm=NONE
  hi elixirInclude ctermfg=Red ctermbg=NONE cterm=NONE
  hi elixirAlias ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi elixirOperator ctermfg=Blue ctermbg=NONE cterm=NONE
  hi! link elixirDefine Type
  hi! link elixirPrivateDefine Type
  hi! link ocamlModule Type
  hi ocamlModPath ctermfg=Green ctermbg=NONE cterm=NONE
  hi fortranCall ctermfg=Red ctermbg=NONE cterm=NONE
  hi shQuote ctermfg=Green ctermbg=NONE cterm=NONE
  hi shDeref ctermfg=Green ctermbg=NONE cterm=NONE
  hi shVariable ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi shOperator ctermfg=Blue ctermbg=NONE cterm=NONE
  hi zshPreProc ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi zshDeref ctermfg=Green ctermbg=NONE cterm=NONE
  hi fishKeyword ctermfg=Red ctermbg=NONE cterm=NONE
  hi fishStatement ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi fishIdentifier ctermfg=Green ctermbg=NONE cterm=NONE
  hi jsonKeyword ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi jsonQuote ctermfg=White ctermbg=NONE cterm=NONE
  hi jsonBoolean ctermfg=White ctermbg=NONE cterm=NONE
  hi yamlKey ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi yamlConstant ctermfg=Green ctermbg=NONE cterm=NONE
  hi tomlTable ctermfg=Red ctermbg=NONE cterm=NONE
  hi tomlTableArray ctermfg=Red ctermbg=NONE cterm=NONE
  hi tomlKey ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi ALEWarningSign ctermfg=DarkYellow ctermbg=Grey cterm=NONE
  hi ALEErrorSign ctermfg=Red ctermbg=Grey cterm=NONE
  hi ALEInfoSign ctermfg=Blue ctermbg=Grey cterm=NONE
  hi ALEError ctermfg=NONE ctermbg=DarkRed cterm=NONE
  hi ALEWarning ctermfg=NONE ctermbg=DarkYellow cterm=NONE
  hi ALEVirtualTextError ctermfg=Grey ctermbg=NONE cterm=NONE
  hi ALEVirtualTextWarning ctermfg=Grey ctermbg=NONE cterm=NONE
  hi ALEVirtualTextInfo ctermfg=Grey ctermbg=NONE cterm=NONE
  hi! link ALEVirtualTextStyleError ALEVirtualTextError
  hi! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
  hi CocHighlightText ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocCodeLens ctermfg=Grey ctermbg=NONE cterm=NONE
  hi! link CocErrorSign ALEErrorSign
  hi! link CocWarningSign ALEWarningSign
  hi! link CocInfoSign ALEInfoSign
  hi! link CocHintSign Label
  hi! link CocErrorHighlight ALEError
  hi! link CocWarningHighlight ALEWarning
  hi! link CocInfoHighlight ALEInfo
  hi! link CocWarningVirtualText ALEVirtualTextWarning
  hi! link CocErrorVirtualText ALEVirtualTextError
  hi! link CocInfoVirtualText ALEVirtualTextInfo
  hi! link CocHintVirtualText ALEVirtualTextInfo
  hi! link CocCodeLens ALEVirtualTextInfo
  hi NERDTreeFlags ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi NERDTreeDirSlash ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi NERDTreeCWD ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi NERDTreeLinkFile ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi NERDTreeLinkTarget ctermfg=Green ctermbg=NONE cterm=NONE
  hi MatchParenCur ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur ctermfg=NONE ctermbg=NONE cterm=underline
  hi StartifyBracket ctermfg=Green ctermbg=NONE cterm=NONE
  hi StartifyHeader ctermfg=Red ctermbg=NONE cterm=NONE
  hi StartifyNumber ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi StartifyPath ctermfg=Green ctermbg=NONE cterm=NONE
  hi StartifySlash ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi StartifySection ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link StartifySpecial Comment
  hi! link StartifyFile Normal
  hi Sneak ctermfg=NONE ctermbg=DarkGreen cterm=NONE
  hi gvSha ctermfg=Green ctermbg=NONE cterm=NONE
  hi gvAuthor ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  if !s:italics
    hi Folded cterm=NONE
    hi VisualNOS cterm=NONE
    hi Todo cterm=NONE
    hi Comment cterm=NONE
    hi SpecialComment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: white         #ffebc3           223               White
" Color: black         #3c4c55           239               Black
" Color: dark          #4c5866           235               Black
" Color: darkgrey      #536273           238               DarkGrey
" Color: darkgreyalt   #5d6672           238               DarkGrey
" Color: grey          #616c72           244               Grey
" Color: greyalt       #646f7c           244               Grey
" Color: greyer        #7f8f9f           245               Grey
" Color: red           #fd8489           210               Red
" Color: orange        #f0aa8a           216               DarkYellow
" Color: yellow        #eed094           222               Yellow
" Color: green         #a9dd9d           150               Green
" Color: blackgreen    #84a78d           65                DarkGreen
" Color: blue          #bdd0e5           153               Blue
" Color: magenta       #daccf0           189               Magenta
" Color: darkred       #70495d           95                DarkRed
" Color: darkgreen     #54695f           65                DarkGreen
" Color: darkblue      #43596f           67                DarkBlue
" Color: darkorange    #63431e           136               DarkYellow
" Color: lightbrown    #b2a488           247               Brown
" Color: brown         #918175           246               Brown
" Color: darkbrown     #2d2c29           237               Black
" Term colors: greyer red green orange blue magenta green white
" Term colors: greyer red green yellow blue magenta green white
" Color: unused #000000 0 0
