" Name:         Forest Dusk
" Description:  🌲 Comfortable & Pleasant VIM Color Scheme
" Author:       Sainnhepark <sainnhe@gmail.com>
" Maintainer:   Sainnhepark <sainnhe@gmail.com>
" Website:      https://github.com/sainnhe/vim-color-forest-night/
" License:      MIT && Anti-996
" Last Updated: Mon 15 Jul 2019 08:35:22 PM CST

" Generated by Colortemplate v2.0.0

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'forest-dusk'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS'))

let s:italics = get(g:, 'forest_night_use_italic', 1) && s:italics
hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Debug Special
hi! link Include PreProc
hi! link Macro PreProc
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link Structure Type
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#7e837c', '#fc796b', '#a8cb79', '#ed9c6a',
        \ '#bcbfb4', '#d8bbbd', '#a8cb79', '#fdd89a', '#7e837c', '#fc796b',
        \ '#a8cb79', '#edc074', '#bcbfb4', '#d8bbbd', '#a8cb79', '#fdd89a']
  if get(g:, 'forest_night_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#fdd89a guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#fdd89a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#fdd89a guibg=#3c4542 guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#fdd89a guibg=#3c4542 guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=fg guibg=#535a5a guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=#7e837c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn guifg=NONE guibg=#4b514f guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#4b514f guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#7e837c guibg=#606357 guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#3c4542 guibg=#606357 guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=NONE guibg=#606357 guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=NONE guibg=#536049 guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#613d13 guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=NONE guibg=#6f4246 guisp=NONE gui=NONE cterm=NONE
  hi DiffText guifg=NONE guibg=#435255 guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#535a5a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#fc796b guibg=#606357 guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#ed9c6a guibg=#606357 guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#3c4542 guibg=#a8cb79 guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#fdd89a guibg=#606357 guisp=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#fdd89a guibg=#606357 guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#fdd89a guibg=#606357 guisp=NONE gui=italic cterm=italic
  hi IncSearch guifg=NONE guibg=#6f4246 guisp=NONE gui=underline cterm=underline
  hi Search guifg=NONE guibg=#6f4246 guisp=NONE gui=underline cterm=underline
  hi NonText guifg=#7e837c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#fdd89a guibg=#606357 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#606357 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#fdd89a guibg=#606357 guisp=NONE gui=reverse cterm=reverse
  hi PmenuThumb guifg=NONE guibg=#fdd89a guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#bcbfb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#535a5a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#fc796b guibg=NONE guisp=#fc796b gui=NONE cterm=NONE
  hi SpellCap guifg=#ed9c6a guibg=NONE guisp=#ed9c6a gui=NONE cterm=NONE
  hi SpellLocal guifg=#bcbfb4 guibg=NONE guisp=#bcbfb4 gui=NONE cterm=NONE
  hi SpellRare guifg=#d8bbbd guibg=NONE guisp=#d8bbbd gui=NONE cterm=NONE
  hi TabLine guifg=#fdd89a guibg=#606357 guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#fdd89a guibg=#4b514f guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#4b514f guibg=#a8cb79 guisp=NONE gui=NONE cterm=NONE
  hi StatusLine guifg=#fdd89a guibg=#606357 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#fdd89a guibg=#4b514f guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#4b514f guibg=#fdd89a guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#606357 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#6f4246 guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=#6f4246 guisp=NONE gui=italic cterm=italic
  hi MatchParen guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi Todo guifg=#d8bbbd guibg=NONE guisp=NONE gui=italic cterm=italic
  hi PreProc guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Define guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Exception guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreCondit guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Function guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Label guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Constant guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Character guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Number guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Float guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Boolean guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#bcbfb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#bcbfb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#bcbfb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Conditional guifg=#d8bbbd guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Tag guifg=#d8bbbd guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#7e837c guibg=NONE guisp=NONE gui=italic cterm=italic
  hi SpecialComment guifg=#83986f guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Ignore guifg=#7e837c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE cterm=NONE
  hi ToolbarLine guifg=#fdd89a guibg=#606357 guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#3c4542 guibg=#fdd89a guisp=NONE gui=bold cterm=bold
  hi Noise guifg=#fdd89a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownLinkText guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownUrl guifg=#a8cb79 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi markdownListMarker guifg=#bcbfb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownCode guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownId guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownIdDeclaration guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link markdownBoldDelimiter Comment
  hi! link markdownItalicDelimiter Comment
  hi markdownBold guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalic guifg=NONE guibg=NONE guisp=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi markdownRule guifg=#d8bbbd guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi mkdListItem guifg=#bcbfb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi mkdInlineURL guifg=#edc074 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi mkdLink guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi mkdURL guifg=#a8cb79 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi! link mkdCodeDelimiter Delimiter
  hi mkdID guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link mkdBold Comment
  hi! link mkdItalic Comment
  hi mkdRule guifg=#d8bbbd guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rstSections guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rstDirective guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rstExplicitMarkup guifg=#bcbfb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rstStandaloneHyperlink guifg=#a8cb79 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi texStatement guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi texBeginEnd guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi texDefCmd guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi texDefName guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi texSection guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi texDocType guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi texOnlyMath guifg=#d8bbbd guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi texNewCmd guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi texCmdName guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi htmlStatement guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi htmlTag guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi htmlLink guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlBold guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlItalic guifg=NONE guibg=NONE guisp=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi xmlTag guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi xmlTagName guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi xmlEndTag guifg=#bcbfb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssClassName guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link cssClassNameDot cssClassName
  hi cssProp guifg=#fdd89a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link cssBraces Delimiter
  hi! link cssSelectorOp Delimiter
  hi! link cssSelectorOp2 Delimiter
  hi cssAtRule guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssTagName guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssAttrComma guifg=#fdd89a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssUnitDecorators guifg=#bcbfb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssColor guifg=#fdd89a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssImportant guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link sassVariable Identifier
  hi sassClass guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi sassClassChar guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi sassCharset guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi sassInclude guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi scssSelectorName guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link scssSelectorChar scssSelectorName
  hi! link lessVariable Identifier
  hi lessClass guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link javaScriptBraces Delimiter
  hi javaScriptOperator guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi javaScriptNull guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi javaScriptGlobal guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi javaScriptMessage guifg=#bcbfb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi javaScriptMember guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsGlobalNodeObjects guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link jsFunction Keyword
  hi! link jsParens Delimiter
  hi! link jsBraces Delimiter
  hi! link jsBrackets Delimiter
  hi! link jsFuncBraces Delimiter
  hi! link jsFuncParens Delimiter
  hi! link jsObjectBraces Delimiter
  hi! link jsObjectParens Delimiter
  hi! link jsExceptions Exception
  hi jsObjectValue guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsObjectProp guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsBlockLabel guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsOperatorKeyword guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsGlobalObjects guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsUndefined guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsThis guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsArrowFunction guifg=#bcbfb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi typescriptBranch guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link typescriptExceptions Exception
  hi! link typescriptParens Delimiter
  hi! link typescriptBraces Delimiter
  hi! link typescriptEndColons typescriptBraces
  hi typescriptGlobalObjects guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi typescriptLogicSymbols guifg=#d8bbbd guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link typescriptOpSymbols Operator
  hi typescriptOperator guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi typescriptDomNodeConsts guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link dartCoreClasses Function
  hi dartTypedef guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dartOperator guifg=#bcbfb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dartKeyword guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dartCoreClasses guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dartInterpolation guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link coffeeParen Delimiter
  hi! link coffeeCurly Delimiter
  hi! link coffeeBracket Delimiter
  hi coffeeCurlies guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi coffeeSpecialOp guifg=#d8bbbd guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi coffeeExtendedOp guifg=#bcbfb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi coffeeParens guifg=#fdd89a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi coffeeConstant guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi coffeeObjAssign guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi coffeeInterpDelim guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi purescriptModuleName guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi purescriptModuleParams guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi purescriptOperatorTypeSig guifg=#d8bbbd guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi javaScopeDecl guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi javaLabel guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi javaVarArg guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link javaParen Delimiter
  hi javaAnnotation guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ktAnnotation guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ktStructure guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ktKeyword guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ktArrow guifg=#d8bbbd guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pythonExClass guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pythonBoolean guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pythonOperator guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pythonClassVar guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pythonDecorator guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link pythonStatement Keyword
  hi pythonBuiltinFunc guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pythonDottedName guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi goDeclaration guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi goImport guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi goPackage guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi goStatement guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi goPredefinedIdentifiers guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link goUnsignedInts Function
  hi rustKeyword guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link rustDynKeyword Keyword
  hi! link rustExistential Keyword
  hi! link rustSuper Keyword
  hi! link rustExternCrate Keyword
  hi rustSelf guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustSigil guifg=#bcbfb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustEnum guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustModPath guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link rustOperator Delimiter
  hi rustAttribute guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustDerive guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustMacroVariable guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustPubScopeCrate guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustStructure guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustStorage guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link phpParent Delimiter
  hi! link phpFunction Function
  hi phpMethod guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpInclude guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpKeyword guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpClass guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpClassNamespaceSeparator guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpStaticClasses guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpIdentifier guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpIdentifierSimply guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpVarSelector guifg=#bcbfb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link phpMemberSelector Delimiter
  hi! link phpOperator Delimiter
  hi! link csBraces Delimiter
  hi! link csParens Delimiter
  hi csUnspecifiedStatement guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csContextualStatement guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csNew guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csNewType guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csClass guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csEndColon guifg=#fdd89a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csLogicSymbols guifg=#d8bbbd guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link csXmlComment SpecialComment
  hi! link csXmlCommentLeader SpecialComment
  hi fsharpKeyword guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fsharpModifier guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fsharpModule guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fsharpSymbol guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fsharpKeychar guifg=#bcbfb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fsharpOperator guifg=#bcbfb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fsharpOption guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fsharpCoreClass guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fsharpAttribute guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fsharpAttrib guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi swiftKeywords guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi swiftMethod guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi swiftProperty guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyInclude guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyControl guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyDocumentation guifg=#83986f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyPredefinedVariable guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyConstant guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyPseudoVariable guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyInstanceVariable guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyModule guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyModuleName guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyClass guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyClassName guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyDefine guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyMethodName guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyCapitalizedMethod guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link rubySymbol Identifier
  hi rubyExceptionHandler2 guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlPackageDecl guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementPackage guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementInclude guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementStorage guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementInclude guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementFiledesc guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementScalar guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementList guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementFiles guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementSocket guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementFlow guifg=#d8bbbd guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementTime guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementRegexp guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link perlStringStartEnd Delimiter
  hi perlOperator guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlFunction guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlMethod guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlVarSimpleMemberName guifg=#fdd89a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi haskellImportKeywords guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi haskellType guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi haskellWhere guifg=#bcbfb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi haskellOperators guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link haskellDeclKeyword Type
  hi haskellDecl guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link luaBraces Delimiter
  hi luaFuncKeyword guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi luaFuncArgName guifg=#fdd89a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi luaLocal guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link luaSpecialValue Special
  hi! link luaFuncCall Function
  hi moonKeyword guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link moonFunction Delimiter
  hi moonSpecialVar guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi moonInterpDelim guifg=#d8bbbd guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi moonLuaFunc guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi moonSpecialOp guifg=#d8bbbd guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dTypedef guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dScopeDecl guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dLabel guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dOperator guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dAnnotation guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dEnum guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dStructure guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dStorageClass guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dUserLabel guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi scalaInstanceDeclaration guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi scalaCapitalWord guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi scalaAnnotation guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link scalaSpecial Special
  hi scalaKeywordModifier guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link scalaSquareBracketsBrackets Delimiter
  hi elixirAtom guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi elixirInclude guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi elixirAlias guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi elixirOperator guifg=#bcbfb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi elixirDefine guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi elixirPrivateDefine guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi elixirVariable guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi elixirModuleDeclaration guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi elixirKeyword guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ocamlModule guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ocamlModPath guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ocamlFullMod guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ocamlKeyword guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link ocamlArrow Delimiter
  hi! link ocamlEqual Operator
  hi! link ocamlModPreRHS Operator
  hi ocamlKeyChar guifg=#bcbfb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ocamlConstructor guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ocamlStructEncl guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ocamlPpxEncl guifg=#d8bbbd guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fortranCall guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fortranUnitHeader guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fortranKeyword guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fortranReadWrite guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fortranIO guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi clojureKeyword guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi clojureSpecial guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi clojureFunc guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi clojureDispatch guifg=#d8bbbd guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi clojureAnonArg guifg=#bcbfb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi erlangAttribute guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi erlangLocalFuncCall guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi erlangLocalFuncRef guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi erlangGlobalFuncCall guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi erlangType guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi erlangMap guifg=#d8bbbd guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi erlangRecord guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi erlangVariable guifg=#fdd89a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi erlangAtom guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi juliaBlKeyword guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi lispFunc guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi lispDecl guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi lispVar guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi shQuote guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi shDeref guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi shDerefSimple guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi shDerefVar guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi shVariable guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi shOperator guifg=#bcbfb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi shFunction guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link shCmdSubRegion Delimiter
  hi shCommandSub guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi shStatement guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi zshPreProc guifg=#83986f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi zshDeref guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi zshSubst guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link zshSubstDelim Delimiter
  hi zshOption guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi zshTypes guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link zshKeyword Keyword
  hi zshCommands guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi zshShortDeref guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi zshDollarVar guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi zshFunction guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fishKeyword guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fishStatement guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fishIdentifier guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimLet guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimCommand guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimOption guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimNotFunc guifg=#bcbfb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimFunction guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimFuncName guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimMap guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimMapModKey guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsonKeyword guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsonQuote guifg=#fdd89a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsonBoolean guifg=#fdd89a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi yamlKey guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi yamlConstant guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi tomlTable guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi tomlTableArray guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi tomlKey guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi gitconfigSection guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi gitcommitBlank guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi diffAdded guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi diffRemoved guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi diffChanged guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi diffOldFile guifg=#bcbfb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi diffNewFile guifg=#d8bbbd guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi diffFile guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link diffLine Comment
  hi diffIndexLine guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi diffSubname guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi helpHyperTextEntry guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi helpHyperTextJump guifg=#bcbfb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link helpSectionDelim Comment
  hi helpHeadline guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi helpURL guifg=#bcbfb4 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi helpExample guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi helpCommand guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi helpHeader guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEWarningSign guifg=#ed9c6a guibg=#606357 guisp=NONE gui=NONE cterm=NONE
  hi ALEErrorSign guifg=#fc796b guibg=#606357 guisp=NONE gui=NONE cterm=NONE
  hi ALEInfoSign guifg=#bcbfb4 guibg=#606357 guisp=NONE gui=NONE cterm=NONE
  hi ALEError guifg=NONE guibg=#6f4246 guisp=NONE gui=NONE cterm=NONE
  hi ALEWarning guifg=NONE guibg=#613d13 guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextError guifg=#7e837c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextWarning guifg=#7e837c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextInfo guifg=#7e837c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link ALEVirtualTextStyleError ALEVirtualTextError
  hi! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
  hi CocHighlightText guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocCodeLens guifg=#7e837c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link CocErrorSign ALEErrorSign
  hi! link CocWarningSign ALEWarningSign
  hi! link CocInfoSign ALEInfoSign
  hi! link CocHintSign Label
  hi! link CocErrorHighlight ALEError
  hi! link CocWarningHighlight ALEWarning
  hi! link CocInfoHighlight ALEInfo
  hi! link CocWarningVirtualText ALEVirtualTextWarning
  hi! link CocErrorVirtualText ALEVirtualTextError
  hi! link CocInfoVirtualText ALEVirtualTextInfo
  hi! link CocHintVirtualText ALEVirtualTextInfo
  hi! link CocCodeLens ALEVirtualTextInfo
  hi NERDTreeFlags guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NERDTreeDirSlash guifg=#83986f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NERDTreeCWD guifg=#83986f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NERDTreeLinkFile guifg=#83986f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NERDTreeLinkTarget guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi TagbarKind guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi TagbarVisibilityPublic guifg=#bcbfb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi TagbarVisibilityPrivate guifg=#d8bbbd guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi TagbarNestedKind guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi TagbarSignature guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi TagbarPseudoID guifg=#d8bbbd guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MatchParenCur guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi StartifyBracket guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifyHeader guifg=#fc796b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifyNumber guifg=#edc074 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifyPath guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifySlash guifg=#83986f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifySection guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link StartifySpecial Comment
  hi! link StartifyFile Normal
  hi Sneak guifg=NONE guibg=#536049 guisp=NONE gui=NONE cterm=NONE
  hi gvSha guifg=#a8cb79 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi gvAuthor guifg=#ed9c6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  if !s:italics
    hi Folded gui=NONE cterm=NONE
    hi VisualNOS gui=NONE cterm=NONE
    hi Todo gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
    hi SpecialComment gui=NONE cterm=NONE
    hi markdownItalic gui=NONE cterm=NONE
    hi htmlItalic gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'forest_night_transp_bg', 0)
    hi Normal ctermfg=223 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=223 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=223 ctermbg=239 cterm=NONE
    if !has('patch-8.0.0616') " Fix for Vim bug
      set background=dark
    endif
    hi Terminal ctermfg=223 ctermbg=239 cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=238 cterm=NONE
  hi Conceal ctermfg=245 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=235 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=235 cterm=NONE
  hi CursorLineNr ctermfg=245 ctermbg=244 cterm=NONE
  hi LineNr ctermfg=239 ctermbg=244 cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=244 cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=65 cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=136 cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=95 cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=67 cterm=NONE
  hi Directory ctermfg=150 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=238 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=210 ctermbg=244 cterm=NONE
  hi WarningMsg ctermfg=216 ctermbg=244 cterm=NONE
  hi ModeMsg ctermfg=239 ctermbg=150 cterm=NONE
  hi MoreMsg ctermfg=223 ctermbg=244 cterm=NONE
  hi FoldColumn ctermfg=223 ctermbg=244 cterm=NONE
  hi Folded ctermfg=223 ctermbg=244 cterm=italic
  hi IncSearch ctermfg=NONE ctermbg=95 cterm=underline
  hi Search ctermfg=NONE ctermbg=95 cterm=underline
  hi NonText ctermfg=245 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=223 ctermbg=244 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=244 cterm=NONE
  hi PmenuSel ctermfg=223 ctermbg=244 cterm=reverse
  hi PmenuThumb ctermfg=NONE ctermbg=223 cterm=NONE
  hi Question ctermfg=153 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=238 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=210 ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=216 ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=153 ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=189 ctermbg=NONE cterm=NONE
  hi TabLine ctermfg=223 ctermbg=244 cterm=NONE
  hi TabLineFill ctermfg=223 ctermbg=235 cterm=NONE
  hi TabLineSel ctermfg=235 ctermbg=150 cterm=NONE
  hi StatusLine ctermfg=223 ctermbg=244 cterm=NONE
  hi StatusLineNC ctermfg=223 ctermbg=235 cterm=NONE
  hi WildMenu ctermfg=235 ctermbg=223 cterm=NONE
  hi VertSplit ctermfg=244 ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=95 cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=95 cterm=italic
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi Todo ctermfg=189 ctermbg=NONE cterm=italic
  hi PreProc ctermfg=210 ctermbg=NONE cterm=NONE
  hi Define ctermfg=210 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=210 ctermbg=NONE cterm=NONE
  hi Exception ctermfg=210 ctermbg=NONE cterm=NONE
  hi Error ctermfg=210 ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=216 ctermbg=NONE cterm=NONE
  hi Title ctermfg=216 ctermbg=NONE cterm=NONE
  hi Function ctermfg=216 ctermbg=NONE cterm=NONE
  hi Label ctermfg=216 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=216 ctermbg=NONE cterm=NONE
  hi Type ctermfg=222 ctermbg=NONE cterm=NONE
  hi Special ctermfg=222 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=222 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=150 ctermbg=NONE cterm=NONE
  hi String ctermfg=150 ctermbg=NONE cterm=NONE
  hi Character ctermfg=150 ctermbg=NONE cterm=NONE
  hi Number ctermfg=150 ctermbg=NONE cterm=NONE
  hi Float ctermfg=150 ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=150 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=153 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=153 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=153 ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=189 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=189 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=245 ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=65 ctermbg=NONE cterm=italic
  hi Ignore ctermfg=245 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=223 ctermbg=244 cterm=NONE
  hi ToolbarButton ctermfg=239 ctermbg=223 cterm=bold
  hi Noise ctermfg=223 ctermbg=NONE cterm=NONE
  hi markdownLinkText ctermfg=222 ctermbg=NONE cterm=NONE
  hi markdownUrl ctermfg=150 ctermbg=NONE cterm=underline
  hi markdownListMarker ctermfg=153 ctermbg=NONE cterm=NONE
  hi markdownCode ctermfg=150 ctermbg=NONE cterm=NONE
  hi markdownId ctermfg=216 ctermbg=NONE cterm=NONE
  hi markdownIdDeclaration ctermfg=216 ctermbg=NONE cterm=NONE
  hi! link markdownBoldDelimiter Comment
  hi! link markdownItalicDelimiter Comment
  hi markdownBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi markdownRule ctermfg=189 ctermbg=NONE cterm=NONE
  hi mkdListItem ctermfg=153 ctermbg=NONE cterm=NONE
  hi mkdInlineURL ctermfg=222 ctermbg=NONE cterm=underline
  hi mkdLink ctermfg=222 ctermbg=NONE cterm=NONE
  hi mkdURL ctermfg=150 ctermbg=NONE cterm=underline
  hi! link mkdCodeDelimiter Delimiter
  hi mkdID ctermfg=216 ctermbg=NONE cterm=NONE
  hi! link mkdBold Comment
  hi! link mkdItalic Comment
  hi mkdRule ctermfg=189 ctermbg=NONE cterm=NONE
  hi rstSections ctermfg=210 ctermbg=NONE cterm=NONE
  hi rstDirective ctermfg=216 ctermbg=NONE cterm=NONE
  hi rstExplicitMarkup ctermfg=153 ctermbg=NONE cterm=NONE
  hi rstStandaloneHyperlink ctermfg=150 ctermbg=NONE cterm=underline
  hi texStatement ctermfg=150 ctermbg=NONE cterm=NONE
  hi texBeginEnd ctermfg=216 ctermbg=NONE cterm=NONE
  hi texDefCmd ctermfg=216 ctermbg=NONE cterm=NONE
  hi texDefName ctermfg=222 ctermbg=NONE cterm=NONE
  hi texSection ctermfg=210 ctermbg=NONE cterm=NONE
  hi texDocType ctermfg=216 ctermbg=NONE cterm=NONE
  hi texOnlyMath ctermfg=189 ctermbg=NONE cterm=NONE
  hi texNewCmd ctermfg=210 ctermbg=NONE cterm=NONE
  hi texCmdName ctermfg=216 ctermbg=NONE cterm=NONE
  hi htmlStatement ctermfg=216 ctermbg=NONE cterm=NONE
  hi htmlTag ctermfg=150 ctermbg=NONE cterm=NONE
  hi htmlLink ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi xmlTag ctermfg=150 ctermbg=NONE cterm=NONE
  hi xmlTagName ctermfg=216 ctermbg=NONE cterm=NONE
  hi xmlEndTag ctermfg=153 ctermbg=NONE cterm=NONE
  hi cssClassName ctermfg=216 ctermbg=NONE cterm=NONE
  hi! link cssClassNameDot cssClassName
  hi cssProp ctermfg=223 ctermbg=NONE cterm=NONE
  hi! link cssBraces Delimiter
  hi! link cssSelectorOp Delimiter
  hi! link cssSelectorOp2 Delimiter
  hi cssAtRule ctermfg=210 ctermbg=NONE cterm=NONE
  hi cssTagName ctermfg=216 ctermbg=NONE cterm=NONE
  hi cssAttrComma ctermfg=223 ctermbg=NONE cterm=NONE
  hi cssUnitDecorators ctermfg=153 ctermbg=NONE cterm=NONE
  hi cssColor ctermfg=223 ctermbg=NONE cterm=NONE
  hi cssImportant ctermfg=210 ctermbg=NONE cterm=NONE
  hi! link sassVariable Identifier
  hi sassClass ctermfg=216 ctermbg=NONE cterm=NONE
  hi sassClassChar ctermfg=216 ctermbg=NONE cterm=NONE
  hi sassCharset ctermfg=150 ctermbg=NONE cterm=NONE
  hi sassInclude ctermfg=210 ctermbg=NONE cterm=NONE
  hi scssSelectorName ctermfg=216 ctermbg=NONE cterm=NONE
  hi! link scssSelectorChar scssSelectorName
  hi! link lessVariable Identifier
  hi lessClass ctermfg=216 ctermbg=NONE cterm=NONE
  hi! link javaScriptBraces Delimiter
  hi javaScriptOperator ctermfg=216 ctermbg=NONE cterm=NONE
  hi javaScriptNull ctermfg=222 ctermbg=NONE cterm=NONE
  hi javaScriptGlobal ctermfg=210 ctermbg=NONE cterm=NONE
  hi javaScriptMessage ctermfg=153 ctermbg=NONE cterm=NONE
  hi javaScriptMember ctermfg=222 ctermbg=NONE cterm=NONE
  hi jsGlobalNodeObjects ctermfg=210 ctermbg=NONE cterm=NONE
  hi! link jsFunction Keyword
  hi! link jsParens Delimiter
  hi! link jsBraces Delimiter
  hi! link jsBrackets Delimiter
  hi! link jsFuncBraces Delimiter
  hi! link jsFuncParens Delimiter
  hi! link jsObjectBraces Delimiter
  hi! link jsObjectParens Delimiter
  hi! link jsExceptions Exception
  hi jsObjectValue ctermfg=150 ctermbg=NONE cterm=NONE
  hi jsObjectProp ctermfg=222 ctermbg=NONE cterm=NONE
  hi jsBlockLabel ctermfg=222 ctermbg=NONE cterm=NONE
  hi jsOperatorKeyword ctermfg=216 ctermbg=NONE cterm=NONE
  hi jsGlobalObjects ctermfg=216 ctermbg=NONE cterm=NONE
  hi jsUndefined ctermfg=222 ctermbg=NONE cterm=NONE
  hi jsThis ctermfg=216 ctermbg=NONE cterm=NONE
  hi jsArrowFunction ctermfg=153 ctermbg=NONE cterm=NONE
  hi typescriptBranch ctermfg=216 ctermbg=NONE cterm=NONE
  hi! link typescriptExceptions Exception
  hi! link typescriptParens Delimiter
  hi! link typescriptBraces Delimiter
  hi! link typescriptEndColons typescriptBraces
  hi typescriptGlobalObjects ctermfg=216 ctermbg=NONE cterm=NONE
  hi typescriptLogicSymbols ctermfg=189 ctermbg=NONE cterm=NONE
  hi! link typescriptOpSymbols Operator
  hi typescriptOperator ctermfg=216 ctermbg=NONE cterm=NONE
  hi typescriptDomNodeConsts ctermfg=216 ctermbg=NONE cterm=NONE
  hi! link dartCoreClasses Function
  hi dartTypedef ctermfg=216 ctermbg=NONE cterm=NONE
  hi dartOperator ctermfg=153 ctermbg=NONE cterm=NONE
  hi dartKeyword ctermfg=210 ctermbg=NONE cterm=NONE
  hi dartCoreClasses ctermfg=222 ctermbg=NONE cterm=NONE
  hi dartInterpolation ctermfg=216 ctermbg=NONE cterm=NONE
  hi! link coffeeParen Delimiter
  hi! link coffeeCurly Delimiter
  hi! link coffeeBracket Delimiter
  hi coffeeCurlies ctermfg=150 ctermbg=NONE cterm=NONE
  hi coffeeSpecialOp ctermfg=189 ctermbg=NONE cterm=NONE
  hi coffeeExtendedOp ctermfg=153 ctermbg=NONE cterm=NONE
  hi coffeeParens ctermfg=223 ctermbg=NONE cterm=NONE
  hi coffeeConstant ctermfg=216 ctermbg=NONE cterm=NONE
  hi coffeeObjAssign ctermfg=216 ctermbg=NONE cterm=NONE
  hi coffeeInterpDelim ctermfg=150 ctermbg=NONE cterm=NONE
  hi purescriptModuleName ctermfg=216 ctermbg=NONE cterm=NONE
  hi purescriptModuleParams ctermfg=150 ctermbg=NONE cterm=NONE
  hi purescriptOperatorTypeSig ctermfg=189 ctermbg=NONE cterm=NONE
  hi javaScopeDecl ctermfg=210 ctermbg=NONE cterm=NONE
  hi javaLabel ctermfg=216 ctermbg=NONE cterm=NONE
  hi javaVarArg ctermfg=150 ctermbg=NONE cterm=NONE
  hi! link javaParen Delimiter
  hi javaAnnotation ctermfg=216 ctermbg=NONE cterm=NONE
  hi ktAnnotation ctermfg=216 ctermbg=NONE cterm=NONE
  hi ktStructure ctermfg=210 ctermbg=NONE cterm=NONE
  hi ktKeyword ctermfg=150 ctermbg=NONE cterm=NONE
  hi ktArrow ctermfg=189 ctermbg=NONE cterm=NONE
  hi pythonExClass ctermfg=222 ctermbg=NONE cterm=NONE
  hi pythonBoolean ctermfg=150 ctermbg=NONE cterm=NONE
  hi pythonOperator ctermfg=150 ctermbg=NONE cterm=NONE
  hi pythonClassVar ctermfg=222 ctermbg=NONE cterm=NONE
  hi pythonDecorator ctermfg=210 ctermbg=NONE cterm=NONE
  hi! link pythonStatement Keyword
  hi pythonBuiltinFunc ctermfg=222 ctermbg=NONE cterm=NONE
  hi pythonDottedName ctermfg=216 ctermbg=NONE cterm=NONE
  hi goDeclaration ctermfg=216 ctermbg=NONE cterm=NONE
  hi goImport ctermfg=216 ctermbg=NONE cterm=NONE
  hi goPackage ctermfg=210 ctermbg=NONE cterm=NONE
  hi goStatement ctermfg=150 ctermbg=NONE cterm=NONE
  hi goPredefinedIdentifiers ctermfg=222 ctermbg=NONE cterm=NONE
  hi! link goUnsignedInts Function
  hi rustKeyword ctermfg=150 ctermbg=NONE cterm=NONE
  hi! link rustDynKeyword Keyword
  hi! link rustExistential Keyword
  hi! link rustSuper Keyword
  hi! link rustExternCrate Keyword
  hi rustSelf ctermfg=222 ctermbg=NONE cterm=NONE
  hi rustSigil ctermfg=153 ctermbg=NONE cterm=NONE
  hi rustEnum ctermfg=216 ctermbg=NONE cterm=NONE
  hi rustModPath ctermfg=216 ctermbg=NONE cterm=NONE
  hi! link rustOperator Delimiter
  hi rustAttribute ctermfg=210 ctermbg=NONE cterm=NONE
  hi rustDerive ctermfg=216 ctermbg=NONE cterm=NONE
  hi rustMacroVariable ctermfg=216 ctermbg=NONE cterm=NONE
  hi rustPubScopeCrate ctermfg=216 ctermbg=NONE cterm=NONE
  hi rustStructure ctermfg=216 ctermbg=NONE cterm=NONE
  hi rustStorage ctermfg=210 ctermbg=NONE cterm=NONE
  hi! link phpParent Delimiter
  hi! link phpFunction Function
  hi phpMethod ctermfg=216 ctermbg=NONE cterm=NONE
  hi phpInclude ctermfg=216 ctermbg=NONE cterm=NONE
  hi phpKeyword ctermfg=210 ctermbg=NONE cterm=NONE
  hi phpClass ctermfg=216 ctermbg=NONE cterm=NONE
  hi phpClassNamespaceSeparator ctermfg=222 ctermbg=NONE cterm=NONE
  hi phpStaticClasses ctermfg=222 ctermbg=NONE cterm=NONE
  hi phpIdentifier ctermfg=150 ctermbg=NONE cterm=NONE
  hi phpIdentifierSimply ctermfg=216 ctermbg=NONE cterm=NONE
  hi phpVarSelector ctermfg=153 ctermbg=NONE cterm=NONE
  hi! link phpMemberSelector Delimiter
  hi! link phpOperator Delimiter
  hi! link csBraces Delimiter
  hi! link csParens Delimiter
  hi csUnspecifiedStatement ctermfg=216 ctermbg=NONE cterm=NONE
  hi csContextualStatement ctermfg=150 ctermbg=NONE cterm=NONE
  hi csNew ctermfg=216 ctermbg=NONE cterm=NONE
  hi csNewType ctermfg=222 ctermbg=NONE cterm=NONE
  hi csClass ctermfg=210 ctermbg=NONE cterm=NONE
  hi csEndColon ctermfg=223 ctermbg=NONE cterm=NONE
  hi csLogicSymbols ctermfg=189 ctermbg=NONE cterm=NONE
  hi! link csXmlComment SpecialComment
  hi! link csXmlCommentLeader SpecialComment
  hi fsharpKeyword ctermfg=216 ctermbg=NONE cterm=NONE
  hi fsharpModifier ctermfg=210 ctermbg=NONE cterm=NONE
  hi fsharpModule ctermfg=216 ctermbg=NONE cterm=NONE
  hi fsharpSymbol ctermfg=150 ctermbg=NONE cterm=NONE
  hi fsharpKeychar ctermfg=153 ctermbg=NONE cterm=NONE
  hi fsharpOperator ctermfg=153 ctermbg=NONE cterm=NONE
  hi fsharpOption ctermfg=222 ctermbg=NONE cterm=NONE
  hi fsharpCoreClass ctermfg=222 ctermbg=NONE cterm=NONE
  hi fsharpAttribute ctermfg=216 ctermbg=NONE cterm=NONE
  hi fsharpAttrib ctermfg=210 ctermbg=NONE cterm=NONE
  hi swiftKeywords ctermfg=216 ctermbg=NONE cterm=NONE
  hi swiftMethod ctermfg=210 ctermbg=NONE cterm=NONE
  hi swiftProperty ctermfg=150 ctermbg=NONE cterm=NONE
  hi rubyInclude ctermfg=210 ctermbg=NONE cterm=NONE
  hi rubyControl ctermfg=210 ctermbg=NONE cterm=NONE
  hi rubyDocumentation ctermfg=65 ctermbg=NONE cterm=NONE
  hi rubyPredefinedVariable ctermfg=150 ctermbg=NONE cterm=NONE
  hi rubyConstant ctermfg=216 ctermbg=NONE cterm=NONE
  hi rubyPseudoVariable ctermfg=216 ctermbg=NONE cterm=NONE
  hi rubyInstanceVariable ctermfg=222 ctermbg=NONE cterm=NONE
  hi rubyModule ctermfg=210 ctermbg=NONE cterm=NONE
  hi rubyModuleName ctermfg=216 ctermbg=NONE cterm=NONE
  hi rubyClass ctermfg=210 ctermbg=NONE cterm=NONE
  hi rubyClassName ctermfg=216 ctermbg=NONE cterm=NONE
  hi rubyDefine ctermfg=216 ctermbg=NONE cterm=NONE
  hi rubyMethodName ctermfg=222 ctermbg=NONE cterm=NONE
  hi rubyCapitalizedMethod ctermfg=216 ctermbg=NONE cterm=NONE
  hi! link rubySymbol Identifier
  hi rubyExceptionHandler2 ctermfg=210 ctermbg=NONE cterm=NONE
  hi perlPackageDecl ctermfg=216 ctermbg=NONE cterm=NONE
  hi perlStatementPackage ctermfg=210 ctermbg=NONE cterm=NONE
  hi perlStatementInclude ctermfg=216 ctermbg=NONE cterm=NONE
  hi perlStatementStorage ctermfg=210 ctermbg=NONE cterm=NONE
  hi perlStatementInclude ctermfg=210 ctermbg=NONE cterm=NONE
  hi perlStatementFiledesc ctermfg=216 ctermbg=NONE cterm=NONE
  hi perlStatementScalar ctermfg=216 ctermbg=NONE cterm=NONE
  hi perlStatementList ctermfg=222 ctermbg=NONE cterm=NONE
  hi perlStatementFiles ctermfg=216 ctermbg=NONE cterm=NONE
  hi perlStatementSocket ctermfg=210 ctermbg=NONE cterm=NONE
  hi perlStatementFlow ctermfg=189 ctermbg=NONE cterm=NONE
  hi perlStatementTime ctermfg=222 ctermbg=NONE cterm=NONE
  hi perlStatementRegexp ctermfg=216 ctermbg=NONE cterm=NONE
  hi! link perlStringStartEnd Delimiter
  hi perlOperator ctermfg=222 ctermbg=NONE cterm=NONE
  hi perlFunction ctermfg=210 ctermbg=NONE cterm=NONE
  hi perlMethod ctermfg=216 ctermbg=NONE cterm=NONE
  hi perlVarSimpleMemberName ctermfg=223 ctermbg=NONE cterm=NONE
  hi haskellImportKeywords ctermfg=210 ctermbg=NONE cterm=NONE
  hi haskellType ctermfg=216 ctermbg=NONE cterm=NONE
  hi haskellWhere ctermfg=153 ctermbg=NONE cterm=NONE
  hi haskellOperators ctermfg=150 ctermbg=NONE cterm=NONE
  hi! link haskellDeclKeyword Type
  hi haskellDecl ctermfg=210 ctermbg=NONE cterm=NONE
  hi! link luaBraces Delimiter
  hi luaFuncKeyword ctermfg=210 ctermbg=NONE cterm=NONE
  hi luaFuncArgName ctermfg=223 ctermbg=NONE cterm=NONE
  hi luaLocal ctermfg=216 ctermbg=NONE cterm=NONE
  hi! link luaSpecialValue Special
  hi! link luaFuncCall Function
  hi moonKeyword ctermfg=210 ctermbg=NONE cterm=NONE
  hi! link moonFunction Delimiter
  hi moonSpecialVar ctermfg=216 ctermbg=NONE cterm=NONE
  hi moonInterpDelim ctermfg=189 ctermbg=NONE cterm=NONE
  hi moonLuaFunc ctermfg=216 ctermbg=NONE cterm=NONE
  hi moonSpecialOp ctermfg=189 ctermbg=NONE cterm=NONE
  hi dTypedef ctermfg=216 ctermbg=NONE cterm=NONE
  hi dScopeDecl ctermfg=210 ctermbg=NONE cterm=NONE
  hi dLabel ctermfg=222 ctermbg=NONE cterm=NONE
  hi dOperator ctermfg=150 ctermbg=NONE cterm=NONE
  hi dAnnotation ctermfg=222 ctermbg=NONE cterm=NONE
  hi dEnum ctermfg=216 ctermbg=NONE cterm=NONE
  hi dStructure ctermfg=216 ctermbg=NONE cterm=NONE
  hi dStorageClass ctermfg=216 ctermbg=NONE cterm=NONE
  hi dUserLabel ctermfg=210 ctermbg=NONE cterm=NONE
  hi scalaInstanceDeclaration ctermfg=150 ctermbg=NONE cterm=NONE
  hi scalaCapitalWord ctermfg=150 ctermbg=NONE cterm=NONE
  hi scalaAnnotation ctermfg=210 ctermbg=NONE cterm=NONE
  hi! link scalaSpecial Special
  hi scalaKeywordModifier ctermfg=216 ctermbg=NONE cterm=NONE
  hi! link scalaSquareBracketsBrackets Delimiter
  hi elixirAtom ctermfg=150 ctermbg=NONE cterm=NONE
  hi elixirInclude ctermfg=216 ctermbg=NONE cterm=NONE
  hi elixirAlias ctermfg=222 ctermbg=NONE cterm=NONE
  hi elixirOperator ctermfg=153 ctermbg=NONE cterm=NONE
  hi elixirDefine ctermfg=210 ctermbg=NONE cterm=NONE
  hi elixirPrivateDefine ctermfg=210 ctermbg=NONE cterm=NONE
  hi elixirVariable ctermfg=216 ctermbg=NONE cterm=NONE
  hi elixirModuleDeclaration ctermfg=216 ctermbg=NONE cterm=NONE
  hi elixirKeyword ctermfg=216 ctermbg=NONE cterm=NONE
  hi ocamlModule ctermfg=222 ctermbg=NONE cterm=NONE
  hi ocamlModPath ctermfg=150 ctermbg=NONE cterm=NONE
  hi ocamlFullMod ctermfg=222 ctermbg=NONE cterm=NONE
  hi ocamlKeyword ctermfg=216 ctermbg=NONE cterm=NONE
  hi! link ocamlArrow Delimiter
  hi! link ocamlEqual Operator
  hi! link ocamlModPreRHS Operator
  hi ocamlKeyChar ctermfg=153 ctermbg=NONE cterm=NONE
  hi ocamlConstructor ctermfg=150 ctermbg=NONE cterm=NONE
  hi ocamlStructEncl ctermfg=210 ctermbg=NONE cterm=NONE
  hi ocamlPpxEncl ctermfg=189 ctermbg=NONE cterm=NONE
  hi fortranCall ctermfg=210 ctermbg=NONE cterm=NONE
  hi fortranUnitHeader ctermfg=210 ctermbg=NONE cterm=NONE
  hi fortranKeyword ctermfg=216 ctermbg=NONE cterm=NONE
  hi fortranReadWrite ctermfg=216 ctermbg=NONE cterm=NONE
  hi fortranIO ctermfg=222 ctermbg=NONE cterm=NONE
  hi clojureKeyword ctermfg=216 ctermbg=NONE cterm=NONE
  hi clojureSpecial ctermfg=216 ctermbg=NONE cterm=NONE
  hi clojureFunc ctermfg=222 ctermbg=NONE cterm=NONE
  hi clojureDispatch ctermfg=189 ctermbg=NONE cterm=NONE
  hi clojureAnonArg ctermfg=153 ctermbg=NONE cterm=NONE
  hi erlangAttribute ctermfg=210 ctermbg=NONE cterm=NONE
  hi erlangLocalFuncCall ctermfg=216 ctermbg=NONE cterm=NONE
  hi erlangLocalFuncRef ctermfg=222 ctermbg=NONE cterm=NONE
  hi erlangGlobalFuncCall ctermfg=222 ctermbg=NONE cterm=NONE
  hi erlangType ctermfg=210 ctermbg=NONE cterm=NONE
  hi erlangMap ctermfg=189 ctermbg=NONE cterm=NONE
  hi erlangRecord ctermfg=216 ctermbg=NONE cterm=NONE
  hi erlangVariable ctermfg=223 ctermbg=NONE cterm=NONE
  hi erlangAtom ctermfg=150 ctermbg=NONE cterm=NONE
  hi juliaBlKeyword ctermfg=216 ctermbg=NONE cterm=NONE
  hi lispFunc ctermfg=216 ctermbg=NONE cterm=NONE
  hi lispDecl ctermfg=210 ctermbg=NONE cterm=NONE
  hi lispVar ctermfg=222 ctermbg=NONE cterm=NONE
  hi shQuote ctermfg=150 ctermbg=NONE cterm=NONE
  hi shDeref ctermfg=222 ctermbg=NONE cterm=NONE
  hi shDerefSimple ctermfg=222 ctermbg=NONE cterm=NONE
  hi shDerefVar ctermfg=216 ctermbg=NONE cterm=NONE
  hi shVariable ctermfg=216 ctermbg=NONE cterm=NONE
  hi shOperator ctermfg=153 ctermbg=NONE cterm=NONE
  hi shFunction ctermfg=210 ctermbg=NONE cterm=NONE
  hi! link shCmdSubRegion Delimiter
  hi shCommandSub ctermfg=216 ctermbg=NONE cterm=NONE
  hi shStatement ctermfg=210 ctermbg=NONE cterm=NONE
  hi zshPreProc ctermfg=65 ctermbg=NONE cterm=NONE
  hi zshDeref ctermfg=222 ctermbg=NONE cterm=NONE
  hi zshSubst ctermfg=222 ctermbg=NONE cterm=NONE
  hi! link zshSubstDelim Delimiter
  hi zshOption ctermfg=216 ctermbg=NONE cterm=NONE
  hi zshTypes ctermfg=216 ctermbg=NONE cterm=NONE
  hi! link zshKeyword Keyword
  hi zshCommands ctermfg=216 ctermbg=NONE cterm=NONE
  hi zshShortDeref ctermfg=216 ctermbg=NONE cterm=NONE
  hi zshDollarVar ctermfg=216 ctermbg=NONE cterm=NONE
  hi zshFunction ctermfg=210 ctermbg=NONE cterm=NONE
  hi fishKeyword ctermfg=210 ctermbg=NONE cterm=NONE
  hi fishStatement ctermfg=216 ctermbg=NONE cterm=NONE
  hi fishIdentifier ctermfg=222 ctermbg=NONE cterm=NONE
  hi vimLet ctermfg=210 ctermbg=NONE cterm=NONE
  hi vimCommand ctermfg=216 ctermbg=NONE cterm=NONE
  hi vimOption ctermfg=222 ctermbg=NONE cterm=NONE
  hi vimNotFunc ctermfg=153 ctermbg=NONE cterm=NONE
  hi vimFunction ctermfg=222 ctermbg=NONE cterm=NONE
  hi vimFuncName ctermfg=222 ctermbg=NONE cterm=NONE
  hi vimMap ctermfg=210 ctermbg=NONE cterm=NONE
  hi vimMapModKey ctermfg=216 ctermbg=NONE cterm=NONE
  hi jsonKeyword ctermfg=216 ctermbg=NONE cterm=NONE
  hi jsonQuote ctermfg=223 ctermbg=NONE cterm=NONE
  hi jsonBoolean ctermfg=223 ctermbg=NONE cterm=NONE
  hi yamlKey ctermfg=216 ctermbg=NONE cterm=NONE
  hi yamlConstant ctermfg=150 ctermbg=NONE cterm=NONE
  hi tomlTable ctermfg=210 ctermbg=NONE cterm=NONE
  hi tomlTableArray ctermfg=210 ctermbg=NONE cterm=NONE
  hi tomlKey ctermfg=216 ctermbg=NONE cterm=NONE
  hi gitconfigSection ctermfg=216 ctermbg=NONE cterm=NONE
  hi gitcommitBlank ctermfg=216 ctermbg=NONE cterm=NONE
  hi diffAdded ctermfg=150 ctermbg=NONE cterm=NONE
  hi diffRemoved ctermfg=210 ctermbg=NONE cterm=NONE
  hi diffChanged ctermfg=216 ctermbg=NONE cterm=NONE
  hi diffOldFile ctermfg=153 ctermbg=NONE cterm=NONE
  hi diffNewFile ctermfg=189 ctermbg=NONE cterm=NONE
  hi diffFile ctermfg=150 ctermbg=NONE cterm=NONE
  hi! link diffLine Comment
  hi diffIndexLine ctermfg=222 ctermbg=NONE cterm=NONE
  hi diffSubname ctermfg=216 ctermbg=NONE cterm=NONE
  hi helpHyperTextEntry ctermfg=210 ctermbg=NONE cterm=NONE
  hi helpHyperTextJump ctermfg=153 ctermbg=NONE cterm=NONE
  hi! link helpSectionDelim Comment
  hi helpHeadline ctermfg=216 ctermbg=NONE cterm=NONE
  hi helpURL ctermfg=153 ctermbg=NONE cterm=underline
  hi helpExample ctermfg=150 ctermbg=NONE cterm=NONE
  hi helpCommand ctermfg=150 ctermbg=NONE cterm=NONE
  hi helpHeader ctermfg=216 ctermbg=NONE cterm=NONE
  hi ALEWarningSign ctermfg=216 ctermbg=244 cterm=NONE
  hi ALEErrorSign ctermfg=210 ctermbg=244 cterm=NONE
  hi ALEInfoSign ctermfg=153 ctermbg=244 cterm=NONE
  hi ALEError ctermfg=NONE ctermbg=95 cterm=NONE
  hi ALEWarning ctermfg=NONE ctermbg=136 cterm=NONE
  hi ALEVirtualTextError ctermfg=245 ctermbg=NONE cterm=NONE
  hi ALEVirtualTextWarning ctermfg=245 ctermbg=NONE cterm=NONE
  hi ALEVirtualTextInfo ctermfg=245 ctermbg=NONE cterm=NONE
  hi! link ALEVirtualTextStyleError ALEVirtualTextError
  hi! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
  hi CocHighlightText ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocCodeLens ctermfg=245 ctermbg=NONE cterm=NONE
  hi! link CocErrorSign ALEErrorSign
  hi! link CocWarningSign ALEWarningSign
  hi! link CocInfoSign ALEInfoSign
  hi! link CocHintSign Label
  hi! link CocErrorHighlight ALEError
  hi! link CocWarningHighlight ALEWarning
  hi! link CocInfoHighlight ALEInfo
  hi! link CocWarningVirtualText ALEVirtualTextWarning
  hi! link CocErrorVirtualText ALEVirtualTextError
  hi! link CocInfoVirtualText ALEVirtualTextInfo
  hi! link CocHintVirtualText ALEVirtualTextInfo
  hi! link CocCodeLens ALEVirtualTextInfo
  hi NERDTreeFlags ctermfg=216 ctermbg=NONE cterm=NONE
  hi NERDTreeDirSlash ctermfg=65 ctermbg=NONE cterm=NONE
  hi NERDTreeCWD ctermfg=65 ctermbg=NONE cterm=NONE
  hi NERDTreeLinkFile ctermfg=65 ctermbg=NONE cterm=NONE
  hi NERDTreeLinkTarget ctermfg=150 ctermbg=NONE cterm=NONE
  hi TagbarKind ctermfg=216 ctermbg=NONE cterm=NONE
  hi TagbarVisibilityPublic ctermfg=153 ctermbg=NONE cterm=NONE
  hi TagbarVisibilityPrivate ctermfg=189 ctermbg=NONE cterm=NONE
  hi TagbarNestedKind ctermfg=150 ctermbg=NONE cterm=NONE
  hi TagbarSignature ctermfg=150 ctermbg=NONE cterm=NONE
  hi TagbarPseudoID ctermfg=189 ctermbg=NONE cterm=NONE
  hi MatchParenCur ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur ctermfg=NONE ctermbg=NONE cterm=underline
  hi StartifyBracket ctermfg=150 ctermbg=NONE cterm=NONE
  hi StartifyHeader ctermfg=210 ctermbg=NONE cterm=NONE
  hi StartifyNumber ctermfg=222 ctermbg=NONE cterm=NONE
  hi StartifyPath ctermfg=150 ctermbg=NONE cterm=NONE
  hi StartifySlash ctermfg=65 ctermbg=NONE cterm=NONE
  hi StartifySection ctermfg=216 ctermbg=NONE cterm=NONE
  hi! link StartifySpecial Comment
  hi! link StartifyFile Normal
  hi Sneak ctermfg=NONE ctermbg=65 cterm=NONE
  hi gvSha ctermfg=150 ctermbg=NONE cterm=NONE
  hi gvAuthor ctermfg=216 ctermbg=NONE cterm=NONE
  if !s:italics
    hi Folded cterm=NONE
    hi VisualNOS cterm=NONE
    hi Todo cterm=NONE
    hi Comment cterm=NONE
    hi SpecialComment cterm=NONE
    hi markdownItalic cterm=NONE
    hi htmlItalic cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'forest_night_transp_bg', 0)
    hi Normal ctermfg=White ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=White ctermbg=Black cterm=NONE
    hi Terminal ctermfg=White ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=DarkGrey cterm=NONE
  hi Conceal ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=Black cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi CursorLineNr ctermfg=Grey ctermbg=Grey cterm=NONE
  hi LineNr ctermfg=Black ctermbg=Grey cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=Grey cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=DarkGreen cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=DarkYellow cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=DarkRed cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=DarkBlue cterm=NONE
  hi Directory ctermfg=Green ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=Red ctermbg=Grey cterm=NONE
  hi WarningMsg ctermfg=DarkYellow ctermbg=Grey cterm=NONE
  hi ModeMsg ctermfg=Black ctermbg=Green cterm=NONE
  hi MoreMsg ctermfg=White ctermbg=Grey cterm=NONE
  hi FoldColumn ctermfg=White ctermbg=Grey cterm=NONE
  hi Folded ctermfg=White ctermbg=Grey cterm=italic
  hi IncSearch ctermfg=NONE ctermbg=DarkRed cterm=underline
  hi Search ctermfg=NONE ctermbg=DarkRed cterm=underline
  hi NonText ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=White ctermbg=Grey cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=Grey cterm=NONE
  hi PmenuSel ctermfg=White ctermbg=Grey cterm=reverse
  hi PmenuThumb ctermfg=NONE ctermbg=White cterm=NONE
  hi Question ctermfg=Blue ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=Red ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=Blue ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi TabLine ctermfg=White ctermbg=Grey cterm=NONE
  hi TabLineFill ctermfg=White ctermbg=Black cterm=NONE
  hi TabLineSel ctermfg=Black ctermbg=Green cterm=NONE
  hi StatusLine ctermfg=White ctermbg=Grey cterm=NONE
  hi StatusLineNC ctermfg=White ctermbg=Black cterm=NONE
  hi WildMenu ctermfg=Black ctermbg=White cterm=NONE
  hi VertSplit ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=DarkRed cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=DarkRed cterm=italic
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi Todo ctermfg=Magenta ctermbg=NONE cterm=italic
  hi PreProc ctermfg=Red ctermbg=NONE cterm=NONE
  hi Define ctermfg=Red ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=Red ctermbg=NONE cterm=NONE
  hi Exception ctermfg=Red ctermbg=NONE cterm=NONE
  hi Error ctermfg=Red ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Title ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Function ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Label ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Type ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Special ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Constant ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=Green ctermbg=NONE cterm=NONE
  hi String ctermfg=Green ctermbg=NONE cterm=NONE
  hi Character ctermfg=Green ctermbg=NONE cterm=NONE
  hi Number ctermfg=Green ctermbg=NONE cterm=NONE
  hi Float ctermfg=Green ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=Green ctermbg=NONE cterm=NONE
  hi Statement ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Operator ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Tag ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Comment ctermfg=Grey ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=DarkGreen ctermbg=NONE cterm=italic
  hi Ignore ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=White ctermbg=Grey cterm=NONE
  hi ToolbarButton ctermfg=Black ctermbg=White cterm=bold
  hi Noise ctermfg=White ctermbg=NONE cterm=NONE
  hi markdownLinkText ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi markdownUrl ctermfg=Green ctermbg=NONE cterm=underline
  hi markdownListMarker ctermfg=Blue ctermbg=NONE cterm=NONE
  hi markdownCode ctermfg=Green ctermbg=NONE cterm=NONE
  hi markdownId ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi markdownIdDeclaration ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link markdownBoldDelimiter Comment
  hi! link markdownItalicDelimiter Comment
  hi markdownBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi markdownRule ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi mkdListItem ctermfg=Blue ctermbg=NONE cterm=NONE
  hi mkdInlineURL ctermfg=Yellow ctermbg=NONE cterm=underline
  hi mkdLink ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi mkdURL ctermfg=Green ctermbg=NONE cterm=underline
  hi! link mkdCodeDelimiter Delimiter
  hi mkdID ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link mkdBold Comment
  hi! link mkdItalic Comment
  hi mkdRule ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi rstSections ctermfg=Red ctermbg=NONE cterm=NONE
  hi rstDirective ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi rstExplicitMarkup ctermfg=Blue ctermbg=NONE cterm=NONE
  hi rstStandaloneHyperlink ctermfg=Green ctermbg=NONE cterm=underline
  hi texStatement ctermfg=Green ctermbg=NONE cterm=NONE
  hi texBeginEnd ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi texDefCmd ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi texDefName ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi texSection ctermfg=Red ctermbg=NONE cterm=NONE
  hi texDocType ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi texOnlyMath ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi texNewCmd ctermfg=Red ctermbg=NONE cterm=NONE
  hi texCmdName ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi htmlStatement ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi htmlTag ctermfg=Green ctermbg=NONE cterm=NONE
  hi htmlLink ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi xmlTag ctermfg=Green ctermbg=NONE cterm=NONE
  hi xmlTagName ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi xmlEndTag ctermfg=Blue ctermbg=NONE cterm=NONE
  hi cssClassName ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link cssClassNameDot cssClassName
  hi cssProp ctermfg=White ctermbg=NONE cterm=NONE
  hi! link cssBraces Delimiter
  hi! link cssSelectorOp Delimiter
  hi! link cssSelectorOp2 Delimiter
  hi cssAtRule ctermfg=Red ctermbg=NONE cterm=NONE
  hi cssTagName ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi cssAttrComma ctermfg=White ctermbg=NONE cterm=NONE
  hi cssUnitDecorators ctermfg=Blue ctermbg=NONE cterm=NONE
  hi cssColor ctermfg=White ctermbg=NONE cterm=NONE
  hi cssImportant ctermfg=Red ctermbg=NONE cterm=NONE
  hi! link sassVariable Identifier
  hi sassClass ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi sassClassChar ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi sassCharset ctermfg=Green ctermbg=NONE cterm=NONE
  hi sassInclude ctermfg=Red ctermbg=NONE cterm=NONE
  hi scssSelectorName ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link scssSelectorChar scssSelectorName
  hi! link lessVariable Identifier
  hi lessClass ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link javaScriptBraces Delimiter
  hi javaScriptOperator ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi javaScriptNull ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi javaScriptGlobal ctermfg=Red ctermbg=NONE cterm=NONE
  hi javaScriptMessage ctermfg=Blue ctermbg=NONE cterm=NONE
  hi javaScriptMember ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi jsGlobalNodeObjects ctermfg=Red ctermbg=NONE cterm=NONE
  hi! link jsFunction Keyword
  hi! link jsParens Delimiter
  hi! link jsBraces Delimiter
  hi! link jsBrackets Delimiter
  hi! link jsFuncBraces Delimiter
  hi! link jsFuncParens Delimiter
  hi! link jsObjectBraces Delimiter
  hi! link jsObjectParens Delimiter
  hi! link jsExceptions Exception
  hi jsObjectValue ctermfg=Green ctermbg=NONE cterm=NONE
  hi jsObjectProp ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi jsBlockLabel ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi jsOperatorKeyword ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi jsGlobalObjects ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi jsUndefined ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi jsThis ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi jsArrowFunction ctermfg=Blue ctermbg=NONE cterm=NONE
  hi typescriptBranch ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link typescriptExceptions Exception
  hi! link typescriptParens Delimiter
  hi! link typescriptBraces Delimiter
  hi! link typescriptEndColons typescriptBraces
  hi typescriptGlobalObjects ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi typescriptLogicSymbols ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi! link typescriptOpSymbols Operator
  hi typescriptOperator ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi typescriptDomNodeConsts ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link dartCoreClasses Function
  hi dartTypedef ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi dartOperator ctermfg=Blue ctermbg=NONE cterm=NONE
  hi dartKeyword ctermfg=Red ctermbg=NONE cterm=NONE
  hi dartCoreClasses ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi dartInterpolation ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link coffeeParen Delimiter
  hi! link coffeeCurly Delimiter
  hi! link coffeeBracket Delimiter
  hi coffeeCurlies ctermfg=Green ctermbg=NONE cterm=NONE
  hi coffeeSpecialOp ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi coffeeExtendedOp ctermfg=Blue ctermbg=NONE cterm=NONE
  hi coffeeParens ctermfg=White ctermbg=NONE cterm=NONE
  hi coffeeConstant ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi coffeeObjAssign ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi coffeeInterpDelim ctermfg=Green ctermbg=NONE cterm=NONE
  hi purescriptModuleName ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi purescriptModuleParams ctermfg=Green ctermbg=NONE cterm=NONE
  hi purescriptOperatorTypeSig ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi javaScopeDecl ctermfg=Red ctermbg=NONE cterm=NONE
  hi javaLabel ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi javaVarArg ctermfg=Green ctermbg=NONE cterm=NONE
  hi! link javaParen Delimiter
  hi javaAnnotation ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi ktAnnotation ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi ktStructure ctermfg=Red ctermbg=NONE cterm=NONE
  hi ktKeyword ctermfg=Green ctermbg=NONE cterm=NONE
  hi ktArrow ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi pythonExClass ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi pythonBoolean ctermfg=Green ctermbg=NONE cterm=NONE
  hi pythonOperator ctermfg=Green ctermbg=NONE cterm=NONE
  hi pythonClassVar ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi pythonDecorator ctermfg=Red ctermbg=NONE cterm=NONE
  hi! link pythonStatement Keyword
  hi pythonBuiltinFunc ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi pythonDottedName ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi goDeclaration ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi goImport ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi goPackage ctermfg=Red ctermbg=NONE cterm=NONE
  hi goStatement ctermfg=Green ctermbg=NONE cterm=NONE
  hi goPredefinedIdentifiers ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi! link goUnsignedInts Function
  hi rustKeyword ctermfg=Green ctermbg=NONE cterm=NONE
  hi! link rustDynKeyword Keyword
  hi! link rustExistential Keyword
  hi! link rustSuper Keyword
  hi! link rustExternCrate Keyword
  hi rustSelf ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi rustSigil ctermfg=Blue ctermbg=NONE cterm=NONE
  hi rustEnum ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi rustModPath ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link rustOperator Delimiter
  hi rustAttribute ctermfg=Red ctermbg=NONE cterm=NONE
  hi rustDerive ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi rustMacroVariable ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi rustPubScopeCrate ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi rustStructure ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi rustStorage ctermfg=Red ctermbg=NONE cterm=NONE
  hi! link phpParent Delimiter
  hi! link phpFunction Function
  hi phpMethod ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi phpInclude ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi phpKeyword ctermfg=Red ctermbg=NONE cterm=NONE
  hi phpClass ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi phpClassNamespaceSeparator ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi phpStaticClasses ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi phpIdentifier ctermfg=Green ctermbg=NONE cterm=NONE
  hi phpIdentifierSimply ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi phpVarSelector ctermfg=Blue ctermbg=NONE cterm=NONE
  hi! link phpMemberSelector Delimiter
  hi! link phpOperator Delimiter
  hi! link csBraces Delimiter
  hi! link csParens Delimiter
  hi csUnspecifiedStatement ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi csContextualStatement ctermfg=Green ctermbg=NONE cterm=NONE
  hi csNew ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi csNewType ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi csClass ctermfg=Red ctermbg=NONE cterm=NONE
  hi csEndColon ctermfg=White ctermbg=NONE cterm=NONE
  hi csLogicSymbols ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi! link csXmlComment SpecialComment
  hi! link csXmlCommentLeader SpecialComment
  hi fsharpKeyword ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi fsharpModifier ctermfg=Red ctermbg=NONE cterm=NONE
  hi fsharpModule ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi fsharpSymbol ctermfg=Green ctermbg=NONE cterm=NONE
  hi fsharpKeychar ctermfg=Blue ctermbg=NONE cterm=NONE
  hi fsharpOperator ctermfg=Blue ctermbg=NONE cterm=NONE
  hi fsharpOption ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi fsharpCoreClass ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi fsharpAttribute ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi fsharpAttrib ctermfg=Red ctermbg=NONE cterm=NONE
  hi swiftKeywords ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi swiftMethod ctermfg=Red ctermbg=NONE cterm=NONE
  hi swiftProperty ctermfg=Green ctermbg=NONE cterm=NONE
  hi rubyInclude ctermfg=Red ctermbg=NONE cterm=NONE
  hi rubyControl ctermfg=Red ctermbg=NONE cterm=NONE
  hi rubyDocumentation ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi rubyPredefinedVariable ctermfg=Green ctermbg=NONE cterm=NONE
  hi rubyConstant ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi rubyPseudoVariable ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi rubyInstanceVariable ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi rubyModule ctermfg=Red ctermbg=NONE cterm=NONE
  hi rubyModuleName ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi rubyClass ctermfg=Red ctermbg=NONE cterm=NONE
  hi rubyClassName ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi rubyDefine ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi rubyMethodName ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi rubyCapitalizedMethod ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link rubySymbol Identifier
  hi rubyExceptionHandler2 ctermfg=Red ctermbg=NONE cterm=NONE
  hi perlPackageDecl ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi perlStatementPackage ctermfg=Red ctermbg=NONE cterm=NONE
  hi perlStatementInclude ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi perlStatementStorage ctermfg=Red ctermbg=NONE cterm=NONE
  hi perlStatementInclude ctermfg=Red ctermbg=NONE cterm=NONE
  hi perlStatementFiledesc ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi perlStatementScalar ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi perlStatementList ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi perlStatementFiles ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi perlStatementSocket ctermfg=Red ctermbg=NONE cterm=NONE
  hi perlStatementFlow ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi perlStatementTime ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi perlStatementRegexp ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link perlStringStartEnd Delimiter
  hi perlOperator ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi perlFunction ctermfg=Red ctermbg=NONE cterm=NONE
  hi perlMethod ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi perlVarSimpleMemberName ctermfg=White ctermbg=NONE cterm=NONE
  hi haskellImportKeywords ctermfg=Red ctermbg=NONE cterm=NONE
  hi haskellType ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi haskellWhere ctermfg=Blue ctermbg=NONE cterm=NONE
  hi haskellOperators ctermfg=Green ctermbg=NONE cterm=NONE
  hi! link haskellDeclKeyword Type
  hi haskellDecl ctermfg=Red ctermbg=NONE cterm=NONE
  hi! link luaBraces Delimiter
  hi luaFuncKeyword ctermfg=Red ctermbg=NONE cterm=NONE
  hi luaFuncArgName ctermfg=White ctermbg=NONE cterm=NONE
  hi luaLocal ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link luaSpecialValue Special
  hi! link luaFuncCall Function
  hi moonKeyword ctermfg=Red ctermbg=NONE cterm=NONE
  hi! link moonFunction Delimiter
  hi moonSpecialVar ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi moonInterpDelim ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi moonLuaFunc ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi moonSpecialOp ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi dTypedef ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi dScopeDecl ctermfg=Red ctermbg=NONE cterm=NONE
  hi dLabel ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi dOperator ctermfg=Green ctermbg=NONE cterm=NONE
  hi dAnnotation ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi dEnum ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi dStructure ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi dStorageClass ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi dUserLabel ctermfg=Red ctermbg=NONE cterm=NONE
  hi scalaInstanceDeclaration ctermfg=Green ctermbg=NONE cterm=NONE
  hi scalaCapitalWord ctermfg=Green ctermbg=NONE cterm=NONE
  hi scalaAnnotation ctermfg=Red ctermbg=NONE cterm=NONE
  hi! link scalaSpecial Special
  hi scalaKeywordModifier ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link scalaSquareBracketsBrackets Delimiter
  hi elixirAtom ctermfg=Green ctermbg=NONE cterm=NONE
  hi elixirInclude ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi elixirAlias ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi elixirOperator ctermfg=Blue ctermbg=NONE cterm=NONE
  hi elixirDefine ctermfg=Red ctermbg=NONE cterm=NONE
  hi elixirPrivateDefine ctermfg=Red ctermbg=NONE cterm=NONE
  hi elixirVariable ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi elixirModuleDeclaration ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi elixirKeyword ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi ocamlModule ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi ocamlModPath ctermfg=Green ctermbg=NONE cterm=NONE
  hi ocamlFullMod ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi ocamlKeyword ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link ocamlArrow Delimiter
  hi! link ocamlEqual Operator
  hi! link ocamlModPreRHS Operator
  hi ocamlKeyChar ctermfg=Blue ctermbg=NONE cterm=NONE
  hi ocamlConstructor ctermfg=Green ctermbg=NONE cterm=NONE
  hi ocamlStructEncl ctermfg=Red ctermbg=NONE cterm=NONE
  hi ocamlPpxEncl ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi fortranCall ctermfg=Red ctermbg=NONE cterm=NONE
  hi fortranUnitHeader ctermfg=Red ctermbg=NONE cterm=NONE
  hi fortranKeyword ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi fortranReadWrite ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi fortranIO ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi clojureKeyword ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi clojureSpecial ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi clojureFunc ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi clojureDispatch ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi clojureAnonArg ctermfg=Blue ctermbg=NONE cterm=NONE
  hi erlangAttribute ctermfg=Red ctermbg=NONE cterm=NONE
  hi erlangLocalFuncCall ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi erlangLocalFuncRef ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi erlangGlobalFuncCall ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi erlangType ctermfg=Red ctermbg=NONE cterm=NONE
  hi erlangMap ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi erlangRecord ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi erlangVariable ctermfg=White ctermbg=NONE cterm=NONE
  hi erlangAtom ctermfg=Green ctermbg=NONE cterm=NONE
  hi juliaBlKeyword ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi lispFunc ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi lispDecl ctermfg=Red ctermbg=NONE cterm=NONE
  hi lispVar ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi shQuote ctermfg=Green ctermbg=NONE cterm=NONE
  hi shDeref ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi shDerefSimple ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi shDerefVar ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi shVariable ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi shOperator ctermfg=Blue ctermbg=NONE cterm=NONE
  hi shFunction ctermfg=Red ctermbg=NONE cterm=NONE
  hi! link shCmdSubRegion Delimiter
  hi shCommandSub ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi shStatement ctermfg=Red ctermbg=NONE cterm=NONE
  hi zshPreProc ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi zshDeref ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi zshSubst ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi! link zshSubstDelim Delimiter
  hi zshOption ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi zshTypes ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link zshKeyword Keyword
  hi zshCommands ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi zshShortDeref ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi zshDollarVar ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi zshFunction ctermfg=Red ctermbg=NONE cterm=NONE
  hi fishKeyword ctermfg=Red ctermbg=NONE cterm=NONE
  hi fishStatement ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi fishIdentifier ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi vimLet ctermfg=Red ctermbg=NONE cterm=NONE
  hi vimCommand ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi vimOption ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi vimNotFunc ctermfg=Blue ctermbg=NONE cterm=NONE
  hi vimFunction ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi vimFuncName ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi vimMap ctermfg=Red ctermbg=NONE cterm=NONE
  hi vimMapModKey ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi jsonKeyword ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi jsonQuote ctermfg=White ctermbg=NONE cterm=NONE
  hi jsonBoolean ctermfg=White ctermbg=NONE cterm=NONE
  hi yamlKey ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi yamlConstant ctermfg=Green ctermbg=NONE cterm=NONE
  hi tomlTable ctermfg=Red ctermbg=NONE cterm=NONE
  hi tomlTableArray ctermfg=Red ctermbg=NONE cterm=NONE
  hi tomlKey ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi gitconfigSection ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi gitcommitBlank ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi diffAdded ctermfg=Green ctermbg=NONE cterm=NONE
  hi diffRemoved ctermfg=Red ctermbg=NONE cterm=NONE
  hi diffChanged ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi diffOldFile ctermfg=Blue ctermbg=NONE cterm=NONE
  hi diffNewFile ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi diffFile ctermfg=Green ctermbg=NONE cterm=NONE
  hi! link diffLine Comment
  hi diffIndexLine ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi diffSubname ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi helpHyperTextEntry ctermfg=Red ctermbg=NONE cterm=NONE
  hi helpHyperTextJump ctermfg=Blue ctermbg=NONE cterm=NONE
  hi! link helpSectionDelim Comment
  hi helpHeadline ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi helpURL ctermfg=Blue ctermbg=NONE cterm=underline
  hi helpExample ctermfg=Green ctermbg=NONE cterm=NONE
  hi helpCommand ctermfg=Green ctermbg=NONE cterm=NONE
  hi helpHeader ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi ALEWarningSign ctermfg=DarkYellow ctermbg=Grey cterm=NONE
  hi ALEErrorSign ctermfg=Red ctermbg=Grey cterm=NONE
  hi ALEInfoSign ctermfg=Blue ctermbg=Grey cterm=NONE
  hi ALEError ctermfg=NONE ctermbg=DarkRed cterm=NONE
  hi ALEWarning ctermfg=NONE ctermbg=DarkYellow cterm=NONE
  hi ALEVirtualTextError ctermfg=Grey ctermbg=NONE cterm=NONE
  hi ALEVirtualTextWarning ctermfg=Grey ctermbg=NONE cterm=NONE
  hi ALEVirtualTextInfo ctermfg=Grey ctermbg=NONE cterm=NONE
  hi! link ALEVirtualTextStyleError ALEVirtualTextError
  hi! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
  hi CocHighlightText ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocCodeLens ctermfg=Grey ctermbg=NONE cterm=NONE
  hi! link CocErrorSign ALEErrorSign
  hi! link CocWarningSign ALEWarningSign
  hi! link CocInfoSign ALEInfoSign
  hi! link CocHintSign Label
  hi! link CocErrorHighlight ALEError
  hi! link CocWarningHighlight ALEWarning
  hi! link CocInfoHighlight ALEInfo
  hi! link CocWarningVirtualText ALEVirtualTextWarning
  hi! link CocErrorVirtualText ALEVirtualTextError
  hi! link CocInfoVirtualText ALEVirtualTextInfo
  hi! link CocHintVirtualText ALEVirtualTextInfo
  hi! link CocCodeLens ALEVirtualTextInfo
  hi NERDTreeFlags ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi NERDTreeDirSlash ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi NERDTreeCWD ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi NERDTreeLinkFile ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi NERDTreeLinkTarget ctermfg=Green ctermbg=NONE cterm=NONE
  hi TagbarKind ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi TagbarVisibilityPublic ctermfg=Blue ctermbg=NONE cterm=NONE
  hi TagbarVisibilityPrivate ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi TagbarNestedKind ctermfg=Green ctermbg=NONE cterm=NONE
  hi TagbarSignature ctermfg=Green ctermbg=NONE cterm=NONE
  hi TagbarPseudoID ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi MatchParenCur ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur ctermfg=NONE ctermbg=NONE cterm=underline
  hi StartifyBracket ctermfg=Green ctermbg=NONE cterm=NONE
  hi StartifyHeader ctermfg=Red ctermbg=NONE cterm=NONE
  hi StartifyNumber ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi StartifyPath ctermfg=Green ctermbg=NONE cterm=NONE
  hi StartifySlash ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi StartifySection ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link StartifySpecial Comment
  hi! link StartifyFile Normal
  hi Sneak ctermfg=NONE ctermbg=DarkGreen cterm=NONE
  hi gvSha ctermfg=Green ctermbg=NONE cterm=NONE
  hi gvAuthor ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  if !s:italics
    hi Folded cterm=NONE
    hi VisualNOS cterm=NONE
    hi Todo cterm=NONE
    hi Comment cterm=NONE
    hi SpecialComment cterm=NONE
    hi markdownItalic cterm=NONE
    hi htmlItalic cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: white         #fdd89a           223               White
" Color: black         #3c4542           239               Black
" Color: dark          #4b514f           235               Black
" Color: darkgrey      #535a5a           238               DarkGrey
" Color: darkgreyalt   #5c5f57           238               DarkGrey
" Color: grey          #606357           244               Grey
" Color: greyalt       #636560           244               Grey
" Color: greyer        #7e837c           245               Grey
" Color: red           #fc796b           210               Red
" Color: orange        #ed9c6a           216               DarkYellow
" Color: yellow        #edc074           222               Yellow
" Color: green         #a8cb79           150               Green
" Color: blackgreen    #83986f           65                DarkGreen
" Color: blue          #bcbfb4           153               Blue
" Color: magenta       #d8bbbd           189               Magenta
" Color: darkred       #6f4246           95                DarkRed
" Color: darkgreen     #536049           65                DarkGreen
" Color: darkblue      #435255           67                DarkBlue
" Color: darkorange    #613d13           136               DarkYellow
" Color: lightbrown    #b29668           247               Brown
" Color: brown         #90765a           246               Brown
" Color: darkbrown     #2c281e           237               Black
" Term colors: greyer red green orange blue magenta green white
" Term colors: greyer red green yellow blue magenta green white
" vim: et ts=2 sw=2
